<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbComplementsAP" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbComplementsAP">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../Schemas/AuditControlTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="MergeComplementsAPRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../Schemas/External/dbComplementsAP_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="XxerComplementsApTblCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbComplementsAP"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [FRI AUG 13 15:27:38 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:XxerComplementsApTblCollection>
         <xsl:for-each select="/ns0:MergeComplementsAPRq/ns0:Complements/ns0:Complement">
            <tns:XxerComplementsApTbl>
               <tns:paymentId>
                  <xsl:value-of select="ns0:paymentId"/>
               </tns:paymentId>
               <tns:paymentNumber>
                  <xsl:value-of select="ns0:paymentNumber"/>
               </tns:paymentNumber>
               <tns:nombreEmisor>
                  <xsl:value-of select="ns0:nombreEmisor"/>
               </tns:nombreEmisor>
               <tns:emisorRfc>
                  <xsl:value-of select="ns0:emisorRfc"/>
               </tns:emisorRfc>
               <tns:nombrePreceptor>
                  <xsl:value-of select="ns0:nombrePreceptor"/>
               </tns:nombrePreceptor>
               <tns:receptorRfc>
                  <xsl:value-of select="ns0:receptorRfc"/>
               </tns:receptorRfc>
               <tns:paymentAmount>
                  <xsl:value-of select="ns0:paymentAmount"/>
               </tns:paymentAmount>
               <tns:paymentCurrency>
                  <xsl:value-of select="ns0:paymentCurrency"/>
               </tns:paymentCurrency>
               <tns:paymentDate>
                  <xsl:value-of select="ns0:paymentDate"/>
               </tns:paymentDate>
               <tns:status>
                  <xsl:value-of select="ns0:status"/>
               </tns:status>
               <tns:statusDesc>
                  <xsl:value-of select="ns0:statusDesc"/>
               </tns:statusDesc>
               <tns:folioXml>
                  <xsl:value-of select="ns0:folioXml"/>
               </tns:folioXml>
               <tns:serieXml>
                  <xsl:value-of select="ns0:serieXml"/>
               </tns:serieXml>
               <tns:nombreEmisorXml>
                  <xsl:value-of select="ns0:nombreEmisorXml"/>
               </tns:nombreEmisorXml>
               <tns:emisorRfcXml>
                  <xsl:value-of select="ns0:emisorRfcXml"/>
               </tns:emisorRfcXml>
               <tns:nombreReceptorXml>
                  <xsl:value-of select="ns0:nombreReceptorXml"/>
               </tns:nombreReceptorXml>
               <tns:receptorRfcXml>
                  <xsl:value-of select="ns0:receptorRfcXml"/>
               </tns:receptorRfcXml>
               <tns:totalXml>
                  <xsl:value-of select="ns0:totalXml"/>
               </tns:totalXml>
               <tns:subtotalXml>
                  <xsl:value-of select="ns0:subtotalXml"/>
               </tns:subtotalXml>
               <tns:tipoCambioXml>
                  <xsl:value-of select="ns0:tipoCambioXml"/>
               </tns:tipoCambioXml>
               <tns:monedaXml>
                  <xsl:value-of select="ns0:monedaXml"/>
               </tns:monedaXml>
               <tns:usoCfdiXml>
                  <xsl:value-of select="ns0:usoCfdiXml"/>
               </tns:usoCfdiXml>
               <tns:formaPagoXml>
                  <xsl:value-of select="ns0:formaPagoXml"/>
               </tns:formaPagoXml>
               <tns:tipoComprobanteXml>
                  <xsl:value-of select="ns0:tipoComprobanteXml"/>
               </tns:tipoComprobanteXml>
               <tns:descripcionXml>
                  <xsl:value-of select="ns0:descripcionXml"/>
               </tns:descripcionXml>
               <tns:uuidXml>
                  <xsl:value-of select="ns0:uuidXml"/>
               </tns:uuidXml>
               <tns:fechaXml>
                  <xsl:value-of select="ns0:fechaXml"/>
               </tns:fechaXml>
               <tns:fechaTimbradoXml>
                  <xsl:value-of select="ns0:fechaTimbradoXml"/>
               </tns:fechaTimbradoXml>
               <tns:attribute1>
                  <xsl:value-of select="ns0:attribute1"/>
               </tns:attribute1>
               <tns:attribute2>
                  <xsl:value-of select="ns0:attribute2"/>
               </tns:attribute2>
               <tns:attribute3>
                  <xsl:value-of select="ns0:attribute3"/>
               </tns:attribute3>
               <tns:attribute4>
                  <xsl:value-of select="ns0:attribute4"/>
               </tns:attribute4>
               <tns:attribute5>
                  <xsl:value-of select="ns0:attribute5"/>
               </tns:attribute5>
               <tns:createdBy>
                  <xsl:value-of select="ns0:createdBy"/>
               </tns:createdBy>
               <tns:creationDate>
                  <xsl:value-of select="ns0:creationDate"/>
               </tns:creationDate>
               <tns:lastUpdatedBy>
                  <xsl:value-of select="ns0:lastUpdatedBy"/>
               </tns:lastUpdatedBy>
               <tns:lastUpdateDate>
                  <xsl:value-of select="ns0:lastUpdateDate"/>
               </tns:lastUpdateDate>
               <tns:objectVersionNumber>
                  <xsl:value-of select="ns0:objectVersionNumber"/>
               </tns:objectVersionNumber>
               <ns1:objetoImpXml>
                  <xsl:value-of select="ns0:objetoImpXml"/>
               </ns1:objetoImpXml>
               <ns1:receptorRegimen>
                  <xsl:value-of select="ns0:receptorRegimen"/>
               </ns1:receptorRegimen>
               <ns1:emisorRegimen>
                  <xsl:value-of select="ns0:emisorRegimen"/>
               </ns1:emisorRegimen>
               <ns1:receptorRegimenXml>
                  <xsl:value-of select="ns0:receptorRegimenXml"/>
               </ns1:receptorRegimenXml>
               <ns1:emisorRegimenXml>
                  <xsl:value-of select="ns0:emisorRegimenXml"/>
               </ns1:emisorRegimenXml>
               <ns1:versionXml>
                  <xsl:value-of select="ns0:versionXml"/>
               </ns1:versionXml>
               <ns1:paymentStatus>
                  <xsl:value-of select="ns0:paymentStatus"/>
               </ns1:paymentStatus>
               <ns1:xxerComplementsLinesApTblCollection>
                  <xsl:for-each select="ns0:ComplementsLinesAp/ns0:XxerComplementsLinesApTbl">
                     <ns1:XxerComplementsLinesApTbl>
                        <ns1:drId>
                           <xsl:value-of select="ns0:drId"/>
                        </ns1:drId>
                        <ns1:invoiceId>
                           <xsl:value-of select="ns0:invoiceId"/>
                        </ns1:invoiceId>
                        <ns1:status>
                           <xsl:value-of select="ns0:status"/>
                        </ns1:status>
                        <ns1:statusDesc>
                           <xsl:value-of select="ns0:statusDesc"/>
                        </ns1:statusDesc>
                        <ns1:folioDrXml>
                           <xsl:value-of select="ns0:folioDrXml"/>
                        </ns1:folioDrXml>
                        <ns1:serieDrXml>
                           <xsl:value-of select="ns0:serieDrXml"/>
                        </ns1:serieDrXml>
                        <ns1:uuidDrXml>
                           <xsl:value-of select="ns0:uuidDrXml"/>
                        </ns1:uuidDrXml>
                        <ns1:impSaldoAntDrXml>
                           <xsl:value-of select="ns0:impSaldoAntDrXml"/>
                        </ns1:impSaldoAntDrXml>
                        <ns1:impPagoDrXml>
                           <xsl:value-of select="ns0:impPagoDrXml"/>
                        </ns1:impPagoDrXml>
                        <ns1:impSaldoInsolutoDrXml>
                           <xsl:value-of select="ns0:impSaldoInsolutoDrXml"/>
                        </ns1:impSaldoInsolutoDrXml>
                        <ns1:monedaDrXml>
                           <xsl:value-of select="ns0:monedaDrXml"/>
                        </ns1:monedaDrXml>
                        <ns1:metodoPagoDrXml>
                           <xsl:value-of select="ns0:metodoPagoDrXml"/>
                        </ns1:metodoPagoDrXml>
                        <ns1:tipoCambioDrXml>
                           <xsl:value-of select="ns0:tipoCambioDrXml"/>
                        </ns1:tipoCambioDrXml>
                        <ns1:formaPagoDrXml>
                           <xsl:value-of select="ns0:formaPagoDrXml"/>
                        </ns1:formaPagoDrXml>
                        <ns1:fechaDrXml>
                           <xsl:value-of select="ns0:fechaDrXml"/>
                        </ns1:fechaDrXml>
                        <ns1:attribute1>
                           <xsl:value-of select="ns0:attribute1"/>
                        </ns1:attribute1>
                        <ns1:attribute2>
                           <xsl:value-of select="ns0:attribute2"/>
                        </ns1:attribute2>
                        <ns1:attribute3>
                           <xsl:value-of select="ns0:attribute3"/>
                        </ns1:attribute3>
                        <ns1:attribute4>
                           <xsl:value-of select="ns0:attribute4"/>
                        </ns1:attribute4>
                        <ns1:attribute5>
                           <xsl:value-of select="ns0:attribute5"/>
                        </ns1:attribute5>
                        <ns1:createdBy>
                           <xsl:value-of select="ns0:createdBy"/>
                        </ns1:createdBy>
                        <ns1:creationDate>
                           <xsl:value-of select="ns0:creationDate"/>
                        </ns1:creationDate>
                        <ns1:lastUpdatedBy>
                           <xsl:value-of select="ns0:lastUpdatedBy"/>
                        </ns1:lastUpdatedBy>
                        <ns1:lastUpdateDate>
                           <xsl:value-of select="ns0:lastUpdateDate"/>
                        </ns1:lastUpdateDate>
                        <ns1:objectVersionNumber>
                           <xsl:value-of select="ns0:objectVersionNumber"/>
                        </ns1:objectVersionNumber>
                        <ns1:objetoImpDrXml>
                           <xsl:value-of select="ns0:objetoImpDrXml"/>
                        </ns1:objetoImpDrXml>
                     </ns1:XxerComplementsLinesApTbl>
                  </xsl:for-each>
               </ns1:xxerComplementsLinesApTblCollection>
            </tns:XxerComplementsApTbl>
         </xsl:for-each>
      </tns:XxerComplementsApTblCollection>
   </xsl:template>
</xsl:stylesheet>