<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefCreateLocation/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefCreateLocation" xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0" xmlns:ns4="http://xmlns.oracle.com/apps/cdm/foundation/parties/locationService/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns1="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns7="http://xmlns.oracle.com/adf/svc/types/" xmlns:sdoJava="commonj.sdo/java" xmlns:ns6="http://xmlns.oracle.com/apps/cdm/foundation/parties/partyService/" xmlns:types="http://xmlns.oracle.com/apps/cdm/foundation/parties/locationService/applicationModule/types/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns3="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/location/" xmlns:ns5="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/sourceSystemRef/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="CreateLocationRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../../WSDL/Externals/Cloud/Customers/erpRefCreateLocation.wsdl"/>
            <oracle-xsl-mapper:rootElement name="createLocation" namespace="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefCreateLocation/types"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 07 17:28:43 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:createLocation>
         <tns:location>
            <ns4:Country>
               <xsl:value-of select="/ns0:CreateLocationRq/ns0:Location/ns0:Country"/>
            </ns4:Country>
            <ns4:Address1>
               <xsl:value-of select="concat (/ns0:CreateLocationRq/ns0:Location/ns0:StreetName, &quot; &quot;, /ns0:CreateLocationRq/ns0:Location/ns0:ExternalNumber )"/>
            </ns4:Address1>
            <ns4:Address2>
               <xsl:value-of select="/ns0:CreateLocationRq/ns0:Location/ns0:InternalNumber"/>
            </ns4:Address2>
            <ns4:City>
               <xsl:value-of select="/ns0:CreateLocationRq/ns0:Location/ns0:City"/>
            </ns4:City>
            <ns4:PostalCode>
               <xsl:value-of select="/ns0:CreateLocationRq/ns0:Location/ns0:PostalCode"/>
            </ns4:PostalCode>
            <ns4:State>
               <xsl:value-of select="/ns0:CreateLocationRq/ns0:Location/ns0:State"/>
            </ns4:State>
            <xsl:if test="/ns0:CreateLocationRq/ns0:Location/ns0:County">
               <ns4:County>
                  <xsl:value-of select="/ns0:CreateLocationRq/ns0:Location/ns0:County"/>
               </ns4:County>
            </xsl:if>
            <xsl:if test="/ns0:CreateLocationRq/ns0:Location/ns0:Name">
               <ns4:ShortDescription>
                  <xsl:value-of select="/ns0:CreateLocationRq/ns0:Location/ns0:Name"/>
               </ns4:ShortDescription>
            </xsl:if>
            <xsl:if test="/ns0:CreateLocationRq/ns0:Location/ns0:Description">
               <ns4:Description>
                  <xsl:value-of select="/ns0:CreateLocationRq/ns0:Location/ns0:Description"/>
               </ns4:Description>
            </xsl:if>
            <ns4:CreatedByModule>HZ_WS</ns4:CreatedByModule>
         </tns:location>
      </tns:createLocation>
   </xsl:template>
</xsl:stylesheet>