<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefFindCustomerAccount/types" xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns5="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountContact/" xmlns:ns6="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountContactRole/" xmlns:ns1="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns7="http://xmlns.oracle.com/adf/svc/types/" xmlns:sdoJava="commonj.sdo/java" xmlns:ns8="http://xmlns.oracle.com/apps/cdm/foundation/parties/customerAccountService/" xmlns:ns10="http://xmlns.oracle.com/apps/cdm/foundation/parties/partyService/" xmlns:ns12="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountSiteUse/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountRel/" xmlns:ns4="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccount/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns9="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/sourceSystemRef/" xmlns:ns11="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountSite/" xmlns:types="http://xmlns.oracle.com/apps/cdm/foundation/parties/customerAccountService/applicationModule/types/" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefFindCustomerAccount" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../../WSDL/Externals/Cloud/Customers/erpRefFindCustomerAccount.wsdl"/>
            <oracle-xsl-mapper:rootElement name="findCustomerAccountResponse" namespace="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefFindCustomerAccount/types"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="FindCustomerAccountRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 07 23:21:07 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:FindCustomerAccountRs>
       <xsl:if test="count (/ns0:findCustomerAccountResponse/ns0:result/ns7:Message ) = 0">
            <cmn:Success/>
         </xsl:if>
         <xsl:if test="count (/ns0:findCustomerAccountResponse/ns0:result/ns7:Message ) > 0">
            <cmn:Errors>
               <xsl:for-each select="/ns0:findCustomerAccountResponse/ns0:result/ns7:Message">
                  <cmn:Error>
                     <cmn:ErrorCode>
                        <xsl:value-of select="ns1:code"/>
                     </cmn:ErrorCode>
                     <cmn:ShortDescription>
                        <xsl:value-of select="ns1:severity"/>
                     </cmn:ShortDescription>
                     <cmn:Description>
                        <xsl:value-of select="ns1:message"/>
                     </cmn:Description>
                     <cmn:BusinessProcess>FindCustomerAccount</cmn:BusinessProcess>
                     <cmn:FailedService>ERPIntegrationService</cmn:FailedService>
                     <cmn:TimeStamp>
                        <xsl:value-of select="xp20:current-dateTime ( )"/>
                     </cmn:TimeStamp>
                  </cmn:Error>
               </xsl:for-each>
            </cmn:Errors>
         </xsl:if>
         <xsl:for-each select="/ns0:findCustomerAccountResponse/ns0:result/ns8:Value">
            <tns:CustomerAccountResult>
               <tns:CustomerAccount>
                  <xsl:if test="string-length (ns8:AccountName ) > 0">
                     <tns:Name>
                        <xsl:value-of select="ns8:AccountName"/>
                     </tns:Name>
                  </xsl:if>
                  <xsl:if test="string-length (ns8:CustomerType ) > 0">
                     <tns:CustomerType>
                        <xsl:value-of select="ns8:CustomerType"/>
                     </tns:CustomerType>
                  </xsl:if>
                  <xsl:if test="string-length (ns8:CustomerClassCode ) > 0">
                     <tns:CustomerClassCode>
                        <xsl:value-of select="ns8:CustomerClassCode"/>
                     </tns:CustomerClassCode>
                  </xsl:if>
                  <xsl:for-each select="ns8:CustomerAccountSite">
                     <tns:CustAccountSite>
                        <xsl:if test="string-length (ns8:PartySiteId ) > 0">
                           <tns:PartySiteId>
                              <xsl:value-of select="ns8:PartySiteId"/>
                           </tns:PartySiteId>
                        </xsl:if>
                        <xsl:if test="string-length (ns8:CustomerAccountSiteId ) > 0">
                           <tns:CustAccountSiteId>
                              <xsl:value-of select="ns8:CustomerAccountSiteId"/>
                           </tns:CustAccountSiteId>
                        </xsl:if>
                        <xsl:for-each select="ns8:CustomerAccountSiteUse">
                           <tns:SiteUse>
                              <xsl:if test="string-length (ns8:SiteUseId ) > 0">
                                 <tns:UseId>
                                    <xsl:value-of select="ns8:SiteUseId"/>
                                 </tns:UseId>
                              </xsl:if>
                              <xsl:if test="string-length (ns8:SiteUseCode ) > 0">
                                 <tns:UseCode>
                                    <xsl:value-of select="ns8:SiteUseCode"/>
                                 </tns:UseCode>
                              </xsl:if>
                           </tns:SiteUse>
                        </xsl:for-each>
                     </tns:CustAccountSite>
                  </xsl:for-each>
                  <xsl:if test="string-length (ns8:CustomerAccountId ) > 0">
                     <tns:CustomerAccountId>
                        <xsl:value-of select="ns8:CustomerAccountId"/>
                     </tns:CustomerAccountId>
                  </xsl:if>
                  <xsl:if test="string-length (ns8:PartyId ) > 0">
                     <tns:PartyId>
                        <xsl:value-of select="ns8:PartyId"/>
                     </tns:PartyId>
                  </xsl:if>
               </tns:CustomerAccount>
            </tns:CustomerAccountResult>
         </xsl:for-each>
      </tns:FindCustomerAccountRs>
   </xsl:template>
</xsl:stylesheet>