<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://soa.estrellaroja.com.mx/DigitalStampGERTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/DigitalStampTec" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:cfdi="http://soa.estrellaroja.com.mx/cfd/3" xmlns:ns1="http://soa.estrellaroja.com.mx/sitio_internet/cfd/tipoDatos/tdCFDI" xmlns:ns2="http://soa.estrellaroja.com.mx/TimbreFiscalDigital">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NXSDs/nxsd_createCFDI_JasonRs.xsd"/>
            <oracle-xsl-mapper:rootElement name="invoice" namespace="http://soa.estrellaroja.com.mx/DigitalStampTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/DigitalStampGERTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="createTrxCFDIRs" namespace="http://soa.estrellaroja.com.mx/DigitalStampGERTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE JUL 20 14:40:42 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
 <tns:createTrxCFDIRs>
          <xsl:if test="contains (/ns0:invoice/ns0:data/ns0:stampingCode, &quot;100&quot; )">
            <cmn:Success/>
         </xsl:if>
         <xsl:if test="not (contains (/ns0:invoice/ns0:data/ns0:stampingCode, &quot;100&quot; ) )">
            <cmn:Errors>
               <cmn:Error>
                  <cmn:ErrorCode>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:stampingCode"/>
                  </cmn:ErrorCode>
                  <cmn:ShortDescription>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:stampingMessage"/>
                  </cmn:ShortDescription>
                  <cmn:Description>
                  <xsl:value-of select="concat('Error: ',/ns0:invoice/ns0:data/ns0:stampingCode,' - ',/ns0:invoice/ns0:data/ns0:stampingMessage)"/>
                  </cmn:Description>
                  <cmn:BusinessProcess>createTrxCFDI</cmn:BusinessProcess>
                  <cmn:FailedService>DigitalStampGERTec</cmn:FailedService>
                  <cmn:TimeStamp>
                     <xsl:value-of select="xp20:current-dateTime ( )"/>
                  </cmn:TimeStamp>
               </cmn:Error>
            </cmn:Errors>
         </xsl:if>
         <tns:Return>
            <tns:data>
               <tns:transactionNumber>
                  <xsl:value-of select="/ns0:invoice/ns0:data/ns0:transactionNumber"/>
               </tns:transactionNumber>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:id">
                  <tns:id>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:id"/>
                  </tns:id>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:idRfc">
                  <tns:idRfc>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:idRfc"/>
                  </tns:idRfc>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:certificateNumber">
                  <tns:certificateNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:certificateNumber"/>
                  </tns:certificateNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerRfc">
                  <tns:issuerRfc>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerRfc"/>
                  </tns:issuerRfc>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerName">
                  <tns:issuerName>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerName"/>
                  </tns:issuerName>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerStreet">
                  <tns:issuerStreet>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerStreet"/>
                  </tns:issuerStreet>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerExtNumber">
                  <tns:issuerExtNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerExtNumber"/>
                  </tns:issuerExtNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerIntNumber">
                  <tns:issuerIntNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerIntNumber"/>
                  </tns:issuerIntNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerColony">
                  <tns:issuerColony>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerColony"/>
                  </tns:issuerColony>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerZipCode">
                  <tns:issuerZipCode>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerZipCode"/>
                  </tns:issuerZipCode>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerMunicipality">
                  <tns:issuerMunicipality>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerMunicipality"/>
                  </tns:issuerMunicipality>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerState">
                  <tns:issuerState>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerState"/>
                  </tns:issuerState>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerPhone">
                  <tns:issuerPhone>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerPhone"/>
                  </tns:issuerPhone>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerCountry">
                  <tns:issuerCountry>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerCountry"/>
                  </tns:issuerCountry>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerLocality">
                  <tns:issuerLocality>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerLocality"/>
                  </tns:issuerLocality>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerReference">
                  <tns:issuerReference>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerReference"/>
                  </tns:issuerReference>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchLocality">
                  <tns:branchLocality>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchLocality"/>
                  </tns:branchLocality>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:invoiceDate">
                  <tns:invoiceDate>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:invoiceDate"/>
                  </tns:invoiceDate>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:invoiceType">
                  <tns:invoiceType>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:invoiceType"/>
                  </tns:invoiceType>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:documentType">
                  <tns:documentType>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:documentType"/>
                  </tns:documentType>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:additionalInformation">
                  <tns:additionalInformation>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:additionalInformation"/>
                  </tns:additionalInformation>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:cancellationDate">
                  <tns:cancellationDate>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:cancellationDate"/>
                  </tns:cancellationDate>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:cancellationReason">
                  <tns:cancellationReason>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:cancellationReason"/>
                  </tns:cancellationReason>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:totalWords">
                  <tns:totalWords>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:totalWords"/>
                  </tns:totalWords>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:invoiceSeal">
                  <tns:invoiceSeal>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:invoiceSeal"/>
                  </tns:invoiceSeal>
               </xsl:if>
               <xsl:for-each select="/ns0:invoice/ns0:data/ns0:invoiceItems">
                  <tns:invoiceItems>
                     <xsl:if test="ns0:id">
                        <tns:id>
                           <xsl:value-of select="ns0:id"/>
                        </tns:id>
                     </xsl:if>
                     <xsl:if test="ns0:position">
                        <tns:position>
                           <xsl:value-of select="ns0:position"/>
                        </tns:position>
                     </xsl:if>
                     <xsl:if test="ns0:description">
                        <tns:description>
                           <xsl:value-of select="ns0:description"/>
                        </tns:description>
                     </xsl:if>
                     <xsl:if test="ns0:productServiceKey">
                        <tns:productServiceKey>
                           <xsl:value-of select="ns0:productServiceKey"/>
                        </tns:productServiceKey>
                     </xsl:if>
                     <xsl:if test="ns0:productServDescription">
                        <tns:productServDescription>
                           <xsl:value-of select="ns0:productServDescription"/>
                        </tns:productServDescription>
                     </xsl:if>
                     <xsl:if test="ns0:quantity">
                        <tns:quantity>
                           <xsl:value-of select="ns0:quantity"/>
                        </tns:quantity>
                     </xsl:if>
                     <xsl:if test="ns0:discount">
                        <tns:discount>
                           <xsl:value-of select="ns0:discount"/>
                        </tns:discount>
                     </xsl:if>
                     <xsl:if test="ns0:vatPercentage">
                        <tns:vatPercentage>
                           <xsl:value-of select="ns0:vatPercentage"/>
                        </tns:vatPercentage>
                     </xsl:if>
                     <xsl:if test="ns0:unit">
                        <tns:unit>
                           <xsl:value-of select="ns0:unit"/>
                        </tns:unit>
                     </xsl:if>
                     <xsl:if test="ns0:unitKey">
                        <tns:unitKey>
                           <xsl:value-of select="ns0:unitKey"/>
                        </tns:unitKey>
                     </xsl:if>
                     <xsl:if test="ns0:unitPrice">
                        <tns:unitPrice>
                           <xsl:value-of select="ns0:unitPrice"/>
                        </tns:unitPrice>
                     </xsl:if>
                     <xsl:if test="ns0:taxBase">
                        <tns:taxBase>
                           <xsl:value-of select="ns0:taxBase"/>
                        </tns:taxBase>
                     </xsl:if>
                     <xsl:if test="ns0:tax">
                        <tns:tax>
                           <xsl:value-of select="ns0:tax"/>
                        </tns:tax>
                     </xsl:if>
                     <xsl:if test="ns0:factorType">
                        <tns:factorType>
                           <xsl:value-of select="ns0:factorType"/>
                        </tns:factorType>
                     </xsl:if>
                     <xsl:if test="ns0:rateFee">
                        <tns:rateFee>
                           <xsl:value-of select="ns0:rateFee"/>
                        </tns:rateFee>
                     </xsl:if>
                     <xsl:if test="ns0:stpsPercentage">
                        <tns:stpsPercentage>
                           <xsl:value-of select="ns0:stpsPercentage"/>
                        </tns:stpsPercentage>
                     </xsl:if>
                     <xsl:if test="ns0:impPercentage">
                        <tns:impPercentage>
                           <xsl:value-of select="ns0:impPercentage"/>
                        </tns:impPercentage>
                     </xsl:if>
                     <xsl:if test="ns0:retentionVatPercentage">
                        <tns:retentionVatPercentage>
                           <xsl:value-of select="ns0:retentionVatPercentage"/>
                        </tns:retentionVatPercentage>
                     </xsl:if>
                     <xsl:if test="ns0:retentionRatePercentage">
                        <tns:retentionRatePercentage>
                           <xsl:value-of select="ns0:retentionRatePercentage"/>
                        </tns:retentionRatePercentage>
                     </xsl:if>
                     <xsl:if test="ns0:amount">
                        <tns:amount>
                           <xsl:value-of select="ns0:amount"/>
                        </tns:amount>
                     </xsl:if>
                     <xsl:if test="ns0:subtotal">
                        <tns:subtotal>
                           <xsl:value-of select="ns0:subtotal"/>
                        </tns:subtotal>
                     </xsl:if>
                     <xsl:if test="ns0:vat">
                        <tns:vat>
                           <xsl:value-of select="ns0:vat"/>
                        </tns:vat>
                     </xsl:if>
                     <xsl:if test="ns0:stps">
                        <tns:stps>
                           <xsl:value-of select="ns0:stps"/>
                        </tns:stps>
                     </xsl:if>
                     <xsl:if test="ns0:imp">
                        <tns:imp>
                           <xsl:value-of select="ns0:imp"/>
                        </tns:imp>
                     </xsl:if>
                     <xsl:if test="ns0:identificationNumber">
                        <tns:identificationNumber>
                           <xsl:value-of select="ns0:identificationNumber"/>
                        </tns:identificationNumber>
                     </xsl:if>
                     <xsl:if test="ns0:retentionVat">
                        <tns:retentionVat>
                           <xsl:value-of select="ns0:retentionVat"/>
                        </tns:retentionVat>
                     </xsl:if>
                     <xsl:if test="ns0:retentionRate">
                        <tns:retentionRate>
                           <xsl:value-of select="ns0:retentionRate"/>
                        </tns:retentionRate>
                     </xsl:if>
                     <xsl:if test="ns0:total">
                        <tns:total>
                           <xsl:value-of select="ns0:total"/>
                        </tns:total>
                     </xsl:if>
                     <xsl:if test="ns0:st">
                        <tns:st>
                           <xsl:value-of select="ns0:st"/>
                        </tns:st>
                     </xsl:if>
                     <xsl:for-each select="ns0:propertyAccount">
                        <tns:propertyAccount>
                           <xsl:value-of select="."/>
                        </tns:propertyAccount>
                     </xsl:for-each>
                     <xsl:if test="ns0:references">
                        <tns:references>
                           <xsl:value-of select="ns0:references"/>
                        </tns:references>
                     </xsl:if>
                     <xsl:if test="ns0:branchSale">
                        <tns:branchSale>
                           <xsl:value-of select="ns0:branchSale"/>
                        </tns:branchSale>
                     </xsl:if>
                     <xsl:if test="ns0:taxObject">
                        <tns:taxObject>
                           <xsl:value-of select="ns0:taxObject"/>
                        </tns:taxObject>
                     </xsl:if>
                     <xsl:if test="ns0:addendumInterfaceApply">
                        <tns:addendumInterfaceApply>
                           <xsl:value-of select="ns0:addendumInterfaceApply"/>
                        </tns:addendumInterfaceApply>
                     </xsl:if>
                     <xsl:if test="ns0:addendumInterfaceType">
                        <tns:addendumInterfaceType>
                           <xsl:value-of select="ns0:addendumInterfaceType"/>
                        </tns:addendumInterfaceType>
                     </xsl:if>
                     <xsl:if test="ns0:addendumInterfaceConcept">
                        <tns:addendumInterfaceConcept>
                           <xsl:value-of select="ns0:addendumInterfaceConcept"/>
                        </tns:addendumInterfaceConcept>
                     </xsl:if>
                     <xsl:if test="ns0:customsName">
                        <tns:customsName>
                           <xsl:value-of select="ns0:customsName"/>
                        </tns:customsName>
                     </xsl:if>
                     <xsl:if test="ns0:customsNumber">
                        <tns:customsNumber>
                           <xsl:value-of select="ns0:customsNumber"/>
                        </tns:customsNumber>
                     </xsl:if>
                     <xsl:if test="ns0:customsDate">
                        <tns:customsDate>
                           <xsl:value-of select="ns0:customsDate"/>
                        </tns:customsDate>
                     </xsl:if>
                     <xsl:if test="ns0:idInvoice">
                        <tns:idInvoice>
                           <xsl:value-of select="ns0:idInvoice"/>
                        </tns:idInvoice>
                     </xsl:if>
                  </tns:invoiceItems>
               </xsl:for-each>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:totalItems">
                  <tns:totalItems>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:totalItems"/>
                  </tns:totalItems>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:localRetentionName">
                  <tns:localRetentionName>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:localRetentionName"/>
                  </tns:localRetentionName>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:localRetentionPercentage">
                  <tns:localRetentionPercentage>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:localRetentionPercentage"/>
                  </tns:localRetentionPercentage>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:localRetentionAmount">
                  <tns:localRetentionAmount>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:localRetentionAmount"/>
                  </tns:localRetentionAmount>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:totalVat">
                  <tns:totalVat>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:totalVat"/>
                  </tns:totalVat>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:totalStps">
                  <tns:totalStps>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:totalStps"/>
                  </tns:totalStps>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:totalSt">
                  <tns:totalSt>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:totalSt"/>
                  </tns:totalSt>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:totalTip">
                  <tns:totalTip>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:totalTip"/>
                  </tns:totalTip>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:retentionVat">
                  <tns:retentionVat>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:retentionVat"/>
                  </tns:retentionVat>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:retentionRate">
                  <tns:retentionRate>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:retentionRate"/>
                  </tns:retentionRate>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:totalTaxBase">
                  <tns:totalTaxBase>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:totalTaxBase"/>
                  </tns:totalTaxBase>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:subtotal">
                  <tns:subtotal>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:subtotal"/>
                  </tns:subtotal>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:total">
                  <tns:total>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:total"/>
                  </tns:total>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:serie">
                  <tns:serie>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:serie"/>
                  </tns:serie>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchId">
                  <tns:branchId>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchId"/>
                  </tns:branchId>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchNumber">
                  <tns:branchNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchNumber"/>
                  </tns:branchNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchName">
                  <tns:branchName>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchName"/>
                  </tns:branchName>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchStreet">
                  <tns:branchStreet>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchStreet"/>
                  </tns:branchStreet>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchExtNumber">
                  <tns:branchExtNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchExtNumber"/>
                  </tns:branchExtNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchIntNumber">
                  <tns:branchIntNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchIntNumber"/>
                  </tns:branchIntNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchColony">
                  <tns:branchColony>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchColony"/>
                  </tns:branchColony>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchZipCode">
                  <tns:branchZipCode>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchZipCode"/>
                  </tns:branchZipCode>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchMunicipality">
                  <tns:branchMunicipality>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchMunicipality"/>
                  </tns:branchMunicipality>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchState">
                  <tns:branchState>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchState"/>
                  </tns:branchState>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchReference">
                  <tns:branchReference>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchReference"/>
                  </tns:branchReference>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchPhone">
                  <tns:branchPhone>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchPhone"/>
                  </tns:branchPhone>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:branchCountry">
                  <tns:branchCountry>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchCountry"/>
                  </tns:branchCountry>
               </xsl:if>
               <tns:branchSale>
                  <xsl:value-of select="/ns0:invoice/ns0:data/ns0:branchSale"/>
               </tns:branchSale>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverName">
                  <tns:receiverName>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverName"/>
                  </tns:receiverName>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverTaxRegime">
                  <tns:receiverTaxRegime>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverTaxRegime"/>
                  </tns:receiverTaxRegime>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverEmail">
                  <tns:receiverEmail>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverEmail"/>
                  </tns:receiverEmail>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverRfc">
                  <tns:receiverRfc>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverRfc"/>
                  </tns:receiverRfc>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverPhone">
                  <tns:receiverPhone>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverPhone"/>
                  </tns:receiverPhone>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverStreet">
                  <tns:receiverStreet>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverStreet"/>
                  </tns:receiverStreet>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverExtNumber">
                  <tns:receiverExtNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverExtNumber"/>
                  </tns:receiverExtNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverIntNumber">
                  <tns:receiverIntNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverIntNumber"/>
                  </tns:receiverIntNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverColony">
                  <tns:receiverColony>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverColony"/>
                  </tns:receiverColony>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverZipCode">
                  <tns:receiverZipCode>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverZipCode"/>
                  </tns:receiverZipCode>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverMunicipality">
                  <tns:receiverMunicipality>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverMunicipality"/>
                  </tns:receiverMunicipality>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverState">
                  <tns:receiverState>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverState"/>
                  </tns:receiverState>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverCountry">
                  <tns:receiverCountry>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverCountry"/>
                  </tns:receiverCountry>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverPassport">
                  <tns:receiverPassport>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverPassport"/>
                  </tns:receiverPassport>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverCfdiUse">
                  <tns:receiverCfdiUse>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverCfdiUse"/>
                  </tns:receiverCfdiUse>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:receiverReference">
                  <tns:receiverReference>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:receiverReference"/>
                  </tns:receiverReference>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:paymentMethod">
                  <tns:paymentMethod>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentMethod"/>
                  </tns:paymentMethod>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:currency">
                  <tns:currency>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:currency"/>
                  </tns:currency>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:issuerTaxRegime">
                  <tns:issuerTaxRegime>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:issuerTaxRegime"/>
                  </tns:issuerTaxRegime>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:currencyExchangeRate">
                  <tns:currencyExchangeRate>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:currencyExchangeRate"/>
                  </tns:currencyExchangeRate>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:paymentMethodSelect">
                  <tns:paymentMethodSelect>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentMethodSelect"/>
                  </tns:paymentMethodSelect>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:addedPaymentMethods">
                  <tns:addedPaymentMethods>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:addedPaymentMethods"/>
                  </tns:addedPaymentMethods>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:paymentForm">
                  <tns:paymentForm>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentForm"/>
                  </tns:paymentForm>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:paymentCondition">
                  <tns:paymentCondition>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentCondition"/>
                  </tns:paymentCondition>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:paymentStatus">
                  <tns:paymentStatus>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentStatus"/>
                  </tns:paymentStatus>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:paymentAccountNumber">
                  <tns:paymentAccountNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentAccountNumber"/>
                  </tns:paymentAccountNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:discount">
                  <tns:discount>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:discount"/>
                  </tns:discount>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:comments">
                  <tns:comments>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:comments"/>
                  </tns:comments>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:approvalNumber">
                  <tns:approvalNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:approvalNumber"/>
                  </tns:approvalNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:approvalYear">
                  <tns:approvalYear>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:approvalYear"/>
                  </tns:approvalYear>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:stampingUuid">
                  <tns:stampingUuid>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:stampingUuid"/>
                  </tns:stampingUuid>
               </xsl:if>
              <xsl:choose>
                  <xsl:when test="/ns0:invoice/ns0:data/ns0:stampingDate">
                     <tns:stampingDate>
                        <xsl:value-of select="/ns0:invoice/ns0:data/ns0:stampingDate"/>
                     </tns:stampingDate>
                  </xsl:when>
                  <xsl:otherwise>
                     <tns:stampingDate>
                        <xsl:value-of select="xp20:format-dateTime (xp20:current-dateTime ( ),'[Y0001]-[M01]-[D01]T[H01]:[m01]:[s01]')"/>
                     </tns:stampingDate>
                  </xsl:otherwise>
               </xsl:choose>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:stampingCertificateNumber">
                  <tns:stampingCertificateNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:stampingCertificateNumber"/>
                  </tns:stampingCertificateNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:stampingSeal">
                  <tns:stampingSeal>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:stampingSeal"/>
                  </tns:stampingSeal>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:documentNumber">
                  <tns:documentNumber>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:documentNumber"/>
                  </tns:documentNumber>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:discountReason">
                  <tns:discountReason>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:discountReason"/>
                  </tns:discountReason>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:urlPdf">
                  <tns:urlPdf>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:urlPdf"/>
                  </tns:urlPdf>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:stampingCode">
                  <tns:stampingCode>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:stampingCode"/>
                  </tns:stampingCode>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:stampingMessage">
                  <tns:stampingMessage>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:stampingMessage"/>
                  </tns:stampingMessage>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:urlXml">
                  <tns:urlXml>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:urlXml"/>
                  </tns:urlXml>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:status">
                  <tns:status>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:status"/>
                  </tns:status>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:service">
                  <tns:service>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:service"/>
                  </tns:service>
               </xsl:if>
               <tns:export>
                  <xsl:value-of select="/ns0:invoice/ns0:data/ns0:export"/>
               </tns:export>
               <tns:typeInvoice>
                  <xsl:value-of select="/ns0:invoice/ns0:data/ns0:typeInvoice"/>
               </tns:typeInvoice>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:globalInformation">
                  <tns:globalInformation>
                     <xsl:if test="/ns0:invoice/ns0:data/ns0:globalInformation/ns0:periodicity">
                        <tns:periodicity>
                           <xsl:value-of select="/ns0:invoice/ns0:data/ns0:globalInformation/ns0:periodicity"/>
                        </tns:periodicity>
                     </xsl:if>
                     <xsl:if test="/ns0:invoice/ns0:data/ns0:globalInformation/ns0:months">
                        <tns:months>
                           <xsl:value-of select="/ns0:invoice/ns0:data/ns0:globalInformation/ns0:months"/>
                        </tns:months>
                     </xsl:if>
                     <xsl:if test="/ns0:invoice/ns0:data/ns0:globalInformation/ns0:year">
                        <tns:year>
                           <xsl:value-of select="/ns0:invoice/ns0:data/ns0:globalInformation/ns0:year"/>
                        </tns:year>
                     </xsl:if>
                  </tns:globalInformation>
               </xsl:if>
               <xsl:for-each select="/ns0:invoice/ns0:data/ns0:relatedCfdi">
                  <tns:relatedCfdi>
                     <xsl:if test="ns0:relationshipType">
                        <tns:relationshipType>
                           <xsl:value-of select="ns0:relationshipType"/>
                        </tns:relationshipType>
                     </xsl:if>
                     <xsl:for-each select="ns0:uuids">
                        <tns:uuids>
                           <xsl:value-of select="."/>
                        </tns:uuids>
                     </xsl:for-each>
                  </tns:relatedCfdi>
               </xsl:for-each>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:originSystem">
                  <tns:originSystem>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:originSystem"/>
                  </tns:originSystem>
               </xsl:if>
               <xsl:if test="/ns0:invoice/ns0:data/ns0:documentTypeDescription">
                  <tns:documentTypeDescription>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:documentTypeDescription"/>
                  </tns:documentTypeDescription>
               </xsl:if>
               <tns:paymentComplement>
                  <tns:totalPaymentsAmount>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalPaymentsAmount"/>
                  </tns:totalPaymentsAmount>
                  <tns:totalRetentionIEPS>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalRetentionIEPS"/>
                  </tns:totalRetentionIEPS>
                  <tns:totalRetentionISR>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalRetentionISR"/>
                  </tns:totalRetentionISR>
                  <tns:totalRetentionVat>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalRetentionVat"/>
                  </tns:totalRetentionVat>
                  <tns:totalTaxBaseVat0>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalTaxBaseVat0"/>
                  </tns:totalTaxBaseVat0>
                  <tns:totalTaxBaseVat16>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalTaxBaseVat16"/>
                  </tns:totalTaxBaseVat16>
                  <tns:totalTaxBaseVat8>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalTaxBaseVat8"/>
                  </tns:totalTaxBaseVat8>
                  <tns:totalTaxBaseVatExento>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalTaxBaseVatExento"/>
                  </tns:totalTaxBaseVatExento>
                  <tns:totalTaxVat0>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalTaxVat0"/>
                  </tns:totalTaxVat0>
                  <tns:totalTaxVat16>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalTaxVat16"/>
                  </tns:totalTaxVat16>
                  <tns:totalTaxVat8>
                     <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:totalTaxVat8"/>
                  </tns:totalTaxVat8>
                  <xsl:for-each select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:payments">
                     <tns:payments>
                        <tns:paymentDate>
                           <xsl:value-of select="ns0:paymentDate"/>
                        </tns:paymentDate>
                        <tns:paymentWay>
                           <xsl:value-of select="ns0:paymentWay"/>
                        </tns:paymentWay>
                        <tns:currency>
                           <xsl:value-of select="ns0:currency"/>
                        </tns:currency>
                        <tns:currencyExchange>
                           <xsl:value-of select="ns0:currencyExchange"/>
                        </tns:currencyExchange>
                        <tns:amount>
                           <xsl:value-of select="ns0:amount"/>
                        </tns:amount>
                        <tns:operationNumber>
                           <xsl:value-of select="ns0:operationNumber"/>
                        </tns:operationNumber>
                        <tns:ordAccIusserRfc>
                           <xsl:value-of select="ns0:ordAccIusserRfc"/>
                        </tns:ordAccIusserRfc>
                        <tns:bankName>
                           <xsl:value-of select="ns0:bankName"/>
                        </tns:bankName>
                        <tns:payerAccount>
                           <xsl:value-of select="ns0:payerAccount"/>
                        </tns:payerAccount>
                        <tns:benAccIssuerRfc>
                           <xsl:value-of select="ns0:benAccIssuerRfc"/>
                        </tns:benAccIssuerRfc>
                        <tns:beneficiaryAccount>
                           <xsl:value-of select="ns0:beneficiaryAccount"/>
                        </tns:beneficiaryAccount>
                        <tns:paymentStringType>
                           <xsl:value-of select="ns0:paymentStringType"/>
                        </tns:paymentStringType>
                        <tns:paymentCert>
                           <xsl:value-of select="ns0:paymentCert"/>
                        </tns:paymentCert>
                        <tns:paymentString>
                           <xsl:value-of select="ns0:paymentString"/>
                        </tns:paymentString>
                        <tns:paymentSeal>
                           <xsl:value-of select="ns0:paymentSeal"/>
                        </tns:paymentSeal>
                        <tns:version>
                           <xsl:value-of select="ns0:version"/>
                        </tns:version>
                        <xsl:for-each select="ns0:relatedDocuments">
                           <tns:relatedDocuments>
                              <tns:documentId>
                                 <xsl:value-of select="ns0:documentId"/>
                              </tns:documentId>
                              <tns:serie>
                                 <xsl:value-of select="ns0:serie"/>
                              </tns:serie>
                              <tns:folio>
                                 <xsl:value-of select="ns0:folio"/>
                              </tns:folio>
                              <tns:currency>
                                 <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:payments/ns0:currency"/>
                              </tns:currency>
                              <tns:currencyExchange>
                                 <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:payments/ns0:currencyExchange"/>
                              </tns:currencyExchange>
                              <tns:paymentMethod>
                                 <xsl:value-of select="ns0:paymentMethod"/>
                              </tns:paymentMethod>
                              <tns:partialityNumber>
                                 <xsl:value-of select="ns0:partialityNumber"/>
                              </tns:partialityNumber>
                              <tns:previousBalance>
                                 <xsl:value-of select="ns0:previousBalance"/>
                              </tns:previousBalance>
                              <tns:paidAmount>
                                 <xsl:value-of select="ns0:paidAmount"/>
                              </tns:paidAmount>
                              <tns:outstandingBalance>
                                 <xsl:value-of select="ns0:outstandingBalance"/>
                              </tns:outstandingBalance>
                              <tns:taxObject>
                                 <xsl:value-of select="ns0:taxObject"/>
                              </tns:taxObject>
                              <xsl:for-each select="ns0:retainedTaxes">
                                 <tns:retainedTaxes>
                                    <tns:amount>
                                       <xsl:value-of select="ns0:amount"/>
                                    </tns:amount>
                                    <tns:factorType>
                                       <xsl:value-of select="ns0:factorType"/>
                                    </tns:factorType>
                                    <tns:rateFee>
                                       <xsl:value-of select="ns0:rateFee"/>
                                    </tns:rateFee>
                                    <tns:tax>
                                       <xsl:value-of select="ns0:tax"/>
                                    </tns:tax>
                                    <tns:taxBase>
                                       <xsl:value-of select="ns0:taxBase"/>
                                    </tns:taxBase>
                                 </tns:retainedTaxes>
                              </xsl:for-each>
                              <xsl:for-each select="ns0:transferredsTaxes">
                                 <tns:transferredsTaxes>
                                    <tns:amount>
                                       <xsl:value-of select="ns0:amount"/>
                                    </tns:amount>
                                    <tns:factorType>
                                       <xsl:value-of select="ns0:factorType"/>
                                    </tns:factorType>
                                    <tns:rateFee>
                                       <xsl:value-of select="ns0:rateFee"/>
                                    </tns:rateFee>
                                    <tns:tax>
                                       <xsl:value-of select="ns0:tax"/>
                                    </tns:tax>
                                    <tns:taxBase>
                                       <xsl:value-of select="ns0:taxBase"/>
                                    </tns:taxBase>
                                 </tns:transferredsTaxes>
                              </xsl:for-each>
                           </tns:relatedDocuments>
                        </xsl:for-each>
                        <xsl:for-each select="ns0:retainedTaxes">
                           <tns:retainedTaxes>
                              <tns:amount>
                                 <xsl:value-of select="/ns0:invoice/ns0:data/ns0:paymentComplement/ns0:payments/ns0:amount"/>
                              </tns:amount>
                              <tns:factorType>
                                 <xsl:value-of select="ns0:factorType"/>
                              </tns:factorType>
                              <tns:rateFee>
                                 <xsl:value-of select="ns0:rateFee"/>
                              </tns:rateFee>
                              <tns:tax>
                                 <xsl:value-of select="ns0:tax"/>
                              </tns:tax>
                              <tns:taxBase>
                                 <xsl:value-of select="ns0:taxBase"/>
                              </tns:taxBase>
                           </tns:retainedTaxes>
                        </xsl:for-each>
                        <xsl:for-each select="ns0:transferredsTaxes">
                           <tns:transferredsTaxes>
                              <tns:amount>
                                 <xsl:value-of select="ns0:amount"/>
                              </tns:amount>
                              <tns:factorType>
                                 <xsl:value-of select="ns0:factorType"/>
                              </tns:factorType>
                              <tns:rateFee>
                                 <xsl:value-of select="ns0:rateFee"/>
                              </tns:rateFee>
                              <tns:tax>
                                 <xsl:value-of select="ns0:tax"/>
                              </tns:tax>
                              <tns:taxBase>
                                 <xsl:value-of select="ns0:taxBase"/>
                              </tns:taxBase>
                           </tns:transferredsTaxes>
                        </xsl:for-each>
                     </tns:payments>
                  </xsl:for-each>
               </tns:paymentComplement>
            </tns:data>
            <tns:message>
               <xsl:value-of select="/ns0:invoice/ns0:message"/>
            </tns:message>
            <tns:responseCode>
               <xsl:value-of select="/ns0:invoice/ns0:responseCode"/>
            </tns:responseCode>
         </tns:Return>
      </tns:createTrxCFDIRs>
   </xsl:template>
</xsl:stylesheet>