<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/DigitalStampGERTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:cfdi="http://soa.estrellaroja.com.mx/cfd/3" xmlns:ns1="http://soa.estrellaroja.com.mx/sitio_internet/cfd/tipoDatos/tdCFDI" xmlns:ns2="http://soa.estrellaroja.com.mx/TimbreFiscalDigital" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/DigitalStampGERTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="createTrxCFDIRq" namespace="http://soa.estrellaroja.com.mx/DigitalStampGERTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NXSDs/nxsd_createCFDI_Jason_Rq.xsd"/>
            <oracle-xsl-mapper:rootElement name="invoice" namespace="http://soa.estrellaroja.com.mx/DigitalStampGERTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE JUL 20 14:34:09 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:invoice>
         <ns0:invoice>
            <ns0:transactionNumber>
               <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:transactionNumber"/>
            </ns0:transactionNumber>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:id">
               <ns0:id>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:id"/>
               </ns0:id>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:idRfc">
               <ns0:idRfc>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:idRfc"/>
               </ns0:idRfc>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:certificateNumber">
               <ns0:certificateNumber>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:certificateNumber"/>
               </ns0:certificateNumber>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerRfc">
               <ns0:issuerRfc>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerRfc"/>
               </ns0:issuerRfc>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerName">
               <ns0:issuerName>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerName"/>
               </ns0:issuerName>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerStreet">
               <ns0:issuerStreet>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerStreet"/>
               </ns0:issuerStreet>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerExtNumber">
               <ns0:issuerExtNumber>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerExtNumber"/>
               </ns0:issuerExtNumber>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerIntNumber">
               <ns0:issuerIntNumber>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerIntNumber"/>
               </ns0:issuerIntNumber>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerColony">
               <ns0:issuerColony>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerColony"/>
               </ns0:issuerColony>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerZipCode">
               <ns0:issuerZipCode>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerZipCode"/>
               </ns0:issuerZipCode>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerMunicipality">
               <ns0:issuerMunicipality>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerMunicipality"/>
               </ns0:issuerMunicipality>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerState">
               <ns0:issuerState>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerState"/>
               </ns0:issuerState>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerPhone">
               <ns0:issuerPhone>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerPhone"/>
               </ns0:issuerPhone>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerCountry">
               <ns0:issuerCountry>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerCountry"/>
               </ns0:issuerCountry>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:invoiceDate">
               <ns0:invoiceDate>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:invoiceDate"/>
               </ns0:invoiceDate>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:documentType">
               <ns0:documentType>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:documentType"/>
               </ns0:documentType>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:additionalInformation">
               <ns0:additionalInformation>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:additionalInformation"/>
               </ns0:additionalInformation>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:cancellationDate">
               <ns0:cancellationDate>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:cancellationDate"/>
               </ns0:cancellationDate>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalWords">
               <ns0:totalWords>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalWords"/>
               </ns0:totalWords>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:originSystem">
               <ns0:originSystem>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:originSystem"/>
               </ns0:originSystem>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalItems">
               <ns0:totalItems>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalItems"/>
               </ns0:totalItems>
            </xsl:if>
            <ns0:localRetentionName>
               <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:localRetentionName"/>
            </ns0:localRetentionName>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:localRetentionPercentage">
               <ns0:localRetentionPercentage>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:localRetentionPercentage"/>
               </ns0:localRetentionPercentage>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:localRetentionAmount">
               <ns0:localRetentionAmount>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:localRetentionAmount"/>
               </ns0:localRetentionAmount>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalVat">
               <ns0:totalVat>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalVat"/>
               </ns0:totalVat>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalStps">
               <ns0:totalStps>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalStps"/>
               </ns0:totalStps>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalSt">
               <ns0:totalSt>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalSt"/>
               </ns0:totalSt>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalTip">
               <ns0:totalTip>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalTip"/>
               </ns0:totalTip>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:retentionVat">
               <ns0:retentionVat>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:retentionVat"/>
               </ns0:retentionVat>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:retentionRate">
               <ns0:retentionRate>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:retentionRate"/>
               </ns0:retentionRate>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalTaxBase">
               <ns0:totalTaxBase>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:totalTaxBase"/>
               </ns0:totalTaxBase>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:subtotal">
               <ns0:subtotal>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:subtotal"/>
               </ns0:subtotal>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:total">
               <ns0:total>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:total"/>
               </ns0:total>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:serie">
               <ns0:serie>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:serie"/>
               </ns0:serie>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchId">
               <ns0:branchId>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchId"/>
               </ns0:branchId>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchNumber">
               <ns0:branchNumber>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchNumber"/>
               </ns0:branchNumber>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchName">
               <ns0:branchName>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchName"/>
               </ns0:branchName>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchStreet">
               <ns0:branchStreet>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchStreet"/>
               </ns0:branchStreet>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchExtNumber">
               <ns0:branchExtNumber>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchExtNumber"/>
               </ns0:branchExtNumber>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchIntNumber">
               <ns0:branchIntNumber>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchIntNumber"/>
               </ns0:branchIntNumber>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchColony">
               <ns0:branchColony>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchColony"/>
               </ns0:branchColony>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchZipCode">
               <ns0:branchZipCode>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchZipCode"/>
               </ns0:branchZipCode>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchMunicipality">
               <ns0:branchMunicipality>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchMunicipality"/>
               </ns0:branchMunicipality>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchState">
               <ns0:branchState>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchState"/>
               </ns0:branchState>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchReference">
               <ns0:branchReference>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchReference"/>
               </ns0:branchReference>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchPhone">
               <ns0:branchPhone>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchPhone"/>
               </ns0:branchPhone>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchCountry">
               <ns0:branchCountry>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchCountry"/>
               </ns0:branchCountry>
            </xsl:if>
            <ns0:branchSale>
               <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:branchSale"/>
            </ns0:branchSale>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverName">
               <ns0:receiverName>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverName"/>
               </ns0:receiverName>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverTaxRegime">
               <ns0:receiverTaxRegime>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverTaxRegime"/>
               </ns0:receiverTaxRegime>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverEmail">
               <ns0:receiverEmail>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverEmail"/>
               </ns0:receiverEmail>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverRfc">
               <ns0:receiverRfc>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverRfc"/>
               </ns0:receiverRfc>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverPhone">
               <ns0:receiverPhone>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverPhone"/>
               </ns0:receiverPhone>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverStreet">
               <ns0:receiverStreet>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverStreet"/>
               </ns0:receiverStreet>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverExtNumber">
               <ns0:receiverExtNumber>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverExtNumber"/>
               </ns0:receiverExtNumber>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverIntNumber">
               <ns0:receiverIntNumber>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverIntNumber"/>
               </ns0:receiverIntNumber>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverColony">
               <ns0:receiverColony>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverColony"/>
               </ns0:receiverColony>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverZipCode">
               <ns0:receiverZipCode>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverZipCode"/>
               </ns0:receiverZipCode>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverMunicipality">
               <ns0:receiverMunicipality>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverMunicipality"/>
               </ns0:receiverMunicipality>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverState">
               <ns0:receiverState>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverState"/>
               </ns0:receiverState>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverCountry">
               <ns0:receiverCountry>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverCountry"/>
               </ns0:receiverCountry>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverPassport">
               <ns0:receiverPassport>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverPassport"/>
               </ns0:receiverPassport>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverCfdiUse">
               <ns0:receiverCfdiUse>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:receiverCfdiUse"/>
               </ns0:receiverCfdiUse>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentMethod">
               <ns0:paymentMethod>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentMethod"/>
               </ns0:paymentMethod>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:currency">
               <ns0:currency>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:currency"/>
               </ns0:currency>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerTaxRegime">
               <ns0:issuerTaxRegime>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:issuerTaxRegime"/>
               </ns0:issuerTaxRegime>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:currencyExchangeRate">
               <ns0:currencyExchangeRate>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:currencyExchangeRate"/>
               </ns0:currencyExchangeRate>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentMethodSelect">
               <ns0:paymentMethodSelect>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentMethodSelect"/>
               </ns0:paymentMethodSelect>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addedPaymentMethods">
               <ns0:addedPaymentMethods>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addedPaymentMethods"/>
               </ns0:addedPaymentMethods>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentForm">
               <ns0:paymentForm>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentForm"/>
               </ns0:paymentForm>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentCondition">
               <ns0:paymentCondition>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentCondition"/>
               </ns0:paymentCondition>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentStatus">
               <ns0:paymentStatus>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentStatus"/>
               </ns0:paymentStatus>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentAccountNumber">
               <ns0:paymentAccountNumber>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentAccountNumber"/>
               </ns0:paymentAccountNumber>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:discount">
               <ns0:discount>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:discount"/>
               </ns0:discount>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:comments">
               <ns0:comments>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:comments"/>
               </ns0:comments>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:service">
               <ns0:service>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:service"/>
               </ns0:service>
            </xsl:if>
            <ns0:export>
               <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:export"/>
            </ns0:export>
            <ns0:typeInvoice>
               <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:typeInvoice"/>
            </ns0:typeInvoice>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:documentTypeDescription">
               <ns0:documentTypeDescription>
                  <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:documentTypeDescription"/>
               </ns0:documentTypeDescription>
            </xsl:if>
            <xsl:for-each select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:invoiceItems">
               <ns0:invoiceItems>
                  <xsl:if test="ns0:description">
                     <ns0:description>
                        <xsl:value-of select="ns0:description"/>
                     </ns0:description>
                  </xsl:if>
                  <xsl:if test="ns0:productServiceKey">
                     <ns0:productServiceKey>
                        <xsl:value-of select="ns0:productServiceKey"/>
                     </ns0:productServiceKey>
                  </xsl:if>
                  <xsl:if test="ns0:productServDescription">
                     <ns0:productServDescription>
                        <xsl:value-of select="ns0:productServDescription"/>
                     </ns0:productServDescription>
                  </xsl:if>
                  <xsl:if test="ns0:quantity">
                     <ns0:quantity>
                        <xsl:value-of select="ns0:quantity"/>
                     </ns0:quantity>
                  </xsl:if>
                  <xsl:if test="ns0:discount">
                     <ns0:discount>
                        <xsl:value-of select="ns0:discount"/>
                     </ns0:discount>
                  </xsl:if>
                  <xsl:if test="ns0:vatPercentage">
                     <ns0:vatPercentage>
                        <xsl:value-of select="ns0:vatPercentage"/>
                     </ns0:vatPercentage>
                  </xsl:if>
                  <xsl:if test="ns0:unit">
                     <ns0:unit>
                        <xsl:value-of select="ns0:unit"/>
                     </ns0:unit>
                  </xsl:if>
                  <xsl:if test="ns0:unitKey">
                     <ns0:unitKey>
                        <xsl:value-of select="ns0:unitKey"/>
                     </ns0:unitKey>
                  </xsl:if>
                  <xsl:if test="ns0:unitPrice">
                     <ns0:unitPrice>
                        <xsl:value-of select="ns0:unitPrice"/>
                     </ns0:unitPrice>
                  </xsl:if>
                  <xsl:if test="ns0:taxBase">
                     <ns0:taxBase>
                        <xsl:value-of select="ns0:taxBase"/>
                     </ns0:taxBase>
                  </xsl:if>
                  <xsl:if test="ns0:tax">
                     <ns0:tax>
                        <xsl:value-of select="ns0:tax"/>
                     </ns0:tax>
                  </xsl:if>
                  <xsl:if test="ns0:factorType">
                     <ns0:factorType>
                        <xsl:value-of select="ns0:factorType"/>
                     </ns0:factorType>
                  </xsl:if>
                  <xsl:if test="ns0:rateFee">
                     <ns0:rateFee>
                        <xsl:value-of select="ns0:rateFee"/>
                     </ns0:rateFee>
                  </xsl:if>
                  <xsl:if test="ns0:stpsPercentage">
                     <ns0:stpsPercentage>
                        <xsl:value-of select="ns0:stpsPercentage"/>
                     </ns0:stpsPercentage>
                  </xsl:if>
                  <xsl:if test="ns0:impPercentage">
                     <ns0:impPercentage>
                        <xsl:value-of select="ns0:impPercentage"/>
                     </ns0:impPercentage>
                  </xsl:if>
                  <xsl:if test="ns0:retentionVatPercentage">
                     <ns0:retentionVatPercentage>
                        <xsl:value-of select="ns0:retentionVatPercentage"/>
                     </ns0:retentionVatPercentage>
                  </xsl:if>
                  <xsl:if test="ns0:retentionRatePercentage">
                     <ns0:retentionRatePercentage>
                        <xsl:value-of select="ns0:retentionRatePercentage"/>
                     </ns0:retentionRatePercentage>
                  </xsl:if>
                  <xsl:if test="ns0:amount">
                     <ns0:amount>
                        <xsl:value-of select="ns0:amount"/>
                     </ns0:amount>
                  </xsl:if>
                  <xsl:if test="ns0:subtotal">
                     <ns0:subtotal>
                        <xsl:value-of select="ns0:subtotal"/>
                     </ns0:subtotal>
                  </xsl:if>
                  <xsl:if test="ns0:vat">
                     <ns0:vat>
                        <xsl:value-of select="ns0:vat"/>
                     </ns0:vat>
                  </xsl:if>
                  <xsl:if test="ns0:stps">
                     <ns0:stps>
                        <xsl:value-of select="ns0:stps"/>
                     </ns0:stps>
                  </xsl:if>
                  <xsl:if test="ns0:imp">
                     <ns0:imp>
                        <xsl:value-of select="ns0:imp"/>
                     </ns0:imp>
                  </xsl:if>
                  <xsl:if test="ns0:identificationNumber">
                        <ns0:identificationNumber>
                           <xsl:value-of select="ns0:identificationNumber"/>
                        </ns0:identificationNumber>
                     </xsl:if>
                  <xsl:if test="ns0:retentionVat">
                     <ns0:retentionVat>
                        <xsl:value-of select="ns0:retentionVat"/>
                     </ns0:retentionVat>
                  </xsl:if>
                  <xsl:if test="ns0:retentionRate">
                     <ns0:retentionRate>
                        <xsl:value-of select="ns0:retentionRate"/>
                     </ns0:retentionRate>
                  </xsl:if>
                  <xsl:if test="ns0:total">
                     <ns0:total>
                        <xsl:value-of select="ns0:total"/>
                     </ns0:total>
                  </xsl:if>
                  <xsl:if test="ns0:st">
                     <ns0:st>
                        <xsl:value-of select="ns0:st"/>
                     </ns0:st>
                  </xsl:if>
                  <xsl:if test="ns0:propertyAccount">
                     <xsl:for-each select="ns0:propertyAccount"> <ns0:propertyAccount>
                           <xsl:value-of select="."/>
                        </ns0:propertyAccount>
                     </xsl:for-each>
                  </xsl:if>
                 
                  <xsl:if test="ns0:taxObject">
                     <ns0:taxObject>
                        <xsl:value-of select="ns0:taxObject"/>
                     </ns0:taxObject>
                  </xsl:if>
                  <xsl:if test="ns0:addendumInterfaceApply">
                     <ns0:addendumInterfaceApply>
                        <xsl:value-of select="ns0:addendumInterfaceApply"/>
                     </ns0:addendumInterfaceApply>
                  </xsl:if>
                  <xsl:if test="ns0:addendumInterfaceType">
                     <ns0:addendumInterfaceType>
                        <xsl:value-of select="ns0:addendumInterfaceType"/>
                     </ns0:addendumInterfaceType>
                  </xsl:if>
                  <xsl:if test="ns0:addendumInterfaceConcept">
                     <ns0:addendumInterfaceConcept>
                        <xsl:value-of select="ns0:addendumInterfaceConcept"/>
                     </ns0:addendumInterfaceConcept>
                  </xsl:if>
               </ns0:invoiceItems>
            </xsl:for-each>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:globalInformation">
               <ns0:globalInformation>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:globalInformation/ns0:periodicity">
                     <ns0:periodicity>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:globalInformation/ns0:periodicity"/>
                     </ns0:periodicity>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:globalInformation/ns0:months">
                     <ns0:months>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:globalInformation/ns0:months"/>
                     </ns0:months>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:globalInformation/ns0:year">
                     <ns0:year>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:globalInformation/ns0:year"/>
                     </ns0:year>
                  </xsl:if>
               </ns0:globalInformation>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:relatedCfdi/ns0:relationshipType">
            <xsl:for-each select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:relatedCfdi">
               <ns0:relatedCfdi>
                  <xsl:if test="ns0:relationshipType">
                     <ns0:relationshipType>
                        <xsl:value-of select="ns0:relationshipType"/>
                     </ns0:relationshipType>
                  </xsl:if>
                  <xsl:for-each select="ns0:uuids">
                     <ns0:uuids>
                           <xsl:value-of select="."/>
                        </ns0:uuids>
                  </xsl:for-each>
               </ns0:relatedCfdi>
            </xsl:for-each>
            </xsl:if>
            <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement">
               <ns0:paymentComplement>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalPaymentsAmount">
                     <ns0:totalPaymentsAmount>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalPaymentsAmount"/>
                     </ns0:totalPaymentsAmount>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalRetentionIEPS">
                     <ns0:totalRetentionIEPS>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalRetentionIEPS"/>
                     </ns0:totalRetentionIEPS>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalRetentionISR">
                     <ns0:totalRetentionISR>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalRetentionISR"/>
                     </ns0:totalRetentionISR>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalRetentionVat">
                     <ns0:totalRetentionVat>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalRetentionVat"/>
                     </ns0:totalRetentionVat>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxBaseVat0">
                     <ns0:totalTaxBaseVat0>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxBaseVat0"/>
                     </ns0:totalTaxBaseVat0>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxBaseVat16">
                     <ns0:totalTaxBaseVat16>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxBaseVat16"/>
                     </ns0:totalTaxBaseVat16>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxBaseVat8">
                     <ns0:totalTaxBaseVat8>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxBaseVat8"/>
                     </ns0:totalTaxBaseVat8>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxBaseVatExento">
                     <ns0:totalTaxBaseVatExento>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxBaseVatExento"/>
                     </ns0:totalTaxBaseVatExento>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxVat0">
                     <ns0:totalTaxVat0>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxVat0"/>
                     </ns0:totalTaxVat0>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxVat16">
                     <ns0:totalTaxVat16>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxVat16"/>
                     </ns0:totalTaxVat16>
                  </xsl:if>
                  <xsl:if test="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxVat8">
                     <ns0:totalTaxVat8>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:totalTaxVat8"/>
                     </ns0:totalTaxVat8>
                  </xsl:if>
                  <xsl:for-each select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:paymentComplement/ns0:payments">
                     <ns0:payments>
                        <xsl:if test="ns0:paymentDate">
                           <ns0:paymentDate>
                              <xsl:value-of select="ns0:paymentDate"/>
                           </ns0:paymentDate>
                        </xsl:if>
                        <xsl:if test="ns0:paymentWay">
                           <ns0:paymentWay>
                              <xsl:value-of select="ns0:paymentWay"/>
                           </ns0:paymentWay>
                        </xsl:if>
                        <xsl:if test="ns0:currency">
                           <ns0:currency>
                              <xsl:value-of select="ns0:currency"/>
                           </ns0:currency>
                        </xsl:if>
                        <xsl:if test="ns0:currencyExchange">
                           <ns0:currencyExchange>
                              <xsl:value-of select="ns0:currencyExchange"/>
                           </ns0:currencyExchange>
                        </xsl:if>
                        <xsl:if test="ns0:amount">
                           <ns0:amount>
                              <xsl:value-of select="ns0:amount"/>
                           </ns0:amount>
                        </xsl:if>
                        <xsl:if test="ns0:operationNumber">
                           <ns0:operationNumber>
                              <xsl:value-of select="ns0:operationNumber"/>
                           </ns0:operationNumber>
                        </xsl:if>
                        <xsl:if test="ns0:ordAccIusserRfc">
                           <ns0:ordAccIusserRfc>
                              <xsl:value-of select="ns0:ordAccIusserRfc"/>
                           </ns0:ordAccIusserRfc>
                        </xsl:if>
                        <xsl:if test="ns0:bankName">
                           <ns0:bankName>
                              <xsl:value-of select="ns0:bankName"/>
                           </ns0:bankName>
                        </xsl:if>
                        <xsl:if test="ns0:payerAccount">
                           <ns0:payerAccount>
                              <xsl:value-of select="ns0:payerAccount"/>
                           </ns0:payerAccount>
                        </xsl:if>
                        <xsl:if test="ns0:benAccIssuerRfc">
                           <ns0:benAccIssuerRfc>
                              <xsl:value-of select="ns0:benAccIssuerRfc"/>
                           </ns0:benAccIssuerRfc>
                        </xsl:if>
                        <xsl:if test="ns0:beneficiaryAccount">
                           <ns0:beneficiaryAccount>
                              <xsl:value-of select="ns0:beneficiaryAccount"/>
                           </ns0:beneficiaryAccount>
                        </xsl:if>
                        <xsl:if test="ns0:paymentStringType">
                           <ns0:paymentStringType>
                              <xsl:value-of select="ns0:paymentStringType"/>
                           </ns0:paymentStringType>
                        </xsl:if>
                        <xsl:if test="ns0:paymentCert">
                           <ns0:paymentCert>
                              <xsl:value-of select="ns0:paymentCert"/>
                           </ns0:paymentCert>
                        </xsl:if>
                        <xsl:if test="ns0:paymentString">
                           <ns0:paymentString>
                              <xsl:value-of select="ns0:paymentString"/>
                           </ns0:paymentString>
                        </xsl:if>
                        <xsl:if test="ns0:paymentSeal">
                           <ns0:paymentSeal>
                              <xsl:value-of select="ns0:paymentSeal"/>
                           </ns0:paymentSeal>
                        </xsl:if>
                        <xsl:if test="ns0:version">
                           <ns0:version>
                              <xsl:value-of select="ns0:version"/>
                           </ns0:version>
                        </xsl:if>
                        <xsl:for-each select="ns0:retainedTaxes">
                           <ns0:retainedTaxes>
                              <xsl:if test="ns0:amount">
                                 <ns0:amount>
                                    <xsl:value-of select="ns0:amount"/>
                                 </ns0:amount>
                              </xsl:if>
                              <xsl:if test="ns0:factorType">
                                 <ns0:factorType>
                                    <xsl:value-of select="ns0:factorType"/>
                                 </ns0:factorType>
                              </xsl:if>
                              <xsl:if test="ns0:rateFee">
                                 <ns0:rateFee>
                                    <xsl:value-of select="ns0:rateFee"/>
                                 </ns0:rateFee>
                              </xsl:if>
                              <xsl:if test="ns0:tax">
                                 <ns0:tax>
                                    <xsl:value-of select="ns0:tax"/>
                                 </ns0:tax>
                              </xsl:if>
                              <xsl:if test="ns0:taxBase">
                                 <ns0:taxBase>
                                    <xsl:value-of select="ns0:taxBase"/>
                                 </ns0:taxBase>
                              </xsl:if>
                           </ns0:retainedTaxes>
                        </xsl:for-each>
                        <xsl:for-each select="ns0:transferredsTaxes">
                           <ns0:transferredsTaxes>
                              <xsl:if test="ns0:amount">
                                 <ns0:amount>
                                    <xsl:value-of select="ns0:amount"/>
                                 </ns0:amount>
                              </xsl:if>
                              <xsl:if test="ns0:factorType">
                                 <ns0:factorType>
                                    <xsl:value-of select="ns0:factorType"/>
                                 </ns0:factorType>
                              </xsl:if>
                              <xsl:if test="ns0:rateFee">
                                 <ns0:rateFee>
                                    <xsl:value-of select="ns0:rateFee"/>
                                 </ns0:rateFee>
                              </xsl:if>
                              <xsl:if test="ns0:tax">
                                 <ns0:tax>
                                    <xsl:value-of select="ns0:tax"/>
                                 </ns0:tax>
                              </xsl:if>
                              <xsl:if test="ns0:taxBase">
                                 <ns0:taxBase>
                                    <xsl:value-of select="ns0:taxBase"/>
                                 </ns0:taxBase>
                              </xsl:if>
                           </ns0:transferredsTaxes>
                        </xsl:for-each>
                        <xsl:for-each select="ns0:relatedDocuments">
                           <ns0:relatedDocuments>
                              <xsl:if test="ns0:documentId">
                                 <ns0:documentId>
                                    <xsl:value-of select="ns0:documentId"/>
                                 </ns0:documentId>
                              </xsl:if>
                              <xsl:if test="ns0:serie">
                                 <ns0:serie>
                                    <xsl:value-of select="ns0:serie"/>
                                 </ns0:serie>
                              </xsl:if>
                              <xsl:if test="ns0:folio">
                                 <ns0:folio>
                                    <xsl:value-of select="ns0:folio"/>
                                 </ns0:folio>
                              </xsl:if>
                              <xsl:if test="ns0:currency">
                                 <ns0:currency>
                                    <xsl:value-of select="ns0:currency"/>
                                 </ns0:currency>
                              </xsl:if>
                              <xsl:if test="ns0:currencyExchange">
                                 <ns0:currencyExchange>
                                    <xsl:value-of select="ns0:currencyExchange"/>
                                 </ns0:currencyExchange>
                              </xsl:if>
                              <xsl:if test="ns0:paymentMethod">
                                 <ns0:paymentMethod>
                                    <xsl:value-of select="ns0:paymentMethod"/>
                                 </ns0:paymentMethod>
                              </xsl:if>
                              <xsl:if test="ns0:partialityNumber">
                                 <ns0:partialityNumber>
                                    <xsl:value-of select="ns0:partialityNumber"/>
                                 </ns0:partialityNumber>
                              </xsl:if>
                              <xsl:if test="ns0:previousBalance">
                                 <ns0:previousBalance>
                                    <xsl:value-of select="ns0:previousBalance"/>
                                 </ns0:previousBalance>
                              </xsl:if>
                              <xsl:if test="ns0:paidAmount">
                                 <ns0:paidAmount>
                                    <xsl:value-of select="ns0:paidAmount"/>
                                 </ns0:paidAmount>
                              </xsl:if>
                              <xsl:if test="ns0:outstandingBalance">
                                 <ns0:outstandingBalance>
                                    <xsl:value-of select="ns0:outstandingBalance"/>
                                 </ns0:outstandingBalance>
                              </xsl:if>
                              <ns0:taxObject>
                                 <xsl:value-of select="ns0:taxObject"/>
                              </ns0:taxObject>
                              <xsl:for-each select="ns0:retainedTaxes">
                                 <ns0:retainedTaxes>
                                    <xsl:if test="ns0:amount">
                                       <ns0:amount>
                                          <xsl:value-of select="ns0:amount"/>
                                       </ns0:amount>
                                    </xsl:if>
                                    <xsl:if test="ns0:factorType">
                                       <ns0:factorType>
                                          <xsl:value-of select="ns0:factorType"/>
                                       </ns0:factorType>
                                    </xsl:if>
                                    <xsl:if test="ns0:rateFee">
                                       <ns0:rateFee>
                                          <xsl:value-of select="ns0:rateFee"/>
                                       </ns0:rateFee>
                                    </xsl:if>
                                    <xsl:if test="ns0:tax">
                                       <ns0:tax>
                                          <xsl:value-of select="ns0:tax"/>
                                       </ns0:tax>
                                    </xsl:if>
                                    <xsl:if test="ns0:taxBase">
                                       <ns0:taxBase>
                                          <xsl:value-of select="ns0:taxBase"/>
                                       </ns0:taxBase>
                                    </xsl:if>
                                 </ns0:retainedTaxes>
                              </xsl:for-each>
                              <xsl:for-each select="ns0:transferredsTaxes">
                                 <ns0:transferredsTaxes>
                                    <xsl:if test="ns0:amount">
                                       <ns0:amount>
                                          <xsl:value-of select="ns0:amount"/>
                                       </ns0:amount>
                                    </xsl:if>
                                    <xsl:if test="ns0:factorType">
                                       <ns0:factorType>
                                          <xsl:value-of select="ns0:factorType"/>
                                       </ns0:factorType>
                                    </xsl:if>
                                    <xsl:if test="ns0:rateFee">
                                       <ns0:rateFee>
                                          <xsl:value-of select="ns0:rateFee"/>
                                       </ns0:rateFee>
                                    </xsl:if>
                                    <xsl:if test="ns0:tax">
                                       <ns0:tax>
                                          <xsl:value-of select="ns0:tax"/>
                                       </ns0:tax>
                                    </xsl:if>
                                    <xsl:if test="ns0:taxBase">
                                       <ns0:taxBase>
                                          <xsl:value-of select="ns0:taxBase"/>
                                       </ns0:taxBase>
                                    </xsl:if>
                                 </ns0:transferredsTaxes>
                              </xsl:for-each>
                           </ns0:relatedDocuments>
                        </xsl:for-each>
                     </ns0:payments>
                  </xsl:for-each>
               </ns0:paymentComplement>
            </xsl:if>
            <xsl:if test="count (/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaAdo ) > 0 or count (/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW ) > 0">
               <ns0:addendas>
                  <ns0:psv_vw>
                     <ns0:cancelaciones>
                        <ns0:cancelaSustituye>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:cancelaciones/ns0:cancelaSustituye"/>
                        </ns0:cancelaSustituye>
                     </ns0:cancelaciones>
                     <ns0:moneda>
                        <ns0:tipoMoneda>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:moneda/ns0:tipoMoneda"/>
                        </ns0:tipoMoneda>
                        <ns0:tipoCambio>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:moneda/ns0:tipoCambio"/>
                        </ns0:tipoCambio>
                        <ns0:codigoImpuesto>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:moneda/ns0:codigoImpuesto"/>
                        </ns0:codigoImpuesto>
                     </ns0:moneda>
                     <ns0:proveedor>
                        <ns0:codigo>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:proveedor/ns0:codigo"/>
                        </ns0:codigo>
                        <ns0:nombre>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:proveedor/ns0:nombre"/>
                        </ns0:nombre>
                        <ns0:correoContacto>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:proveedor/ns0:correoContacto"/>
                        </ns0:correoContacto>
                     </ns0:proveedor>
                     <ns0:origen>
                        <ns0:codigo>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:origen/ns0:codigo"/>
                        </ns0:codigo>
                        <ns0:nombre>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:origen/ns0:nombre"/>
                        </ns0:nombre>
                     </ns0:origen>
                     <ns0:destino>
                        <ns0:codigo>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:destino/ns0:codigo"/>
                        </ns0:codigo>
                        <ns0:naveReciboMaterial>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:destino/ns0:naveReciboMaterial"/>
                        </ns0:naveReciboMaterial>
                     </ns0:destino>
                     <ns0:medidas>
                        <ns0:pesoBruto>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:medidas/ns0:pesoBruto"/>
                        </ns0:pesoBruto>
                        <ns0:pesoNeto>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:medidas/ns0:pesoNeto"/>
                        </ns0:pesoNeto>
                        <ns0:volumen>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:medidas/ns0:volumen"/>
                        </ns0:volumen>
                        <ns0:numeroPiezas>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:medidas/ns0:numeroPiezas"/>
                        </ns0:numeroPiezas>
                        <ns0:descripcion>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:medidas/ns0:descripcion"/>
                        </ns0:descripcion>
                     </ns0:medidas>
                     <ns0:referencias>
                        <ns0:referenciaProveedor>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:referencias/ns0:referenciaProveedor"/>
                        </ns0:referenciaProveedor>
                        <ns0:remision>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:referencias/ns0:remision"/>
                        </ns0:remision>
                        <ns0:numeroASN>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:referencias/ns0:numeroASN"/>
                        </ns0:numeroASN>
                        <ns0:unidadNegocios>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:referencias/ns0:unidadNegocios"/>
                        </ns0:unidadNegocios>
                     </ns0:referencias>
                     <ns0:solicitante>
                        <ns0:nombre>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:solicitante/ns0:nombre"/>
                        </ns0:nombre>
                        <ns0:correo>
                           <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:solicitante/ns0:correo"/>
                        </ns0:correo>
                     </ns0:solicitante>
                     <xsl:for-each select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:notas">
                        <ns0:notas>
                           <ns0:nota>
                              <xsl:value-of select="ns0:nota"/>
                           </ns0:nota>
                        </ns0:notas>
                     </xsl:for-each>
                     <xsl:for-each select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:archivo">
                        <ns0:archivo>
                           <ns0:datos>
                              <xsl:value-of select="ns0:datos"/>
                           </ns0:datos>
                           <ns0:tipo>
                              <xsl:value-of select="ns0:tipo"/>
                           </ns0:tipo>
                        </ns0:archivo>
                     </xsl:for-each>
                     <xsl:for-each select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:partes">
                        <ns0:partes>
                           <ns0:referencias>
                              <ns0:ordenCompra>
                                 <xsl:value-of select="ns0:referencias/ns0:ordenCompra"/>
                              </ns0:ordenCompra>
                           </ns0:referencias>
                           <xsl:for-each select="ns0:notas">
                              <ns0:notas>
                                 <ns0:nota>
                                    <xsl:value-of select="ns0:nota"/>
                                 </ns0:nota>
                              </ns0:notas>
                           </xsl:for-each>
                           <ns0:posicion>
                              <xsl:value-of select="ns0:posicion"/>
                           </ns0:posicion>
                           <ns0:numeroMaterial>
                              <xsl:value-of select="ns0:numeroMaterial"/>
                           </ns0:numeroMaterial>
                           <ns0:descripcionMaterial>
                              <xsl:value-of select="ns0:descripcionMaterial"/>
                           </ns0:descripcionMaterial>
                           <ns0:cantidadMaterial>
                              <xsl:value-of select="ns0:cantidadMaterial"/>
                           </ns0:cantidadMaterial>
                           <ns0:unidadMedida>
                              <xsl:value-of select="ns0:unidadMedida"/>
                           </ns0:unidadMedida>
                           <ns0:precioUnitario>
                              <xsl:value-of select="ns0:precioUnitario"/>
                           </ns0:precioUnitario>
                           <ns0:montoLinea>
                              <xsl:value-of select="ns0:montoLinea"/>
                           </ns0:montoLinea>
                           <ns0:pesoBruto>
                              <xsl:value-of select="ns0:pesoBruto"/>
                           </ns0:pesoBruto>
                           <ns0:pesoNeto>
                              <xsl:value-of select="ns0:pesoNeto"/>
                           </ns0:pesoNeto>
                           <ns0:codigoImpuesto>
                              <xsl:value-of select="ns0:codigoImpuesto"/>
                           </ns0:codigoImpuesto>
                        </ns0:partes>
                     </xsl:for-each>
                     <ns0:version>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:version"/>
                     </ns0:version>
                     <ns0:tipoDocumentoFiscal>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:tipoDocumentoFiscal"/>
                     </ns0:tipoDocumentoFiscal>
                     <ns0:tipoDocumentoVWM>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:tipoDocumentoVWM"/>
                     </ns0:tipoDocumentoVWM>
                     <ns0:division>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaVW/ns0:psv_vw/ns0:division"/>
                     </ns0:division>
                  </ns0:psv_vw>
                  <ns0:grupoAdo>
                     <ns0:tipoAddenda>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaAdo/ns0:grupo_ado/ns0:tipoAddenda"/>
                     </ns0:tipoAddenda>
                     <ns0:valor>
                        <xsl:value-of select="/ns0:createTrxCFDIRq/ns0:invoice/ns0:addendaAdo/ns0:grupo_ado/ns0:valor"/>
                     </ns0:valor>
                  </ns0:grupoAdo>
               </ns0:addendas>
            </xsl:if>
         </ns0:invoice>
      </ns0:invoice>
   </xsl:template>
</xsl:stylesheet>