<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbGetValPaymentComplementsResume" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/AuditControlTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetValPaymentComplementsResumeRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/External/dbGetValPaymentComplementsResume_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="dbGetValPaymentComplementsResumeSelect_pComplementUuid_pComplementRfcIssuer_pComplementRfcReceiver_pStatus_pStartDate_pEndDateInputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbGetValPaymentComplementsResume"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED JAN 10 17:51:24 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:dbGetValPaymentComplementsResumeSelect_pComplementUuid_pComplementRfcIssuer_pComplementRfcReceiver_pStatus_pStartDate_pEndDateInputParameters>
         <xsl:if test="/ns0:GetValPaymentComplementsResumeRq/ns0:Uuid">
            <tns:pComplementUuid>
               <xsl:value-of select="/ns0:GetValPaymentComplementsResumeRq/ns0:Uuid"/>
            </tns:pComplementUuid>
         </xsl:if>
         <xsl:if test="/ns0:GetValPaymentComplementsResumeRq/ns0:RfcIssuer">
            <tns:pComplementRfcIssuer>
               <xsl:value-of select="/ns0:GetValPaymentComplementsResumeRq/ns0:RfcIssuer"/>
            </tns:pComplementRfcIssuer>
         </xsl:if>
         <xsl:if test="/ns0:GetValPaymentComplementsResumeRq/ns0:RfcReceiver">
            <tns:pComplementRfcReceiver>
               <xsl:value-of select="/ns0:GetValPaymentComplementsResumeRq/ns0:RfcReceiver"/>
            </tns:pComplementRfcReceiver>
         </xsl:if>
         <xsl:if test="/ns0:GetValPaymentComplementsResumeRq/ns0:Status">
            <tns:pStatus>
               <xsl:value-of select="/ns0:GetValPaymentComplementsResumeRq/ns0:Status"/>
            </tns:pStatus>
         </xsl:if>
         <xsl:if test="/ns0:GetValPaymentComplementsResumeRq/ns0:StartDate">
            <tns:pStartDate>
               <xsl:value-of select="/ns0:GetValPaymentComplementsResumeRq/ns0:StartDate"/>
            </tns:pStartDate>
         </xsl:if>
         <xsl:if test="/ns0:GetValPaymentComplementsResumeRq/ns0:EndDate">
            <tns:pEndDate>
               <xsl:value-of select="/ns0:GetValPaymentComplementsResumeRq/ns0:EndDate"/>
            </tns:pEndDate>
         </xsl:if>
      </tns:dbGetValPaymentComplementsResumeSelect_pComplementUuid_pComplementRfcIssuer_pComplementRfcReceiver_pStatus_pStartDate_pEndDateInputParameters>
   </xsl:template>
</xsl:stylesheet>