<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/dbaReadInventoryTransactions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://soa.estrellaroja.com.mx/FinancialsTec" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/dbaReadInventoryTransactions.xsd"/>
            <oracle-xsl-mapper:rootElement name="dbaReadInventoryTransactionsOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbaReadInventoryTransactions"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/FinancialsTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetInventoryTransactionsRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON DEC 11 17:14:27 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetInventoryTransactionsRs>
         <cmn:Success/>
         <tns:Return>
            <xsl:for-each select="/ns0:dbaReadInventoryTransactionsOutputCollection/ns0:dbaReadInventoryTransactionsOutput">
               <tns:InventoryTransaction>
                  <tns:OrganizationName>
                     <xsl:if test="ns0:OrganizationName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:OrganizationName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:OrganizationName"/>
                  </tns:OrganizationName>
                  <tns:TransactionDate>
                     <xsl:if test="ns0:TransactionDate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionDate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionDate"/>
                  </tns:TransactionDate>
                  <tns:TransactionTypeName>
                     <xsl:if test="ns0:TransactionTypeName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionTypeName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionTypeName"/>
                  </tns:TransactionTypeName>
                  <tns:SourceCode>
                     <xsl:if test="ns0:SourceCode/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SourceCode/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SourceCode"/>
                  </tns:SourceCode>
                  <tns:SourceHeaderId>
                     <xsl:if test="ns0:SourceHeaderId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SourceHeaderId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SourceHeaderId"/>
                  </tns:SourceHeaderId>
                  <tns:SourceLineId>
                     <xsl:if test="ns0:SourceLineId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SourceLineId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SourceLineId"/>
                  </tns:SourceLineId>
                  <tns:TransactionSourceName>
                     <xsl:if test="ns0:TransactionSourceName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionSourceName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionSourceName"/>
                  </tns:TransactionSourceName>
                  <tns:DspSegment1>
                     <xsl:if test="ns0:DspSegment1/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:DspSegment1/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:DspSegment1"/>
                  </tns:DspSegment1>
                  <tns:DspSegment2>
                     <xsl:if test="ns0:DspSegment2/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:DspSegment2/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:DspSegment2"/>
                  </tns:DspSegment2>
                  <tns:DspSegment3>
                     <xsl:if test="ns0:DspSegment3/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:DspSegment3/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:DspSegment3"/>
                  </tns:DspSegment3>
                  <tns:DspSegment4>
                     <xsl:if test="ns0:DspSegment4/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:DspSegment4/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:DspSegment4"/>
                  </tns:DspSegment4>
                  <tns:DspSegment5>
                     <xsl:if test="ns0:DspSegment5/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:DspSegment5/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:DspSegment5"/>
                  </tns:DspSegment5>
                  <tns:DspSegment6>
                     <xsl:if test="ns0:DspSegment6/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:DspSegment6/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:DspSegment6"/>
                  </tns:DspSegment6>
                  <tns:DspSegment7>
                     <xsl:if test="ns0:DspSegment7/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:DspSegment7/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:DspSegment7"/>
                  </tns:DspSegment7>
                  <tns:DspSegment8>
                     <xsl:if test="ns0:DspSegment8/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:DspSegment8/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:DspSegment8"/>
                  </tns:DspSegment8>
                  <tns:ProcessFlag>
                     <xsl:if test="ns0:ProcessFlag/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ProcessFlag/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ProcessFlag"/>
                  </tns:ProcessFlag>
                  <tns:ItemNumber>
                     <xsl:if test="ns0:ItemNumber/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ItemNumber/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ItemNumber"/>
                  </tns:ItemNumber>
                  <tns:SubinvetoryCode>
                     <xsl:if test="ns0:SubinvetoryCode/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SubinvetoryCode/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SubinvetoryCode"/>
                  </tns:SubinvetoryCode>
                  <tns:LocatorName>
                     <xsl:if test="ns0:LocatorName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:LocatorName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:LocatorName"/>
                  </tns:LocatorName>
                  <tns:TransactionQuantity>
                     <xsl:if test="ns0:TransactionQuantity/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionQuantity/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionQuantity"/>
                  </tns:TransactionQuantity>
                  <tns:TransactionUom>
                     <xsl:if test="ns0:TransactionUom/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionUom/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionUom"/>
                  </tns:TransactionUom>
                  <tns:TransactionUnitOfMeasure>
                     <xsl:if test="ns0:TransactionUnitOfMeasure/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionUnitOfMeasure/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionUnitOfMeasure"/>
                  </tns:TransactionUnitOfMeasure>
                  <tns:TransactionSourceTypeName>
                     <xsl:if test="ns0:TransactionSourceTypeName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionSourceTypeName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionSourceTypeName"/>
                  </tns:TransactionSourceTypeName>
                  <tns:TransactionMode>
                     <xsl:if test="ns0:TransactionMode/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionMode/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionMode"/>
                  </tns:TransactionMode>
                  <tns:Attribute1>
                     <xsl:if test="ns0:Attribute1/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Attribute1/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Attribute1"/>
                  </tns:Attribute1>
                  <tns:Attribute2>
                     <xsl:if test="ns0:Attribute2/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Attribute2/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Attribute2"/>
                  </tns:Attribute2>
                  <tns:Attribute3>
                     <xsl:if test="ns0:Attribute3/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Attribute3/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Attribute3"/>
                  </tns:Attribute3>
                  <tns:Attribute4>
                     <xsl:if test="ns0:Attribute4/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Attribute4/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Attribute4"/>
                  </tns:Attribute4>
                  <tns:Attribute5>
                     <xsl:if test="ns0:Attribute5/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Attribute5/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Attribute5"/>
                  </tns:Attribute5>
                  <tns:Attribute6>
                     <xsl:if test="ns0:Attribute6/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Attribute6/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Attribute6"/>
                  </tns:Attribute6>
                  <tns:Attribute7>
                     <xsl:if test="ns0:Attribute7/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Attribute7/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Attribute7"/>
                  </tns:Attribute7>
                  <tns:Attribute8>
                     <xsl:if test="ns0:Attribute8/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Attribute8/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Attribute8"/>
                  </tns:Attribute8>
                  <tns:Attribute9>
                     <xsl:if test="ns0:Attribute9/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Attribute9/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Attribute9"/>
                  </tns:Attribute9>
                  <tns:Attribute10>
                     <xsl:if test="ns0:Attribute10/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Attribute10/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Attribute10"/>
                  </tns:Attribute10>
               </tns:InventoryTransaction>
            </xsl:for-each>
         </tns:Return>
      </tns:GetInventoryTransactionsRs>
   </xsl:template>
</xsl:stylesheet>