<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefFindCustomerAccount/types" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns5="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountContact/" xmlns:ns6="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountContactRole/" xmlns:ns1="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns7="http://xmlns.oracle.com/adf/svc/types/" xmlns:sdoJava="commonj.sdo/java" xmlns:ns8="http://xmlns.oracle.com/apps/cdm/foundation/parties/customerAccountService/" xmlns:ns10="http://xmlns.oracle.com/apps/cdm/foundation/parties/partyService/" xmlns:ns12="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountSiteUse/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountRel/" xmlns:ns4="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccount/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns9="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/sourceSystemRef/" xmlns:ns11="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountSite/" xmlns:types="http://xmlns.oracle.com/apps/cdm/foundation/parties/customerAccountService/applicationModule/types/" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefFindCustomerAccount">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="FindCustomerAccountRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../../WSDL/Externals/Cloud/Customers/erpRefFindCustomerAccount.wsdl"/>
            <oracle-xsl-mapper:rootElement name="findCustomerAccount" namespace="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefFindCustomerAccount/types"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 07 23:17:15 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:findCustomerAccount>
      <tns:findCriteria>
            <ns7:fetchStart>
               <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:fetchStart"/>
            </ns7:fetchStart>
            <ns7:fetchSize>
               <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:fetchSize"/>
            </ns7:fetchSize>
            <xsl:if test="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:filter">
               <ns7:filter>
                  <xsl:if test="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:filter/ns0:conjunction">
                     <ns7:conjunction>
                        <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:filter/ns0:conjunction"/>
                     </ns7:conjunction>
                  </xsl:if>
                  <xsl:for-each select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:filter/ns0:group">
                     <ns7:group>
                        <xsl:if test="ns0:conjunction">
                           <ns7:conjunction>
                              <xsl:value-of select="ns0:conjunction"/>
                           </ns7:conjunction>
                        </xsl:if>
                        <ns7:upperCaseCompare>
                           <xsl:value-of select="ns0:upperCaseCompare"/>
                        </ns7:upperCaseCompare>
                        <xsl:for-each select="ns0:item">
                           <ns7:item>
                              <xsl:if test="ns0:conjunction">
                                 <ns7:conjunction>
                                    <xsl:value-of select="ns0:conjunction"/>
                                 </ns7:conjunction>
                              </xsl:if>
                              <ns7:upperCaseCompare>
                                 <xsl:value-of select="ns0:upperCaseCompare"/>
                              </ns7:upperCaseCompare>
                              <ns7:attribute>
                                 <xsl:value-of select="ns0:attribute"/>
                              </ns7:attribute>
                              <ns7:operator>
                                 <xsl:value-of select="ns0:operator"/>
                              </ns7:operator>
                              <xsl:for-each select="ns0:value">
                                 <ns7:value>
                                    <xsl:value-of select="."/>
                                 </ns7:value>
                              </xsl:for-each>
                              <xsl:if test="ns0:nested">
                                 <ns7:nested>
                                    <xsl:if test="ns0:nested/ns0:conjunction">
                                       <ns7:conjunction>
                                          <xsl:value-of select="ns0:nested/ns0:conjunction"/>
                                       </ns7:conjunction>
                                    </xsl:if>
                                    <xsl:for-each select="ns0:nested/ns0:group">
                                       <ns7:group>
                                          <xsl:if test="ns0:conjunction">
                                             <ns7:conjunction>
                                                <xsl:value-of select="ns0:conjunction"/>
                                             </ns7:conjunction>
                                          </xsl:if>
                                          <ns7:upperCaseCompare>
                                             <xsl:value-of select="ns0:upperCaseCompare"/>
                                          </ns7:upperCaseCompare>
                                          <xsl:for-each select="ns0:item">
                                             <ns7:item>
                                                <xsl:if test="ns0:conjunction">
                                                   <ns7:conjunction>
                                                      <xsl:value-of select="ns0:conjunction"/>
                                                   </ns7:conjunction>
                                                </xsl:if>
                                                <ns7:upperCaseCompare>
                                                   <xsl:value-of select="ns0:upperCaseCompare"/>
                                                </ns7:upperCaseCompare>
                                                <ns7:attribute>
                                                   <xsl:value-of select="ns0:attribute"/>
                                                </ns7:attribute>
                                                <ns7:operator>
                                                   <xsl:value-of select="ns0:operator"/>
                                                </ns7:operator>
                                                <xsl:for-each select="ns0:value">
                                                   <ns7:value>
                                                      <xsl:value-of select="."/>
                                                   </ns7:value>
                                                </xsl:for-each>
                                             </ns7:item>
                                          </xsl:for-each>
                                       </ns7:group>
                                    </xsl:for-each>
                                    <xsl:for-each select="ns0:nested/ns0:nested">
                                       <ns7:nested>
                                          <xsl:if test="ns0:conjunction">
                                             <ns7:conjunction>
                                                <xsl:value-of select="ns0:conjunction"/>
                                             </ns7:conjunction>
                                          </xsl:if>
                                          <xsl:for-each select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:filter/ns0:group/ns0:item/ns0:nested/ns0:group/ns0:item/ns0:nested/ns0:group">
                                             <ns7:group>
                                                <xsl:if test="ns0:conjunction">
                                                   <ns7:conjunction>
                                                      <xsl:value-of select="ns0:conjunction"/>
                                                   </ns7:conjunction>
                                                </xsl:if>
                                                <ns7:upperCaseCompare>
                                                   <xsl:value-of select="ns0:upperCaseCompare"/>
                                                </ns7:upperCaseCompare>
                                                <xsl:for-each select="ns0:item">
                                                   <ns7:item>
                                                      <xsl:if test="ns0:conjunction">
                                                         <ns7:conjunction>
                                                            <xsl:value-of select="ns0:conjunction"/>
                                                         </ns7:conjunction>
                                                      </xsl:if>
                                                      <ns7:upperCaseCompare>
                                                         <xsl:value-of select="ns0:upperCaseCompare"/>
                                                      </ns7:upperCaseCompare>
                                                      <ns7:attribute>
                                                         <xsl:value-of select="ns0:attribute"/>
                                                      </ns7:attribute>
                                                      <ns7:operator>
                                                         <xsl:value-of select="ns0:operator"/>
                                                      </ns7:operator>
                                                      <xsl:for-each select="ns0:value">
                                                         <ns7:value>
                                                            <xsl:value-of select="."/>
                                                         </ns7:value>
                                                      </xsl:for-each>
                                                   </ns7:item>
                                                </xsl:for-each>
                                             </ns7:group>
                                          </xsl:for-each>
                                       </ns7:nested>
                                    </xsl:for-each>
                                 </ns7:nested>
                              </xsl:if>
                           </ns7:item>
                        </xsl:for-each>
                     </ns7:group>
                  </xsl:for-each>
                  <xsl:for-each select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:filter/ns0:nested">
                     <ns7:nested>
                        <xsl:if test="ns0:conjunction">
                           <ns7:conjunction>
                              <xsl:value-of select="ns0:conjunction"/>
                           </ns7:conjunction>
                        </xsl:if>
                        <xsl:for-each select="ns0:group">
                           <ns7:group>
                              <xsl:if test="ns0:conjunction">
                                 <ns7:conjunction>
                                    <xsl:value-of select="ns0:conjunction"/>
                                 </ns7:conjunction>
                              </xsl:if>
                              <ns7:upperCaseCompare>
                                 <xsl:value-of select="ns0:upperCaseCompare"/>
                              </ns7:upperCaseCompare>
                              <xsl:for-each select="ns0:item">
                                 <ns7:item>
                                    <xsl:if test="ns0:conjunction">
                                       <ns7:conjunction>
                                          <xsl:value-of select="ns0:conjunction"/>
                                       </ns7:conjunction>
                                    </xsl:if>
                                    <ns7:upperCaseCompare>
                                       <xsl:value-of select="ns0:upperCaseCompare"/>
                                    </ns7:upperCaseCompare>
                                    <ns7:attribute>
                                       <xsl:value-of select="ns0:attribute"/>
                                    </ns7:attribute>
                                    <ns7:operator>
                                       <xsl:value-of select="ns0:operator"/>
                                    </ns7:operator>
                                    <xsl:for-each select="ns0:value">
                                       <ns7:value>
                                          <xsl:value-of select="."/>
                                       </ns7:value>
                                    </xsl:for-each>
                                 </ns7:item>
                              </xsl:for-each>
                           </ns7:group>
                        </xsl:for-each>
                     </ns7:nested>
                  </xsl:for-each>
               </ns7:filter>
            </xsl:if>
            <xsl:if test="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:sortOrder">
               <ns7:sortOrder>
                  <xsl:for-each select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:sortOrder/ns0:sortAttribute">
                     <ns7:sortAttribute>
                        <ns7:name>
                           <xsl:value-of select="ns0:name"/>
                        </ns7:name>
                        <ns7:descending>
                           <xsl:value-of select="ns0:descending"/>
                        </ns7:descending>
                     </ns7:sortAttribute>
                  </xsl:for-each>
               </ns7:sortOrder>
            </xsl:if>
            <xsl:for-each select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:findAttribute">
               <ns7:findAttribute>
                  <xsl:value-of select="."/>
               </ns7:findAttribute>
            </xsl:for-each>
            <ns7:excludeAttribute>
               <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:excludeAttribute"/>
            </ns7:excludeAttribute>
            <xsl:for-each select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria">
               <ns7:childFindCriteria>
                  <ns7:fetchStart>
                     <xsl:value-of select="ns0:fetchStart"/>
                  </ns7:fetchStart>
                  <ns7:fetchSize>
                     <xsl:value-of select="ns0:fetchSize"/>
                  </ns7:fetchSize>
                  <xsl:if test="ns0:filter">
                     <ns7:filter>
                        <xsl:if test="ns0:filter/ns0:conjunction">
                           <ns7:conjunction>
                              <xsl:value-of select="ns0:filter/ns0:conjunction"/>
                           </ns7:conjunction>
                        </xsl:if>
                        <xsl:for-each select="ns0:filter/ns0:group">
                           <ns7:group>
                              <xsl:if test="ns0:conjunction">
                                 <ns7:conjunction>
                                    <xsl:value-of select="ns0:conjunction"/>
                                 </ns7:conjunction>
                              </xsl:if>
                              <ns7:upperCaseCompare>
                                 <xsl:value-of select="ns0:upperCaseCompare"/>
                              </ns7:upperCaseCompare>
                              <xsl:for-each select="ns0:item">
                                 <ns7:item>
                                    <xsl:if test="ns0:conjunction">
                                       <ns7:conjunction>
                                          <xsl:value-of select="ns0:conjunction"/>
                                       </ns7:conjunction>
                                    </xsl:if>
                                    <ns7:upperCaseCompare>
                                       <xsl:value-of select="ns0:upperCaseCompare"/>
                                    </ns7:upperCaseCompare>
                                    <ns7:attribute>
                                       <xsl:value-of select="ns0:attribute"/>
                                    </ns7:attribute>
                                    <ns7:operator>
                                       <xsl:value-of select="ns0:operator"/>
                                    </ns7:operator>
                                    <xsl:for-each select="ns0:value">
                                       <ns7:value>
                                          <xsl:value-of select="."/>
                                       </ns7:value>
                                    </xsl:for-each>
                                    <xsl:if test="ns0:nested">
                                       <ns7:nested>
                                          <xsl:if test="ns0:nested/ns0:conjunction">
                                             <ns7:conjunction>
                                                <xsl:value-of select="ns0:nested/ns0:conjunction"/>
                                             </ns7:conjunction>
                                          </xsl:if>
                                          <xsl:for-each select="ns0:nested/ns0:group">
                                             <ns7:group>
                                                <xsl:if test="ns0:conjunction">
                                                   <ns7:conjunction>
                                                      <xsl:value-of select="ns0:conjunction"/>
                                                   </ns7:conjunction>
                                                </xsl:if>
                                                <ns7:upperCaseCompare>
                                                   <xsl:value-of select="ns0:upperCaseCompare"/>
                                                </ns7:upperCaseCompare>
                                                <xsl:for-each select="ns0:item">
                                                   <ns7:item>
                                                      <xsl:if test="ns0:conjunction">
                                                         <ns7:conjunction>
                                                            <xsl:value-of select="ns0:conjunction"/>
                                                         </ns7:conjunction>
                                                      </xsl:if>
                                                      <ns7:upperCaseCompare>
                                                         <xsl:value-of select="ns0:upperCaseCompare"/>
                                                      </ns7:upperCaseCompare>
                                                      <ns7:attribute>
                                                         <xsl:value-of select="ns0:attribute"/>
                                                      </ns7:attribute>
                                                      <ns7:operator>
                                                         <xsl:value-of select="ns0:operator"/>
                                                      </ns7:operator>
                                                      <xsl:for-each select="ns0:value">
                                                         <ns7:value>
                                                            <xsl:value-of select="."/>
                                                         </ns7:value>
                                                      </xsl:for-each>
                                                   </ns7:item>
                                                </xsl:for-each>
                                             </ns7:group>
                                          </xsl:for-each>
                                          <xsl:for-each select="ns0:nested/ns0:nested">
                                             <ns7:nested>
                                                <xsl:if test="ns0:conjunction">
                                                   <ns7:conjunction>
                                                      <xsl:value-of select="ns0:conjunction"/>
                                                   </ns7:conjunction>
                                                </xsl:if>
                                                <xsl:for-each select="ns0:group">
                                                   <ns7:group>
                                                      <xsl:if test="ns0:conjunction">
                                                         <ns7:conjunction>
                                                            <xsl:value-of select="ns0:conjunction"/>
                                                         </ns7:conjunction>
                                                      </xsl:if>
                                                      <ns7:upperCaseCompare>
                                                         <xsl:value-of select="ns0:upperCaseCompare"/>
                                                      </ns7:upperCaseCompare>
                                                      <xsl:for-each select="ns0:item">
                                                         <ns7:item>
                                                            <xsl:if test="ns0:conjunction">
                                                               <ns7:conjunction>
                                                                  <xsl:value-of select="ns0:conjunction"/>
                                                               </ns7:conjunction>
                                                            </xsl:if>
                                                            <ns7:upperCaseCompare>
                                                               <xsl:value-of select="ns0:upperCaseCompare"/>
                                                            </ns7:upperCaseCompare>
                                                            <ns7:attribute>
                                                               <xsl:value-of select="ns0:attribute"/>
                                                            </ns7:attribute>
                                                            <ns7:operator>
                                                               <xsl:value-of select="ns0:operator"/>
                                                            </ns7:operator>
                                                            <xsl:for-each select="ns0:value">
                                                               <ns7:value>
                                                                  <xsl:value-of select="."/>
                                                               </ns7:value>
                                                            </xsl:for-each>
                                                         </ns7:item>
                                                      </xsl:for-each>
                                                   </ns7:group>
                                                </xsl:for-each>
                                             </ns7:nested>
                                          </xsl:for-each>
                                       </ns7:nested>
                                    </xsl:if>
                                 </ns7:item>
                              </xsl:for-each>
                           </ns7:group>
                        </xsl:for-each>
                        <xsl:for-each select="ns0:filter/ns0:nested">
                           <ns7:nested>
                              <xsl:if test="ns0:conjunction">
                                 <ns7:conjunction>
                                    <xsl:value-of select="ns0:conjunction"/>
                                 </ns7:conjunction>
                              </xsl:if>
                              <xsl:for-each select="ns0:group">
                                 <ns7:group>
                                    <xsl:if test="ns0:conjunction">
                                       <ns7:conjunction>
                                          <xsl:value-of select="ns0:conjunction"/>
                                       </ns7:conjunction>
                                    </xsl:if>
                                    <ns7:upperCaseCompare>
                                       <xsl:value-of select="ns0:upperCaseCompare"/>
                                    </ns7:upperCaseCompare>
                                    <xsl:for-each select="ns0:item">
                                       <ns7:item>
                                          <xsl:if test="ns0:conjunction">
                                             <ns7:conjunction>
                                                <xsl:value-of select="ns0:conjunction"/>
                                             </ns7:conjunction>
                                          </xsl:if>
                                          <ns7:upperCaseCompare>
                                             <xsl:value-of select="ns0:upperCaseCompare"/>
                                          </ns7:upperCaseCompare>
                                          <ns7:attribute>
                                             <xsl:value-of select="ns0:attribute"/>
                                          </ns7:attribute>
                                          <ns7:operator>
                                             <xsl:value-of select="ns0:operator"/>
                                          </ns7:operator>
                                          <xsl:for-each select="ns0:value">
                                             <ns7:value>
                                                <xsl:value-of select="."/>
                                             </ns7:value>
                                          </xsl:for-each>
                                       </ns7:item>
                                    </xsl:for-each>
                                 </ns7:group>
                              </xsl:for-each>
                           </ns7:nested>
                        </xsl:for-each>
                     </ns7:filter>
                  </xsl:if>
                  <xsl:if test="ns0:sortOrder">
                     <ns7:sortOrder>
                        <xsl:for-each select="ns0:sortOrder/ns0:sortAttribute">
                           <ns7:sortAttribute>
                              <ns7:name>
                                 <xsl:value-of select="ns0:name"/>
                              </ns7:name>
                              <ns7:descending>
                                 <xsl:value-of select="ns0:descending"/>
                              </ns7:descending>
                           </ns7:sortAttribute>
                        </xsl:for-each>
                     </ns7:sortOrder>
                  </xsl:if>
                  <xsl:for-each select="ns0:findAttribute">
                     <ns7:findAttribute>
                        <xsl:value-of select="."/>
                     </ns7:findAttribute>
                  </xsl:for-each>
                  <ns7:excludeAttribute>
                     <xsl:value-of select="ns0:excludeAttribute"/>
                  </ns7:excludeAttribute>
                  <xsl:for-each select="ns0:childFindCriteria">
                     <ns7:childFindCriteria>
                        <ns7:fetchStart>
                           <xsl:value-of select="ns0:fetchStart"/>
                        </ns7:fetchStart>
                        <ns7:fetchSize>
                           <xsl:value-of select="ns0:fetchSize"/>
                        </ns7:fetchSize>
                        <xsl:if test="ns0:filter">
                           <ns7:filter>
                              <xsl:if test="ns0:filter/ns0:conjunction">
                                 <ns7:conjunction>
                                    <xsl:value-of select="ns0:filter/ns0:conjunction"/>
                                 </ns7:conjunction>
                              </xsl:if>
                              <xsl:for-each select="ns0:filter/ns0:group">
                                 <ns7:group>
                                    <xsl:if test="ns0:conjunction">
                                       <ns7:conjunction>
                                          <xsl:value-of select="ns0:conjunction"/>
                                       </ns7:conjunction>
                                    </xsl:if>
                                    <ns7:upperCaseCompare>
                                       <xsl:value-of select="ns0:upperCaseCompare"/>
                                    </ns7:upperCaseCompare>
                                    <xsl:for-each select="ns0:item">
                                       <ns7:item>
                                          <xsl:if test="ns0:conjunction">
                                             <ns7:conjunction>
                                                <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:group/ns0:item/ns0:conjunction"/>
                                             </ns7:conjunction>
                                          </xsl:if>
                                          <ns7:upperCaseCompare>
                                             <xsl:value-of select="ns0:upperCaseCompare"/>
                                          </ns7:upperCaseCompare>
                                          <ns7:attribute>
                                             <xsl:value-of select="ns0:attribute"/>
                                          </ns7:attribute>
                                          <ns7:operator>
                                             <xsl:value-of select="ns0:operator"/>
                                          </ns7:operator>
                                          <xsl:for-each select="ns0:value">
                                             <ns7:value>
                                                <xsl:value-of select="."/>
                                             </ns7:value>
                                          </xsl:for-each>
                                          <xsl:if test="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:group/ns0:item/ns0:nested">
                                             <ns7:nested>
                                                <xsl:if test="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:group/ns0:item/ns0:nested/ns0:conjunction">
                                                   <ns7:conjunction>
                                                      <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:group/ns0:item/ns0:nested/ns0:conjunction"/>
                                                   </ns7:conjunction>
                                                </xsl:if>
                                             </ns7:nested>
                                          </xsl:if>
                                       </ns7:item>
                                    </xsl:for-each>
                                 </ns7:group>
                              </xsl:for-each>
                              <xsl:for-each select="ns0:filter/ns0:nested">
                                 <ns7:nested>
                                    <xsl:if test="ns0:conjunction">
                                       <ns7:conjunction>
                                          <xsl:value-of select="ns0:conjunction"/>
                                       </ns7:conjunction>
                                    </xsl:if>
                                    <xsl:for-each select="ns0:filter/ns0:nested/ns0:group">
                                       <ns7:group>
                                          <xsl:if test="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:nested/ns0:group/ns0:conjunction">
                                             <ns7:conjunction>
                                                <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:nested/ns0:group/ns0:conjunction"/>
                                             </ns7:conjunction>
                                          </xsl:if>
                                          <ns7:upperCaseCompare>
                                             <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:nested/ns0:group/ns0:upperCaseCompare"/>
                                          </ns7:upperCaseCompare>
                                          <xsl:for-each select="ns0:filter/ns0:nested/ns0:group/ns0:item">
                                             <ns7:item>
                                                <xsl:if test="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:nested/ns0:group/ns0:item/ns0:conjunction">
                                                   <ns7:conjunction>
                                                      <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:nested/ns0:group/ns0:item/ns0:conjunction"/>
                                                   </ns7:conjunction>
                                                </xsl:if>
                                                <ns7:upperCaseCompare>
                                                   <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:nested/ns0:group/ns0:item/ns0:upperCaseCompare"/>
                                                </ns7:upperCaseCompare>
                                                <ns7:attribute>
                                                   <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:nested/ns0:group/ns0:item/ns0:attribute"/>
                                                </ns7:attribute>
                                                <ns7:operator>
                                                   <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:nested/ns0:group/ns0:item/ns0:operator"/>
                                                </ns7:operator>
                                                <xsl:for-each select="ns0:filter/ns0:nested/ns0:group/ns0:item/ns0:value">
                                                   <ns7:value>
                                                      <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findCriteria/ns0:childFindCriteria/ns0:childFindCriteria/ns0:filter/ns0:nested/ns0:group/ns0:item/ns0:value"/>
                                                   </ns7:value>
                                                </xsl:for-each>
                                             </ns7:item>
                                          </xsl:for-each>
                                       </ns7:group>
                                    </xsl:for-each>
                                 </ns7:nested>
                              </xsl:for-each>
                           </ns7:filter>
                        </xsl:if>
                        <xsl:if test="ns0:sortOrder">
                           <ns7:sortOrder>
                              <xsl:for-each select="ns0:sortOrder/ns0:sortAttribute">
                                 <ns7:sortAttribute>
                                    <ns7:name>
                                       <xsl:value-of select="ns0:name"/>
                                    </ns7:name>
                                    <ns7:descending>
                                       <xsl:value-of select="ns0:descending"/>
                                    </ns7:descending>
                                 </ns7:sortAttribute>
                              </xsl:for-each>
                           </ns7:sortOrder>
                        </xsl:if>
                        <xsl:for-each select="ns0:findAttribute">
                           <ns7:findAttribute>
                              <xsl:value-of select="."/>
                           </ns7:findAttribute>
                        </xsl:for-each>
                        <ns7:excludeAttribute>
                           <xsl:value-of select="ns0:excludeAttribute"/>
                        </ns7:excludeAttribute>
                        <ns7:childAttrName>
                           <xsl:value-of select="ns0:childAttrName"/>
                        </ns7:childAttrName>
                     </ns7:childFindCriteria>
                  </xsl:for-each>
                  <ns7:childAttrName>
                     <xsl:value-of select="ns0:childAttrName"/>
                  </ns7:childAttrName>
               </ns7:childFindCriteria>
            </xsl:for-each>
         </tns:findCriteria>
         <tns:findControl>
            <ns7:retrieveAllTranslations>
               <xsl:value-of select="/ns0:FindCustomerAccountRq/ns0:findControl/ns0:retrieveAllTranslations"/>
            </ns7:retrieveAllTranslations>
         </tns:findControl>
      </tns:findCustomerAccount>
   </xsl:template>
</xsl:stylesheet>