<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.oracle.com/ReportsSOA" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/XMLSchema_2098908805.xsd"/>
            <oracle-xsl-mapper:rootElement name="reportsSOARq" namespace="http://xmlns.oracle.com/ReportsSOA"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/XMLSchema_2098908805.xsd"/>
            <oracle-xsl-mapper:rootElement name="reportsSOARq" namespace="http://xmlns.oracle.com/ReportsSOA"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON APR 26 20:18:19 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:reportsSOARq>
         <ns0:reportName>
            <xsl:value-of select="/ns0:reportsSOARq/ns0:reportName"/>
         </ns0:reportName>
         <xsl:if test="/ns0:reportsSOARq/ns0:dateInitial">
            <ns0:dateInitial>
               <xsl:value-of select="/ns0:reportsSOARq/ns0:dateInitial"/>
            </ns0:dateInitial>
         </xsl:if>
         <xsl:if test="/ns0:reportsSOARq/ns0:dateFinal">
            <ns0:dateFinal>
               <xsl:value-of select="/ns0:reportsSOARq/ns0:dateFinal"/>
            </ns0:dateFinal>
         </xsl:if>
         <xsl:if test="/ns0:reportsSOARq/ns0:invoiceNumber">
            <ns0:invoiceNumber>
               <xsl:value-of select="/ns0:reportsSOARq/ns0:invoiceNumber"/>
            </ns0:invoiceNumber>
         </xsl:if>
         <ns0:email>
            <xsl:value-of select="/ns0:reportsSOARq/ns0:email"/>
         </ns0:email>
      </ns0:reportsSOARq>
   </xsl:template>
</xsl:stylesheet>