<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbaProcessedReceiptBs" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://soa.estrellaroja.com.mx/FinancialsTec" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/dbaProcessedReceiptBs_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbaProcessedReceiptBs"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/FinancialsTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="ProcessedReceiptRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU JAN 18 10:51:23 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ProcessedReceiptRs>
         <tns:Return>
            <xsl:for-each select="/ns0:OutputParameters/ns0:P_REG_APPLY_RECEIPT/ns0:P_REG_APPLY_RECEIPT_ITEM">
               <tns:ApplyReceipts>
                  <tns:AMOUNT>
                     <xsl:value-of select="ns0:AMOUNT"/>
                  </tns:AMOUNT>
                  <tns:RECEIPT_ID>
                     <xsl:value-of select="ns0:RECEIPT_ID"/>
                  </tns:RECEIPT_ID>
                  <tns:RECEIPT_NUMBER>
                     <xsl:value-of select="ns0:RECEIPT_NUMBER"/>
                  </tns:RECEIPT_NUMBER>
                  <tns:TRANSACTION_NUMBER>
                     <xsl:value-of select="ns0:TRANSACTION_NUMBER"/>
                  </tns:TRANSACTION_NUMBER>
                  <tns:CUSTOMER_NAME>
                     <xsl:value-of select="ns0:CUSTOMER_NAME"/>
                  </tns:CUSTOMER_NAME>
                  <tns:APPLICATION_DATE>
                     <xsl:value-of select="ns0:APPLICATION_DATE"/>
                  </tns:APPLICATION_DATE>
                  <tns:ACCOUNTING_DATE>
                     <xsl:value-of select="ns0:ACCOUNTING_DATE"/>
                  </tns:ACCOUNTING_DATE>
                  <tns:CUST_ACCOUNT_ID>
                     <xsl:value-of select="ns0:CUST_ACCOUNT_ID"/>
                  </tns:CUST_ACCOUNT_ID>
                  <tns:ORGANIZATION_ID>
                     <xsl:value-of select="ns0:ORGANIZATION_ID"/>
                  </tns:ORGANIZATION_ID>
                  <tns:METODO_RECIBO>
                     <xsl:value-of select="ns0:METODO_RECIBO"/>
                  </tns:METODO_RECIBO>
                  <tns:RECEIPT_APPLY_ID>
                     <xsl:value-of select="ns0:RECEIPT_APPLY_ID"/>
                  </tns:RECEIPT_APPLY_ID>
               </tns:ApplyReceipts>
            </xsl:for-each>
            <tns:Error>
               <xsl:value-of select="/ns0:OutputParameters/ns0:P_ERROR"/>
            </tns:Error>
            <tns:ErrorDesc>
               <xsl:value-of select="/ns0:OutputParameters/ns0:P_ERROR_DESC"/>
            </tns:ErrorDesc>
         </tns:Return>
      </tns:ProcessedReceiptRs>
   </xsl:template>
</xsl:stylesheet>