<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbZAMDLV" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbZamDliverPlanEmbarques" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/dbZamDliverPlanEmbarques_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="VBitacoraBlacZamCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbZamDliverPlanEmbarques"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/nxsd_ZamDliverRestResponse.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetPlanEmbarquesRs" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbZAMDLV"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU AUG 26 17:08:03 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetPlanEmbarquesRs>
         <xsl:for-each select="/ns0:VBitacoraBlacZamCollection/ns0:VBitacoraBlacZam">
            <tns:Embarques>
               <tns:noViaje>
                  <xsl:value-of select="ns0:noViaje"/>
               </tns:noViaje>
               <tns:fechaViaje>
                  <xsl:value-of select="ns0:fechaViaje"/>
               </tns:fechaViaje>
               <tns:operadorNombre>
                  <xsl:value-of select="ns0:operadorNombre"/>
               </tns:operadorNombre>
               <tns:operadorTelefono>
                  <xsl:value-of select="ns0:operadorTelefono"/>
               </tns:operadorTelefono>
               <tns:tractorEco>
                  <xsl:value-of select="ns0:tractorEco"/>
               </tns:tractorEco>
               <tns:origen>
                  <xsl:value-of select="ns0:origen"/>
               </tns:origen>
               <tns:descRuta>
                  <xsl:value-of select="ns0:descRuta"/>
               </tns:descRuta>
               <tns:destino>
                  <xsl:value-of select="ns0:destino"/>
               </tns:destino>
               <tns:fechaCita>
                  <xsl:value-of select="ns0:fechaCita"/>
               </tns:fechaCita>
            </tns:Embarques>
         </xsl:for-each>
      </tns:GetPlanEmbarquesRs>
   </xsl:template>
</xsl:stylesheet>