<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbXXER_JOBS_REQUEST" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../Schemas/External/Audit/dbXXER_JOBS_REQUEST_table.xsd"/>
        <oracle-xsl-mapper:rootElement name="XxerJobsRequestCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbXXER_JOBS_REQUEST"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../Schemas/AuditControlTec.xsd"/>
        <oracle-xsl-mapper:rootElement name="GetJobsStatusRs" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED DEC 13 10:11:11 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:GetJobsStatusRs>
      <xsl:if test="/ns0:XxerJobsRequestCollection">
        <cmn:Success/>
      </xsl:if>
      <xsl:if test="count (/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest )  = 0">
        <cmn:Errors>
          <cmn:Error>
            <cmn:ErrorCode>SOA-00010</cmn:ErrorCode>
            <cmn:ShortDescription>No data found</cmn:ShortDescription>
            <cmn:Description>Paraemters not match and no data found</cmn:Description>
            <cmn:BusinessProcess>AuditControlTec</cmn:BusinessProcess>
            <cmn:FailedService>GetJobsStatus</cmn:FailedService>
            <cmn:TimeStamp>
              <xsl:value-of select="xp20:current-dateTime ( )"/>
            </cmn:TimeStamp>
          </cmn:Error>
        </cmn:Errors>
      </xsl:if>
      <xsl:if test="count (/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest ) > 0">
        <tns:Return>
          <tns:Jobs>
            <xsl:if test="/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestUcmId">
              <xsl:if test="not(/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestUcmId/@xsi:nil)">
                <tns:Job>
                  <tns:RequestId>
                    <xsl:value-of select="/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestUcmId"/>
                  </tns:RequestId>
                  <tns:Name>
                    <xsl:value-of select="&quot;IMPORT&quot;"/>
                  </tns:Name>
                  <tns:Status>
                    <xsl:value-of select="/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestUcmStatus"/>
                  </tns:Status>
                </tns:Job>
              </xsl:if>
            </xsl:if>
            <xsl:if test="/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestIntId">
              <xsl:if test="not(/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestIntId/@xsi:nil)">
                <tns:Job>
                  <tns:RequestId>
                    <xsl:value-of select="/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestIntId"/>
                  </tns:RequestId>
                  <tns:Name>
                    <xsl:value-of select="&quot;INTERFACE&quot;"/>
                  </tns:Name>
                  <tns:Status>
                    <xsl:value-of select="/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestUcmStatus"/>
                  </tns:Status>
                </tns:Job>
              </xsl:if>
            </xsl:if>
            <xsl:if test="/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestId">
              <xsl:if test="not(/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestId/@xsi:nil)">
                <tns:Job>
                  <tns:RequestId>
                    <xsl:value-of select="/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestId"/>
                  </tns:RequestId>
                  <tns:Name>
                    <xsl:value-of select="&quot;STANDAR&quot;"/>
                  </tns:Name>
                  <tns:Status>
                    <xsl:value-of select="/ns0:XxerJobsRequestCollection/ns0:XxerJobsRequest/ns0:requestStatus"/>
                  </tns:Status>
                </tns:Job>
              </xsl:if>
            </xsl:if>
          </tns:Jobs>
        </tns:Return>
      </xsl:if>
    </tns:GetJobsStatusRs>
  </xsl:template>
</xsl:stylesheet>