<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbXXER_Transactions" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/AuditControlTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="MergeCtrlTransRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/External/Audit/dbXXER_Transactions_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="XxerIntegrationsTransactionsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbXXER_Transactions"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE DEC 12 18:00:30 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:XxerIntegrationsTransactionsCollection>
         <tns:XxerIntegrationsTransactions>
            <tns:integrationName>
               <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:integrationName"/>
            </tns:integrationName>
            <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:importCreationDate">
               <tns:importCreationDate>
                  <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:importCreationDate"/>
               </tns:importCreationDate>
            </xsl:if>
            <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:processName">
               <tns:processName>
                  <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:processName/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:processName/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:processName"/>
               </tns:processName>
            </xsl:if>
            <tns:creationDate>
               <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:importCreationDate"/>
            </tns:creationDate>
            <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute1">
               <tns:attribute1>
                  <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute1/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute1/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute1"/>
               </tns:attribute1>
            </xsl:if>
            <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute2">
               <tns:attribute2>
                  <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute2/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute2/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute2"/>
               </tns:attribute2>
            </xsl:if>
            <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute3">
               <tns:attribute3>
                  <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute3/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute3/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute3"/>
               </tns:attribute3>
            </xsl:if>
            <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute4">
               <tns:attribute4>
                  <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute4/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute4/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute4"/>
               </tns:attribute4>
            </xsl:if>
            <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute5">
               <tns:attribute5>
                  <xsl:if test="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute5/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute5/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:MergeCtrlTransRq/ns0:integrationTransactions/ns0:attribute5"/>
               </tns:attribute5>
            </xsl:if>
         </tns:XxerIntegrationsTransactions>
      </tns:XxerIntegrationsTransactionsCollection>
   </xsl:template>
</xsl:stylesheet>