<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpCreateApplyReceipt/types" xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0" xmlns:ns3="http://xmlns.oracle.com/apps/flex/financials/receivables/receipts/shared/standardReceiptService/commonService/ApplyReceiptDff/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:types="http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/" xmlns:ns1="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns4="http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/" xmlns:ns5="http://xmlns.oracle.com/adf/svc/types/" xmlns:sdoJava="commonj.sdo/java" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpCreateApplyReceipt" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../../WSDL/Externals/Cloud/Receipt/erpCreateApplyReceipt.wsdl"/>
            <oracle-xsl-mapper:rootElement name="createApplyReceiptResponse" namespace="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpCreateApplyReceipt/types"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="CreateApplyReceiptRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 21 13:09:03 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CreateApplyReceiptRs>
         <xsl:if test="/ns0:createApplyReceiptResponse/ns0:result">
            <cmn:Success/>
         </xsl:if>
         <xsl:if test="/ns0:createApplyReceiptResponse/ns0:result/ns5:Message">
            <cmn:Errors>
               <xsl:for-each select="/ns0:createApplyReceiptResponse/ns0:result/ns5:Message">
                  <cmn:Error>
                     <cmn:ErrorCode>
                        <xsl:value-of select="ns1:code"/>
                     </cmn:ErrorCode>
                     <cmn:ShortDescription>
                        <xsl:value-of select="ns1:severity"/>
                     </cmn:ShortDescription>
                     <cmn:Description>
                        <xsl:value-of select="ns1:message"/>
                     </cmn:Description>
                     <cmn:BusinessProcess>CreateApplyReceipt</cmn:BusinessProcess>
                     <cmn:FailedService>ERPIntegrationServiceTec</cmn:FailedService>
                     <cmn:TimeStamp>
                        <xsl:value-of select="xp20:current-dateTime ( )"/>
                     </cmn:TimeStamp>
                  </cmn:Error>
               </xsl:for-each>
            </cmn:Errors>
         </xsl:if>
         <tns:Return>
            <xsl:for-each select="/ns0:createApplyReceiptResponse/ns0:result/ns4:Value">
               <tns:Value>
                  <xsl:if test="ns4:AmountApplied">
                     <tns:AmountApplied>
                        <xsl:value-of select="ns4:AmountApplied"/>
                     </tns:AmountApplied>
                  </xsl:if>
                  <xsl:if test="ns4:ReceiptId">
                     <tns:ReceiptId>
                        <xsl:if test="ns4:ReceiptId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:ReceiptId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:ReceiptId"/>
                     </tns:ReceiptId>
                  </xsl:if>
                  <xsl:if test="ns4:Comments">
                     <tns:Comments>
                        <xsl:if test="ns4:Comments/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:Comments/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:Comments"/>
                     </tns:Comments>
                  </xsl:if>
                  <xsl:if test="ns4:CustomerTrxId">
                     <tns:CustomerTrxId>
                        <xsl:if test="ns4:CustomerTrxId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:CustomerTrxId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:CustomerTrxId"/>
                     </tns:CustomerTrxId>
                  </xsl:if>
                  <xsl:if test="ns4:Discount">
                     <tns:Discount>
                        <xsl:if test="ns4:Discount/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:Discount/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:Discount"/>
                     </tns:Discount>
                  </xsl:if>
                  <xsl:if test="ns4:Instalment">
                     <tns:Instalment>
                        <xsl:if test="ns4:Instalment/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:Instalment/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:Instalment"/>
                     </tns:Instalment>
                  </xsl:if>
                  <xsl:if test="ns4:ReceiptNumber">
                     <tns:ReceiptNumber>
                        <xsl:if test="ns4:ReceiptNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:ReceiptNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:ReceiptNumber"/>
                     </tns:ReceiptNumber>
                  </xsl:if>
                  <xsl:if test="ns4:TransactionNumber">
                     <tns:TransactionNumber>
                        <xsl:if test="ns4:TransactionNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:TransactionNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:TransactionNumber"/>
                     </tns:TransactionNumber>
                  </xsl:if>
                  <xsl:if test="ns4:ReceiptAmount">
                     <tns:ReceiptAmount>
                        <xsl:if test="ns4:ReceiptAmount/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:ReceiptAmount/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:ReceiptAmount"/>
                     </tns:ReceiptAmount>
                  </xsl:if>
                  <xsl:if test="ns4:ReceiptDate">
                     <tns:ReceiptDate>
                        <xsl:if test="ns4:ReceiptDate/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:ReceiptDate/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:ReceiptDate"/>
                     </tns:ReceiptDate>
                  </xsl:if>
                  <xsl:if test="ns4:CustomerName">
                     <tns:CustomerName>
                        <xsl:if test="ns4:CustomerName/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:CustomerName/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:CustomerName"/>
                     </tns:CustomerName>
                  </xsl:if>
                  <xsl:if test="ns4:TransactionDate">
                     <tns:TransactionDate>
                        <xsl:if test="ns4:TransactionDate/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:TransactionDate/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:TransactionDate"/>
                     </tns:TransactionDate>
                  </xsl:if>
                  <xsl:if test="ns4:TransactionSource">
                     <tns:TransactionSource>
                        <xsl:if test="ns4:TransactionSource/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:TransactionSource/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:TransactionSource"/>
                     </tns:TransactionSource>
                  </xsl:if>
                  <xsl:if test="ns4:AmountReceiptCurrency">
                     <tns:AmountReceiptCurrency>
                        <xsl:if test="ns4:AmountReceiptCurrency/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:AmountReceiptCurrency/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:AmountReceiptCurrency"/>
                     </tns:AmountReceiptCurrency>
                  </xsl:if>
                  <xsl:if test="ns4:ReceiptCurrency">
                     <tns:ReceiptCurrency>
                        <xsl:if test="ns4:ReceiptCurrency/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:ReceiptCurrency/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:ReceiptCurrency"/>
                     </tns:ReceiptCurrency>
                  </xsl:if>
                  <xsl:if test="ns4:ExchangeRate">
                     <tns:ExchangeRate>
                        <xsl:if test="ns4:ExchangeRate/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:ExchangeRate/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:ExchangeRate"/>
                     </tns:ExchangeRate>
                  </xsl:if>
                  <xsl:if test="ns4:ApplicationDate">
                     <tns:ApplicationDate>
                        <xsl:value-of select="ns4:ApplicationDate"/>
                     </tns:ApplicationDate>
                  </xsl:if>
                  <xsl:if test="ns4:AccountingDate">
                     <tns:AccountingDate>
                        <xsl:value-of select="ns4:AccountingDate"/>
                     </tns:AccountingDate>
                  </xsl:if>
                  <xsl:if test="ns4:ApplyClosedInvoices">
                     <tns:ApplyClosedInvoices>
                        <xsl:if test="ns4:ApplyClosedInvoices/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:ApplyClosedInvoices/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:ApplyClosedInvoices"/>
                     </tns:ApplyClosedInvoices>
                  </xsl:if>
                  <xsl:if test="ns4:InstalmentId">
                     <tns:InstalmentId>
                        <xsl:if test="ns4:InstalmentId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns4:InstalmentId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns4:InstalmentId"/>
                     </tns:InstalmentId>
                  </xsl:if>
                  <xsl:if test="ns4:ReceivableApplicationFLEXVA">
                     <tns:ReceivableApplicationFLEXVA>
                        <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:ReceivableApplicationId">
                           <tns:ReceivableApplicationId>
                              <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:ReceivableApplicationId"/>
                           </tns:ReceivableApplicationId>
                        </xsl:if>
                        <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:listoParaTimbre">
                           <tns:ListoParaTimbre>
                              <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:listoParaTimbre/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:listoParaTimbre/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:listoParaTimbre"/>
                           </tns:ListoParaTimbre>
                        </xsl:if>
                        <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:listoParaTimbre_DisplayValue">
                           <tns:ListoParaTimbreDisplayValue>
                              <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:listoParaTimbre_DisplayValue/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:listoParaTimbre_DisplayValue/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:listoParaTimbre_DisplayValue"/>
                           </tns:ListoParaTimbreDisplayValue>
                        </xsl:if>
                        <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:reProceso">
                           <tns:ReProceso>
                              <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:reProceso/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:reProceso/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:reProceso"/>
                           </tns:ReProceso>
                        </xsl:if>
                        <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:reProceso_DisplayValue">
                           <tns:ReProcesoDisplayValue>
                              <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:reProceso_DisplayValue/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:reProceso_DisplayValue/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:reProceso_DisplayValue"/>
                           </tns:ReProcesoDisplayValue>
                        </xsl:if>
                        <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:__FLEX_Context">
                           <tns:FLEXContext>
                              <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:__FLEX_Context"/>
                           </tns:FLEXContext>
                        </xsl:if>
                        <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:__FLEX_Context_DisplayValue">
                           <tns:FLEXContextDisplayValue>
                              <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:__FLEX_Context_DisplayValue"/>
                           </tns:FLEXContextDisplayValue>
                        </xsl:if>
                        <xsl:if test="ns4:ReceivableApplicationFLEXVA/ns3:_FLEX_NumOfSegments">
                           <tns:FLEXNumOfSegments>
                              <xsl:value-of select="ns4:ReceivableApplicationFLEXVA/ns3:_FLEX_NumOfSegments"/>
                           </tns:FLEXNumOfSegments>
                        </xsl:if>
                     </tns:ReceivableApplicationFLEXVA>
                  </xsl:if>
               </tns:Value>
            </xsl:for-each>
         </tns:Return>
      </tns:CreateApplyReceiptRs>
   </xsl:template>
</xsl:stylesheet>