<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpCreateApplyReceipt/types" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0" xmlns:ns3="http://xmlns.oracle.com/apps/flex/financials/receivables/receipts/shared/standardReceiptService/commonService/ApplyReceiptDff/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:types="http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/" xmlns:ns1="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns4="http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/" xmlns:ns5="http://xmlns.oracle.com/adf/svc/types/" xmlns:sdoJava="commonj.sdo/java" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpCreateApplyReceipt" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="CreateApplyReceiptRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../../WSDL/Externals/Cloud/Receipt/erpCreateApplyReceipt.wsdl"/>
            <oracle-xsl-mapper:rootElement name="createApplyReceipt" namespace="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpCreateApplyReceipt/types"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 21 12:53:49 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:createApplyReceipt>
         <xsl:for-each select="/ns0:CreateApplyReceiptRq/ns0:ApplyReceiptType">
            <tns:applyReceipt>
               <xsl:if test="ns0:AmountApplied">
                  <ns4:AmountApplied>
                     <xsl:value-of select="ns0:AmountApplied"/>
                  </ns4:AmountApplied>
               </xsl:if>
               <xsl:if test="ns0:ReceiptId">
                  <ns4:ReceiptId>
                     <xsl:if test="ns0:ReceiptId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ReceiptId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ReceiptId"/>
                  </ns4:ReceiptId>
               </xsl:if>
               <xsl:if test="ns0:Comments">
                  <ns4:Comments>
                     <xsl:if test="ns0:Comments/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Comments/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Comments"/>
                  </ns4:Comments>
               </xsl:if>
               <xsl:if test="ns0:CustomerTrxId">
                  <ns4:CustomerTrxId>
                     <xsl:if test="ns0:CustomerTrxId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CustomerTrxId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CustomerTrxId"/>
                  </ns4:CustomerTrxId>
               </xsl:if>
               <xsl:if test="ns0:Discount">
                  <ns4:Discount>
                     <xsl:if test="ns0:Discount/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Discount/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Discount"/>
                  </ns4:Discount>
               </xsl:if>
               <xsl:if test="ns0:Instalment">
                  <ns4:Instalment>
                     <xsl:if test="ns0:Instalment/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Instalment/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Instalment"/>
                  </ns4:Instalment>
               </xsl:if>
               <xsl:if test="ns0:ReceiptNumber">
                  <ns4:ReceiptNumber>
                     <xsl:if test="ns0:ReceiptNumber/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ReceiptNumber/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ReceiptNumber"/>
                  </ns4:ReceiptNumber>
               </xsl:if>
               <xsl:if test="ns0:TransactionNumber">
                  <ns4:TransactionNumber>
                     <xsl:if test="ns0:TransactionNumber/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionNumber/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionNumber"/>
                  </ns4:TransactionNumber>
               </xsl:if>
               <xsl:if test="ns0:ReceiptAmount">
                  <ns4:ReceiptAmount>
                     <xsl:if test="ns0:ReceiptAmount/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ReceiptAmount/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ReceiptAmount"/>
                  </ns4:ReceiptAmount>
               </xsl:if>
               <xsl:if test="ns0:ReceiptDate">
                  <ns4:ReceiptDate>
                     <xsl:if test="ns0:ReceiptDate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ReceiptDate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ReceiptDate"/>
                  </ns4:ReceiptDate>
               </xsl:if>
               <xsl:if test="ns0:CustomerName">
                  <ns4:CustomerName>
                     <xsl:if test="ns0:CustomerName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CustomerName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CustomerName"/>
                  </ns4:CustomerName>
               </xsl:if>
               <xsl:if test="ns0:TransactionDate">
                  <ns4:TransactionDate>
                     <xsl:if test="ns0:TransactionDate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionDate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionDate"/>
                  </ns4:TransactionDate>
               </xsl:if>
               <xsl:if test="ns0:TransactionSource">
                  <ns4:TransactionSource>
                     <xsl:if test="ns0:TransactionSource/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionSource/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionSource"/>
                  </ns4:TransactionSource>
               </xsl:if>
               <xsl:if test="ns0:AmountReceiptCurrency">
                  <ns4:AmountReceiptCurrency>
                     <xsl:if test="ns0:AmountReceiptCurrency/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:AmountReceiptCurrency/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:AmountReceiptCurrency"/>
                  </ns4:AmountReceiptCurrency>
               </xsl:if>
               <xsl:if test="ns0:ReceiptCurrency">
                  <ns4:ReceiptCurrency>
                     <xsl:if test="ns0:ReceiptCurrency/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ReceiptCurrency/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ReceiptCurrency"/>
                  </ns4:ReceiptCurrency>
               </xsl:if>
               <xsl:if test="ns0:ExchangeRate">
                  <ns4:ExchangeRate>
                     <xsl:if test="ns0:ExchangeRate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ExchangeRate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ExchangeRate"/>
                  </ns4:ExchangeRate>
               </xsl:if>
               <xsl:if test="ns0:ApplicationDate">
                  <ns4:ApplicationDate>
                     <xsl:value-of select="ns0:ApplicationDate"/>
                  </ns4:ApplicationDate>
               </xsl:if>
               <xsl:if test="ns0:AccountingDate">
                  <ns4:AccountingDate>
                     <xsl:value-of select="ns0:AccountingDate"/>
                  </ns4:AccountingDate>
               </xsl:if>
               <xsl:if test="ns0:ApplyClosedInvoices">
                  <ns4:ApplyClosedInvoices>
                     <xsl:if test="ns0:ApplyClosedInvoices/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ApplyClosedInvoices/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ApplyClosedInvoices"/>
                  </ns4:ApplyClosedInvoices>
               </xsl:if>
               <xsl:if test="ns0:InstalmentId">
                  <ns4:InstalmentId>
                     <xsl:if test="ns0:InstalmentId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:InstalmentId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:InstalmentId"/>
                  </ns4:InstalmentId>
               </xsl:if>
               <xsl:if test="ns0:ReceivableApplicationFLEXVA">
                  <ns4:ReceivableApplicationFLEXVA>
                     <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:ReceivableApplicationId">
                        <ns3:ReceivableApplicationId>
                           <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:ReceivableApplicationId"/>
                        </ns3:ReceivableApplicationId>
                     </xsl:if>
                     <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:ListoParaTimbre">
                        <ns3:listoParaTimbre>
                           <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:ListoParaTimbre/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:ListoParaTimbre/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:ListoParaTimbre"/>
                        </ns3:listoParaTimbre>
                     </xsl:if>
                     <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:ListoParaTimbreDisplayValue">
                        <ns3:listoParaTimbre_DisplayValue>
                           <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:ListoParaTimbreDisplayValue/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:ListoParaTimbreDisplayValue/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:ListoParaTimbreDisplayValue"/>
                        </ns3:listoParaTimbre_DisplayValue>
                     </xsl:if>
                     <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:ReProceso">
                        <ns3:reProceso>
                           <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:ReProceso/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:ReProceso/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:ReProceso"/>
                        </ns3:reProceso>
                     </xsl:if>
                     <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:ReProcesoDisplayValue">
                        <ns3:reProceso_DisplayValue>
                           <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:ReProcesoDisplayValue/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:ReProcesoDisplayValue/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:ReProcesoDisplayValue"/>
                        </ns3:reProceso_DisplayValue>
                     </xsl:if>
                     <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:FLEXContext">
                        <ns3:__FLEX_Context>
                           <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:FLEXContext"/>
                        </ns3:__FLEX_Context>
                     </xsl:if>
                     <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:FLEXContextDisplayValue">
                        <ns3:__FLEX_Context_DisplayValue>
                           <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:FLEXContextDisplayValue"/>
                        </ns3:__FLEX_Context_DisplayValue>
                     </xsl:if>
                     <xsl:if test="ns0:ReceivableApplicationFLEXVA/ns0:FLEXNumOfSegments">
                        <ns3:_FLEX_NumOfSegments>
                           <xsl:value-of select="ns0:ReceivableApplicationFLEXVA/ns0:FLEXNumOfSegments"/>
                        </ns3:_FLEX_NumOfSegments>
                     </xsl:if>
                  </ns4:ReceivableApplicationFLEXVA>
               </xsl:if>
            </tns:applyReceipt>
         </xsl:for-each>
      </tns:createApplyReceipt>
   </xsl:template>
</xsl:stylesheet>