<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl dig UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:dig="http://soa.estrellaroja.com.mx/DigitalStampTec" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns1="http://www.sat.gob.mx/TimbreFiscalDigital" xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:ns2="http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI" xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns0="http://soa.estrellaroja.com.mx/cfd/3" xmlns:ns4="http://soa.estrellaroja.com.mx/sitio_internet/cfd/tipoDatos/tdCFDI" xmlns:ns5="http://soa.estrellaroja.com.mx/TimbreFiscalDigital">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NXSDs/nxsd_createCFDI_JasonRs.xsd"/>
            <oracle-xsl-mapper:rootElement name="invoice" namespace="http://soa.estrellaroja.com.mx/DigitalStampTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/DigitalStampTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="createTrxCFDIRs" namespace="http://soa.estrellaroja.com.mx/DigitalStampTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED DEC 06 16:59:13 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <dig:createTrxCFDIRs>
         <xsl:if test="contains (/dig:invoice/dig:stamping_code, &quot;100&quot; )">
            <cmn:Success/>
         </xsl:if>
         <xsl:if test="not (contains (/dig:invoice/dig:stamping_code, &quot;100&quot; ) )">
            <cmn:Errors>
               <cmn:Error>
                  <cmn:ErrorCode>
                     <xsl:value-of select="/dig:invoice/dig:stamping_code"/>
                  </cmn:ErrorCode>
                  <cmn:ShortDescription>
                     <xsl:value-of select="/dig:invoice/dig:stamping_message"/>
                  </cmn:ShortDescription>
                  <cmn:Description>
                     <xsl:value-of select="/dig:invoice/dig:stamping_message"/>
                  </cmn:Description>
                  <cmn:BusinessProcess>createTrxCFDI</cmn:BusinessProcess>
                  <cmn:FailedService>DigitalStampTec</cmn:FailedService>
                  <cmn:TimeStamp>
                     <xsl:value-of select="xp20:current-dateTime ( )"/>
                  </cmn:TimeStamp>
               </cmn:Error>
            </cmn:Errors>
         </xsl:if>
         <dig:Return>
            <dig:invoiceRs>
               <dig:id>
                  <xsl:value-of select="/dig:invoice/dig:id"/>
               </dig:id>
               <dig:id_rfc>
                  <xsl:value-of select="/dig:invoice/dig:id_rfc"/>
               </dig:id_rfc>
               <dig:serie>
                  <xsl:value-of select="/dig:invoice/dig:serie"/>
               </dig:serie>
               <dig:certificate_number>
                  <xsl:value-of select="/dig:invoice/dig:certificate_number"/>
               </dig:certificate_number>
               <dig:invoice_date>
                  <xsl:value-of select="/dig:invoice/dig:invoice_date"/>
               </dig:invoice_date>
               <dig:invoice_seal>
                  <xsl:value-of select="/dig:invoice/dig:invoice_seal"/>
               </dig:invoice_seal>
               <dig:receiver_rfc>
                  <xsl:value-of select="/dig:invoice/dig:receiver_rfc"/>
               </dig:receiver_rfc>
               <dig:receiver_name>
                  <xsl:value-of select="/dig:invoice/dig:receiver_name"/>
               </dig:receiver_name>
               <dig:receiver_street>
                  <xsl:value-of select="/dig:invoice/dig:receiver_street"/>
               </dig:receiver_street>
               <dig:receiver_ext_number>
                  <xsl:value-of select="/dig:invoice/dig:receiver_ext_number"/>
               </dig:receiver_ext_number>
               <dig:receiver_int_number>
                  <xsl:value-of select="/dig:invoice/dig:receiver_int_number"/>
               </dig:receiver_int_number>
               <dig:receiver_colony>
                  <xsl:value-of select="/dig:invoice/dig:receiver_colony"/>
               </dig:receiver_colony>
               <dig:receiver_zip_code>
                  <xsl:value-of select="/dig:invoice/dig:receiver_zip_code"/>
               </dig:receiver_zip_code>
               <dig:receiver_municipality>
                  <xsl:value-of select="/dig:invoice/dig:receiver_municipality"/>
               </dig:receiver_municipality>
               <dig:receiver_state>
                  <xsl:value-of select="/dig:invoice/dig:receiver_state"/>
               </dig:receiver_state>
               <dig:receiver_phone>
                  <xsl:value-of select="/dig:invoice/dig:receiver_phone"/>
               </dig:receiver_phone>
               <dig:receiver_country>
                  <xsl:value-of select="/dig:invoice/dig:receiver_country"/>
               </dig:receiver_country>
               <dig:receiver_passport>
                  <xsl:value-of select="/dig:invoice/dig:receiver_passport"/>
               </dig:receiver_passport>
               <dig:receiver_cfdi_use>
                  <xsl:value-of select="/dig:invoice/dig:receiver_cfdi_use"/>
               </dig:receiver_cfdi_use>
               <dig:issuer_rfc>
                  <xsl:value-of select="/dig:invoice/dig:issuer_rfc"/>
               </dig:issuer_rfc>
               <dig:issuer_name>
                  <xsl:value-of select="/dig:invoice/dig:issuer_name"/>
               </dig:issuer_name>
               <dig:issuer_street>
                  <xsl:value-of select="/dig:invoice/dig:issuer_street"/>
               </dig:issuer_street>
               <dig:issuer_ext_number>
                  <xsl:value-of select="/dig:invoice/dig:issuer_ext_number"/>
               </dig:issuer_ext_number>
               <dig:issuer_int_number>
                  <xsl:value-of select="/dig:invoice/dig:issuer_int_number"/>
               </dig:issuer_int_number>
               <dig:issuer_colony>
                  <xsl:value-of select="/dig:invoice/dig:issuer_colony"/>
               </dig:issuer_colony>
               <dig:issuer_zip_code>
                  <xsl:value-of select="/dig:invoice/dig:issuer_zip_code"/>
               </dig:issuer_zip_code>
               <dig:issuer_municipality>
                  <xsl:value-of select="/dig:invoice/dig:issuer_municipality"/>
               </dig:issuer_municipality>
               <dig:issuer_state>
                  <xsl:value-of select="/dig:invoice/dig:issuer_state"/>
               </dig:issuer_state>
               <dig:issuer_phone>
                  <xsl:value-of select="/dig:invoice/dig:issuer_phone"/>
               </dig:issuer_phone>
               <dig:issuer_country>
                  <xsl:value-of select="/dig:invoice/dig:issuer_country"/>
               </dig:issuer_country>
               <dig:branch_name>
                  <xsl:value-of select="/dig:invoice/dig:branch_name"/>
               </dig:branch_name>
               <dig:branch_street>
                  <xsl:value-of select="/dig:invoice/dig:branch_street"/>
               </dig:branch_street>
               <dig:branch_ext_number>
                  <xsl:value-of select="/dig:invoice/dig:branch_ext_number"/>
               </dig:branch_ext_number>
               <dig:branch_int_number>
                  <xsl:value-of select="/dig:invoice/dig:branch_int_number"/>
               </dig:branch_int_number>
               <dig:branch_colony>
                  <xsl:value-of select="/dig:invoice/dig:branch_colony"/>
               </dig:branch_colony>
               <dig:branch_zip_code>
                  <xsl:value-of select="/dig:invoice/dig:branch_zip_code"/>
               </dig:branch_zip_code>
               <dig:branch_municipality>
                  <xsl:value-of select="/dig:invoice/dig:branch_municipality"/>
               </dig:branch_municipality>
               <dig:branch_state>
                  <xsl:value-of select="/dig:invoice/dig:branch_state"/>
               </dig:branch_state>
               <dig:branch_reference>
                  <xsl:value-of select="/dig:invoice/dig:branch_reference"/>
               </dig:branch_reference>
               <dig:branch_phone>
                  <xsl:value-of select="/dig:invoice/dig:branch_phone"/>
               </dig:branch_phone>
               <dig:branch_country>
                  <xsl:value-of select="/dig:invoice/dig:branch_country"/>
               </dig:branch_country>
               <dig:payment_form>
                  <xsl:value-of select="/dig:invoice/dig:payment_form"/>
               </dig:payment_form>
               <dig:payment_condition>
                  <xsl:value-of select="/dig:invoice/dig:payment_condition"/>
               </dig:payment_condition>
               <dig:payment_method>
                  <xsl:value-of select="/dig:invoice/dig:payment_method"/>
               </dig:payment_method>
               <dig:payment_account_number>
                  <xsl:value-of select="/dig:invoice/dig:payment_account_number"/>
               </dig:payment_account_number>
               <dig:payment_status>
                  <xsl:value-of select="/dig:invoice/dig:payment_status"/>
               </dig:payment_status>
               <dig:retention_vat>
                  <xsl:value-of select="/dig:invoice/dig:retention_vat"/>
               </dig:retention_vat>
               <dig:retention_rt>
                  <xsl:value-of select="/dig:invoice/dig:retention_rt"/>
               </dig:retention_rt>
               <dig:discount>
                  <xsl:value-of select="/dig:invoice/dig:discount"/>
               </dig:discount>
               <dig:total_items>
                  <xsl:value-of select="/dig:invoice/dig:total_items"/>
               </dig:total_items>
               <dig:total_vat>
                  <xsl:value-of select="/dig:invoice/dig:total_vat"/>
               </dig:total_vat>
               <dig:total_stps>
                  <xsl:value-of select="/dig:invoice/dig:total_stps"/>
               </dig:total_stps>
               <dig:total_st>
                  <xsl:value-of select="/dig:invoice/dig:total_st"/>
               </dig:total_st>
               <dig:total_tip>
                  <xsl:value-of select="/dig:invoice/dig:total_tip"/>
               </dig:total_tip>
               <dig:subtotal>
                  <xsl:value-of select="/dig:invoice/dig:subtotal"/>
               </dig:subtotal>
               <dig:total>
                  <xsl:value-of select="/dig:invoice/dig:total"/>
               </dig:total>
               <dig:additional_information>
                  <xsl:value-of select="/dig:invoice/dig:additional_information"/>
               </dig:additional_information>
               <dig:comments>
                  <xsl:value-of select="/dig:invoice/dig:comments"/>
               </dig:comments>
               <dig:currency>
                  <xsl:value-of select="/dig:invoice/dig:currency"/>
               </dig:currency>
               <dig:currency_exchange_rate>
                  <xsl:value-of select="/dig:invoice/dig:currency_exchange_rate"/>
               </dig:currency_exchange_rate>
               <dig:cancellation_reason>
                  <xsl:value-of select="/dig:invoice/dig:cancellation_reason"/>
               </dig:cancellation_reason>
               <dig:cancellation_date>
                  <xsl:value-of select="/dig:invoice/dig:cancellation_date"/>
               </dig:cancellation_date>
               <dig:approval_number>
                  <xsl:value-of select="/dig:invoice/dig:approval_number"/>
               </dig:approval_number>
               <dig:approval_year>
                  <xsl:value-of select="/dig:invoice/dig:approval_year"/>
               </dig:approval_year>
               <dig:stamping_uuid>
                  <xsl:value-of select="/dig:invoice/dig:stamping_uuid"/>
               </dig:stamping_uuid>
               <dig:stamping_date>
                  <xsl:value-of select="/dig:invoice/dig:stamping_date"/>
               </dig:stamping_date>
               <dig:stamping_certificate_number>
                  <xsl:value-of select="/dig:invoice/dig:stamping_certificate_number"/>
               </dig:stamping_certificate_number>
               <dig:stamping_seal>
                  <xsl:value-of select="/dig:invoice/dig:stamping_seal"/>
               </dig:stamping_seal>
               <dig:document_number>
                  <xsl:value-of select="/dig:invoice/dig:document_number"/>
               </dig:document_number>
               <dig:discount_reason>
                  <xsl:value-of select="/dig:invoice/dig:discount_reason"/>
               </dig:discount_reason>
               <dig:document_type>
                  <xsl:value-of select="/dig:invoice/dig:document_type"/>
               </dig:document_type>
               <dig:issuer_locality>
                  <xsl:value-of select="/dig:invoice/dig:issuer_locality"/>
               </dig:issuer_locality>
               <dig:issuer_reference>
                  <xsl:value-of select="/dig:invoice/dig:issuer_reference"/>
               </dig:issuer_reference>
               <dig:branch_locality>
                  <xsl:value-of select="/dig:invoice/dig:branch_locality"/>
               </dig:branch_locality>
               <dig:issuer_tax_regime>
                  <xsl:value-of select="/dig:invoice/dig:issuer_tax_regime"/>
               </dig:issuer_tax_regime>
               <dig:receiver_reference>
                  <xsl:value-of select="/dig:invoice/dig:receiver_reference"/>
               </dig:receiver_reference>
               <dig:stamping_code>
                  <xsl:value-of select="/dig:invoice/dig:stamping_code"/>
               </dig:stamping_code>
               <dig:stamping_message>
                  <xsl:value-of select="/dig:invoice/dig:stamping_message"/>
               </dig:stamping_message>
               <dig:relationship_type>
                  <xsl:value-of select="/dig:invoice/dig:relationship_type"/>
               </dig:relationship_type>
               <dig:related_cfdi>
                  <xsl:value-of select="/dig:invoice/dig:related_cfdi"/>
               </dig:related_cfdi>
               <xsl:for-each select="/dig:invoice/dig:invoice_items">
                  <dig:invoice_items>
                     <dig:id>
                        <xsl:value-of select="dig:id"/>
                     </dig:id>
                     <dig:position>
                        <xsl:value-of select="dig:position"/>
                     </dig:position>
                     <dig:prod_serv_key>
                        <xsl:value-of select="dig:prod_serv_key"/>
                     </dig:prod_serv_key>
                     <dig:description>
                        <xsl:value-of select="dig:description"/>
                     </dig:description>
                     <dig:quantity>
                        <xsl:value-of select="dig:quantity"/>
                     </dig:quantity>
                     <dig:unit>
                        <xsl:value-of select="dig:unit"/>
                     </dig:unit>
                     <dig:unit_key>
                        <xsl:value-of select="dig:unit_key"/>
                     </dig:unit_key>
                     <dig:unit_price>
                        <xsl:value-of select="dig:unit_price"/>
                     </dig:unit_price>
                     <dig:tax>
                        <xsl:value-of select="dig:tax"/>
                     </dig:tax>
                     <dig:factor_type>
                        <xsl:value-of select="dig:factor_type"/>
                     </dig:factor_type>
                     <dig:rate_fee>
                        <xsl:value-of select="dig:rate_fee"/>
                     </dig:rate_fee>
                     <dig:discount>
                        <xsl:value-of select="dig:discount"/>
                     </dig:discount>
                     <dig:vat>
                        <xsl:value-of select="dig:vat"/>
                     </dig:vat>
                     <dig:vat_percentage>
                        <xsl:value-of select="dig:vat_percentage"/>
                     </dig:vat_percentage>
                     <dig:stps>
                        <xsl:value-of select="dig:stps"/>
                     </dig:stps>
                     <dig:stps_percentage>
                        <xsl:value-of select="dig:stps_percentage"/>
                     </dig:stps_percentage>
                     <dig:st>
                        <xsl:value-of select="dig:st"/>
                     </dig:st>
                     <dig:st_percentage>
                        <xsl:value-of select="dig:st_percentage"/>
                     </dig:st_percentage>
                     <dig:total>
                        <xsl:value-of select="dig:total"/>
                     </dig:total>
                     <dig:customs_name>
                        <xsl:value-of select="dig:customs_name"/>
                     </dig:customs_name>
                     <dig:customs_number>
                        <xsl:value-of select="dig:customs_number"/>
                     </dig:customs_number>
                     <dig:customs_date>
                        <xsl:value-of select="dig:customs_date"/>
                     </dig:customs_date>
                     <dig:id_invoice>
                        <xsl:value-of select="dig:id_invoice"/>
                     </dig:id_invoice>
                  </dig:invoice_items>
               </xsl:for-each>
               <xsl:for-each select="/dig:invoice/dig:payment_complements">
                  <dig:payment_complements>
                     <dig:id>
                        <xsl:value-of select="dig:id"/>
                     </dig:id>
                     <dig:invoice_id>
                        <xsl:value-of select="dig:invoice_id"/>
                     </dig:invoice_id>
                     <dig:payment_date>
                        <xsl:value-of select="dig:payment_date"/>
                     </dig:payment_date>
                     <dig:payment_way>
                        <xsl:value-of select="dig:payment_way"/>
                     </dig:payment_way>
                     <dig:currency>
                        <xsl:value-of select="dig:currency"/>
                     </dig:currency>
                     <dig:currency_exchange>
                        <xsl:value-of select="dig:currency_exchange"/>
                     </dig:currency_exchange>
                     <dig:amount>
                        <xsl:value-of select="dig:amount"/>
                     </dig:amount>
                     <dig:operation_number>
                        <xsl:value-of select="dig:operation_number"/>
                     </dig:operation_number>
                     <dig:ord_acc_issuer_rfc>
                        <xsl:value-of select="dig:ord_acc_issuer_rfc"/>
                     </dig:ord_acc_issuer_rfc>
                     <dig:bank_name>
                        <xsl:value-of select="dig:bank_name"/>
                     </dig:bank_name>
                     <dig:payer_account>
                        <xsl:value-of select="dig:payer_account"/>
                     </dig:payer_account>
                     <dig:ben_acc_issuer_rfc>
                        <xsl:value-of select="dig:ben_acc_issuer_rfc"/>
                     </dig:ben_acc_issuer_rfc>
                     <dig:beneficiary_account>
                        <xsl:value-of select="dig:beneficiary_account"/>
                     </dig:beneficiary_account>
                     <dig:payment_string_type>
                        <xsl:value-of select="dig:payment_string_type"/>
                     </dig:payment_string_type>
                     <dig:payment_cert>
                        <xsl:value-of select="dig:payment_cert"/>
                     </dig:payment_cert>
                     <dig:payment_string>
                        <xsl:value-of select="dig:payment_string"/>
                     </dig:payment_string>
                     <dig:payment_seal>
                        <xsl:value-of select="dig:payment_seal"/>
                     </dig:payment_seal>
                     <dig:version>
                        <xsl:value-of select="dig:version"/>
                     </dig:version>
                     <dig:related_documents>
                        <dig:id>
                           <xsl:value-of select="dig:related_documents/dig:id"/>
                        </dig:id>
                        <dig:id_payment_complement>
                           <xsl:value-of select="dig:related_documents/dig:id_payment_complement"/>
                        </dig:id_payment_complement>
                        <dig:document_id>
                           <xsl:value-of select="dig:related_documents/dig:document_id"/>
                        </dig:document_id>
                        <dig:serie>
                           <xsl:value-of select="dig:related_documents/dig:serie"/>
                        </dig:serie>
                        <dig:folio>
                           <xsl:value-of select="dig:related_documents/dig:folio"/>
                        </dig:folio>
                        <dig:currency>
                           <xsl:value-of select="dig:related_documents/dig:currency"/>
                        </dig:currency>
                        <dig:currency_exchange>
                           <xsl:value-of select="dig:related_documents/dig:currency_exchange"/>
                        </dig:currency_exchange>
                        <dig:payment_method>
                           <xsl:value-of select="dig:related_documents/dig:payment_method"/>
                        </dig:payment_method>
                        <dig:partiality_number>
                           <xsl:value-of select="dig:related_documents/dig:partiality_number"/>
                        </dig:partiality_number>
                        <dig:previous_balance>
                           <xsl:value-of select="dig:related_documents/dig:previous_balance"/>
                        </dig:previous_balance>
                        <dig:paid_amount>
                           <xsl:value-of select="dig:related_documents/dig:paid_amount"/>
                        </dig:paid_amount>
                        <dig:outstanding_balance>
                           <xsl:value-of select="dig:related_documents/dig:outstanding_balance"/>
                        </dig:outstanding_balance>
                     </dig:related_documents>
                  </dig:payment_complements>
               </xsl:for-each>
               <xsl:if test="/dig:invoice/dig:service">
                  <dig:service>
                     <xsl:value-of select="/dig:invoice/dig:service"/>
                  </dig:service>
               </xsl:if>
            </dig:invoiceRs>
         </dig:Return>
      </dig:createTrxCFDIRs>
   </xsl:template>
</xsl:stylesheet>