<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://soa.estrellaroja.com.mx/ValidacionAutomaticaConsulta" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://soa.estrellaroja.com.mx/ValidacionAutomaticTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/ValidacionAutomaticaConsulta.xsd"/>
            <oracle-xsl-mapper:rootElement name="PostValidationOracleXmlResponse" namespace="http://soa.estrellaroja.com.mx/ValidacionAutomaticaConsulta"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ValidacionAutomaticTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="ValidationOracleXmlResponse" namespace="http://soa.estrellaroja.com.mx/ValidacionAutomaticTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED JUL 21 17:18:25 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ValidationOracleXmlResponse>
         <tns:success>
            <xsl:value-of select="/ns0:PostValidationOracleXmlResponse/ns0:success"/>
         </tns:success>
         <tns:message>
            <xsl:value-of select="/ns0:PostValidationOracleXmlResponse/ns0:message"/>
         </tns:message>
         <tns:log>
                     <xsl:value-of select="/ns0:PostValidationOracleXmlResponse/ns0:log"/>
        </tns:log>

         <tns:mustCancel>
            <xsl:value-of select="/ns0:PostValidationOracleXmlResponse/ns0:mustCancel"/>
         </tns:mustCancel>
         <tns:mustModify>
            <xsl:value-of select="/ns0:PostValidationOracleXmlResponse/ns0:mustModify"/>
         </tns:mustModify>
         <tns:emailSendedToSupplier>
            <xsl:value-of select="/ns0:PostValidationOracleXmlResponse/ns0:emailSendedToSupplier"/>
         </tns:emailSendedToSupplier>
         <tns:invoiceId>
            <xsl:value-of select="/ns0:PostValidationOracleXmlResponse/ns0:invoiceId"/>
         </tns:invoiceId>
         <tns:supplierEmail>
            <xsl:value-of select="/ns0:PostValidationOracleXmlResponse/ns0:supplierEmail"/>
         </tns:supplierEmail>
         <tns:oracleLookupCode>
            <xsl:value-of select="/ns0:PostValidationOracleXmlResponse/ns0:oracleLookupCode"/>
         </tns:oracleLookupCode>
         <tns:Return>
            <cmn:Success/>
         </tns:Return>
      </tns:ValidationOracleXmlResponse>
   </xsl:template>
</xsl:stylesheet>