<wsdl:definitions name="EAMErrorRecord" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_ESTRELLA_ROJA/DEV_EAMUnitMetricsTec/EAMErrorRecord" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_ESTRELLA_ROJA/DEV_EAMUnitMetricsTec/EAMErrorRecord" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EAMErrorRecord" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plt:partnerLinkType name="EAMErrorRecord_plt">
    <plt:role name="EAMErrorRecord_role">
      <plt:portType name="tns:EAMErrorRecord_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EAMErrorRecord" schemaLocation="../../XSD/ErrorRecord/EAMErrorRecordXSD.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="XxerEamErrorLogCollection_msg">
        <wsdl:part name="XxerEamErrorLogCollection" element="top:XxerEamErrorLogCollection"/>
    </wsdl:message>
    <wsdl:portType name="EAMErrorRecord_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:XxerEamErrorLogCollection_msg"/>
            <wsdl:output message="tns:XxerEamErrorLogCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="EAMErrorRecord_pttSOAP11Binding" type="tns:EAMErrorRecord_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="merge">
            <soap:operation style="document" soapAction="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_ESTRELLA_ROJA/DEV_EAMUnitMetricsTec/EAMErrorRecord/merge"/>
            <wsdl:input>
                <soap:body use="literal" parts="XxerEamErrorLogCollection"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="XxerEamErrorLogCollection"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>