<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbaGetReceiptOrInvoicesBs" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://soa.estrellaroja.com.mx/FinancialsTec" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/dbaGetReceiptOrInvoicesBs_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbaGetReceiptOrInvoicesBs"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/FinancialsTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetReceiptOrInvoicesRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 21 17:29:18 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetReceiptOrInvoicesRs>
         <xsl:if test="true ( )">
            <cmn:Success/>
         </xsl:if>
         <tns:Return>
            <xsl:if test="/ns0:OutputParameters/ns0:P_RECEIPT">
               <xsl:for-each select="/ns0:OutputParameters/ns0:P_RECEIPT/ns0:P_RECEIPT_ITEM">
                  <tns:Receipt>
                     <xsl:if test="/ns0:OutputParameters/ns0:P_RECEIPT/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECEIPT/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:if test="ns0:RFC">
                        <tns:RFC>
                           <xsl:value-of select="ns0:RFC"/>
                        </tns:RFC>
                     </xsl:if>
                     <xsl:if test="ns0:AMOUNT">
                        <tns:Amount>
                           <xsl:value-of select="ns0:AMOUNT"/>
                        </tns:Amount>
                     </xsl:if>
                     <xsl:if test="ns0:SITE_USE_ID">
                        <tns:SiteUseId>
                           <xsl:value-of select="ns0:SITE_USE_ID"/>
                        </tns:SiteUseId>
                     </xsl:if>
                     <xsl:if test="ns0:DEPOSIT_DATE">
                        <tns:DepositDate>
                           <xsl:value-of select="ns0:DEPOSIT_DATE"/>
                        </tns:DepositDate>
                     </xsl:if>
                     <xsl:if test="ns0:CUST_ACCOUNT_ID">
                        <tns:CustAccountId>
                           <xsl:value-of select="ns0:CUST_ACCOUNT_ID"/>
                        </tns:CustAccountId>
                     </xsl:if>
                     <xsl:if test="ns0:RECEIPT_DATE">
                        <tns:ReceiptDate>
                           <xsl:value-of select="ns0:RECEIPT_DATE"/>
                        </tns:ReceiptDate>
                     </xsl:if>
                     <xsl:if test="ns0:RECEIPT_METHOD_ID">
                        <tns:ReceiptMethodId>
                           <xsl:value-of select="ns0:RECEIPT_METHOD_ID"/>
                        </tns:ReceiptMethodId>
                     </xsl:if>
                     <xsl:if test="ns0:RECEIPT_NUMBER">
                        <tns:ReceiptNumber>
                           <xsl:value-of select="ns0:RECEIPT_NUMBER"/>
                        </tns:ReceiptNumber>
                     </xsl:if>
                     <xsl:if test="ns0:CASH_RECEIPT_ID">
                        <tns:CashReceiptId>
                           <xsl:value-of select="ns0:CASH_RECEIPT_ID"/>
                        </tns:CashReceiptId>
                     </xsl:if>
                     <xsl:if test="ns0:ORGANIZATION_ID">
                        <tns:OrganizationId>
                           <xsl:value-of select="ns0:ORGANIZATION_ID"/>
                        </tns:OrganizationId>
                     </xsl:if>
                     <xsl:if test="ns0:TABLA_PUENTE_ID">
                        <tns:TablaPuenteId>
                           <xsl:value-of select="ns0:TABLA_PUENTE_ID"/>
                        </tns:TablaPuenteId>
                     </xsl:if>
                  </tns:Receipt>
               </xsl:for-each>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_INVOICE">
               <tns:Invoices>
                  <xsl:for-each select="/ns0:OutputParameters/ns0:P_INVOICE/ns0:P_INVOICE_ITEM">
                     <tns:Invoice>
                        <xsl:if test="@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:RFC">
                           <tns:RFC>
                              <xsl:if test="ns0:RFC/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:RFC/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:RFC"/>
                           </tns:RFC>
                        </xsl:if>
                        <xsl:if test="ns0:BUSINESS_UNIT_NAME">
                           <tns:BusinessUnitName>
                              <xsl:value-of select="ns0:BUSINESS_UNIT_NAME"/>
                           </tns:BusinessUnitName>
                        </xsl:if>
                        <tns:TransactionBatchSourceName>
                           <xsl:value-of select="ns0:TRANS_BATCH_SOURCE_NAME"/>
                        </tns:TransactionBatchSourceName>
                        <tns:TransactionTypeName>
                           <xsl:value-of select="ns0:TRANSACTION_TYPE_NAME"/>
                        </tns:TransactionTypeName>
                        <tns:PaymentTerms>
                           <xsl:value-of select="ns0:PAYMENT_TERMS"/>
                        </tns:PaymentTerms>
                        <tns:TransactionDate>
                           <xsl:value-of select="ns0:TRANSACTION_DATE"/>
                        </tns:TransactionDate>
                        <tns:AccountingDate>
                           <xsl:value-of select="ns0:ACCOUNTING_DATE"/>
                        </tns:AccountingDate>
                        <tns:TransactionNumber>
                           <xsl:value-of select="ns0:TRANSACTION_NUMBER"/>
                        </tns:TransactionNumber>
                        <tns:OriginalSystemBillToCustomerRef>
                           <xsl:value-of select="ns0:ORIG_SYS_BILL_TO_CST_REF"/>
                        </tns:OriginalSystemBillToCustomerRef>
                        <tns:OriginalSystemBillToCustomerAddressRef>
                           <xsl:value-of select="ns0:ORIG_SYS_BILL_TO_CST_AD_REF"/>
                        </tns:OriginalSystemBillToCustomerAddressRef>
                        <tns:OriginalSystemBillToCustomerContactRef>
                           <xsl:value-of select="ns0:ORIG_SYS_BILL_TO_CST_CO_REF"/>
                        </tns:OriginalSystemBillToCustomerContactRef>
                        <tns:OriginalSystemShipToCustomerRef>
                           <xsl:value-of select="ns0:ORIG_SYS_SHIP_TO_CST_REF"/>
                        </tns:OriginalSystemShipToCustomerRef>
                        <tns:OriginalSystemShipToCustomerAddressRef>
                           <xsl:value-of select="ns0:ORIG_SYS_SHIP_TO_CST_AD_REF"/>
                        </tns:OriginalSystemShipToCustomerAddressRef>
                        <tns:OriginalSystemShipToCustomerContactRef>
                           <xsl:value-of select="ns0:ORIG_SYS_SHIP_TO_CST_CO_REF"/>
                        </tns:OriginalSystemShipToCustomerContactRef>
                        <tns:OriginalSystemShipToCustomerAccountRef>
                           <xsl:value-of select="ns0:ORIG_SYS_SHP_TO_CST_ACC_REF"/>
                        </tns:OriginalSystemShipToCustomerAccountRef>
                        <tns:OriginalSystemShipToCustomerAccountAddressRef>
                           <xsl:value-of select="ns0:ORI_SYS_SHP_TO_CST_AC_AD_REF"/>
                        </tns:OriginalSystemShipToCustomerAccountAddressRef>
                        <tns:OriginalSystemShipToCustomerAccountContactRef>
                           <xsl:value-of select="ns0:ORI_SYS_SHP_TO_CST_AC_CO_RF"/>
                        </tns:OriginalSystemShipToCustomerAccountContactRef>
                        <tns:OriginalSystemSoldToCustomerRef>
                           <xsl:value-of select="ns0:ORIG_SYS_SOLD_TO_CST_REF"/>
                        </tns:OriginalSystemSoldToCustomerRef>
                        <tns:OriginalSystemSoldToCustomerAccountRef>
                           <xsl:value-of select="ns0:ORIG_SYS_SOLD_TO_CST_ACC_RF"/>
                        </tns:OriginalSystemSoldToCustomerAccountRef>
                        <tns:BillToCustomerAccountNumber>
                           <xsl:value-of select="ns0:BILL_TO_CUST_ACCOUNT_NMBR"/>
                        </tns:BillToCustomerAccountNumber>
                        <tns:BillToCustomerSiteNumber>
                           <xsl:value-of select="ns0:BILL_TO_CUSTOMER_SITE_NMBR"/>
                        </tns:BillToCustomerSiteNumber>
                        <tns:BillToContactPartyNumber>
                           <xsl:value-of select="ns0:BILL_TO_CONTACT_PARTY_NMBR"/>
                        </tns:BillToContactPartyNumber>
                        <tns:ShipToCustomerAccountNumber>
                           <xsl:value-of select="ns0:SHIP_TO_CUST_ACCOUNT_NMBR"/>
                        </tns:ShipToCustomerAccountNumber>
                        <tns:ShipToCustomerSiteNumber>
                           <xsl:value-of select="ns0:SHIP_TO_CUSTOMER_SITE_NMBR"/>
                        </tns:ShipToCustomerSiteNumber>
                        <tns:ShipToContactPartyNumber>
                           <xsl:value-of select="ns0:SHIP_TO_CONTACT_PARTY_NMBR"/>
                        </tns:ShipToContactPartyNumber>
                        <tns:SoldToCustomerAccountNumber>
                           <xsl:value-of select="ns0:SOLD_TO_CUST_ACCOUNT_NMBR"/>
                        </tns:SoldToCustomerAccountNumber>
                        <tns:TransactionLineType>
                           <xsl:value-of select="ns0:TRANSACTION_LINE_TYPE"/>
                        </tns:TransactionLineType>
                        <tns:TransactionLineDescription>
                           <xsl:value-of select="ns0:TRANSACTION_LINE_DESC"/>
                        </tns:TransactionLineDescription>
                        <tns:CurrencyCode>
                           <xsl:value-of select="ns0:CURRENCY_CODE"/>
                        </tns:CurrencyCode>
                        <tns:CurrencyConversionType>
                           <xsl:value-of select="ns0:CURRENCY_CONVERSION_TYPE"/>
                        </tns:CurrencyConversionType>
                        <tns:CurrencyConversionDate>
                           <xsl:value-of select="ns0:CURRENCY_CONVERSION_DATE"/>
                        </tns:CurrencyConversionDate>
                        <tns:CurrencyConversionRate>
                           <xsl:value-of select="ns0:CURRENCY_CONVERSION_RATE"/>
                        </tns:CurrencyConversionRate>
                        <tns:TransactionLineAmount>
                           <xsl:value-of select="ns0:TRANSACTION_LINE_AMOUNT"/>
                        </tns:TransactionLineAmount>
                        <tns:TransactionLineQuantity>
                           <xsl:value-of select="ns0:TRANSACTION_LINE_QUANTITY"/>
                        </tns:TransactionLineQuantity>
                        <tns:CustomerOrderedQuantity>
                           <xsl:value-of select="ns0:CUSTOMER_ORDERED_QUANTITY"/>
                        </tns:CustomerOrderedQuantity>
                        <tns:UnitSellingPrice>
                           <xsl:value-of select="ns0:UNIT_SELLING_PRICE"/>
                        </tns:UnitSellingPrice>
                        <tns:UnitStandarPrice>
                           <xsl:value-of select="ns0:UNIT_STANDARD_PRICE"/>
                        </tns:UnitStandarPrice>
                        <tns:LineTransactionsFlexfiledContext>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_CONTEXT"/>
                        </tns:LineTransactionsFlexfiledContext>
                        <tns:LineTransactionsFlexfiledSegment1>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_1"/>
                        </tns:LineTransactionsFlexfiledSegment1>
                        <tns:LineTransactionsFlexfiledSegment2>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_2"/>
                        </tns:LineTransactionsFlexfiledSegment2>
                        <tns:LineTransactionsFlexfiledSegment3>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_3"/>
                        </tns:LineTransactionsFlexfiledSegment3>
                        <tns:LineTransactionsFlexfiledSegment4>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_4"/>
                        </tns:LineTransactionsFlexfiledSegment4>
                        <tns:LineTransactionsFlexfiledSegment5>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_5"/>
                        </tns:LineTransactionsFlexfiledSegment5>
                        <tns:LineTransactionsFlexfiledSegment6>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_6"/>
                        </tns:LineTransactionsFlexfiledSegment6>
                        <tns:LineTransactionsFlexfiledSegment7>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_7"/>
                        </tns:LineTransactionsFlexfiledSegment7>
                        <tns:LineTransactionsFlexfiledSegment8>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_8"/>
                        </tns:LineTransactionsFlexfiledSegment8>
                        <tns:LineTransactionsFlexfiledSegment9>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_9"/>
                        </tns:LineTransactionsFlexfiledSegment9>
                        <tns:LineTransactionsFlexfiledSegment10>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_10"/>
                        </tns:LineTransactionsFlexfiledSegment10>
                        <tns:LineTransactionsFlexfiledSegment11>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_11"/>
                        </tns:LineTransactionsFlexfiledSegment11>
                        <tns:LineTransactionsFlexfiledSegment12>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_12"/>
                        </tns:LineTransactionsFlexfiledSegment12>
                        <tns:LineTransactionsFlexfiledSegment13>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_13"/>
                        </tns:LineTransactionsFlexfiledSegment13>
                        <tns:LineTransactionsFlexfiledSegment14>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_14"/>
                        </tns:LineTransactionsFlexfiledSegment14>
                        <tns:LineTransactionsFlexfiledSegment15>
                           <xsl:value-of select="ns0:LINE_TRANS_FLXFLD_SGMNT_15"/>
                        </tns:LineTransactionsFlexfiledSegment15>
                        <tns:PrimarySalesPersonNumber>
                           <xsl:value-of select="ns0:PRIMARY_SALESPERSON_NUMBER"/>
                        </tns:PrimarySalesPersonNumber>
                        <tns:TaxCassificationCode>
                           <xsl:value-of select="ns0:TAX_CLASSIFICATION_CODE"/>
                        </tns:TaxCassificationCode>
                        <tns:LegalEntityIdentifier>
                           <xsl:value-of select="ns0:LEGAL_ENTITY_IDENTIFIER"/>
                        </tns:LegalEntityIdentifier>
                        <tns:AccountedAmountInLedgerCurrency>
                           <xsl:value-of select="ns0:ACCD_AMOUNT_IN_LED_CRRNCY"/>
                        </tns:AccountedAmountInLedgerCurrency>
                        <tns:SalesOrderNumber>
                           <xsl:value-of select="ns0:SALES_ORDER_NUMBER"/>
                        </tns:SalesOrderNumber>
                        <tns:SalesOrderDate>
                           <xsl:value-of select="ns0:SALES_ORDER_DATE"/>
                        </tns:SalesOrderDate>
                        <tns:ActualShipDate>
                           <xsl:value-of select="ns0:ACTUAL_SHIP_DATE"/>
                        </tns:ActualShipDate>
                        <tns:WarehouseCode>
                           <xsl:value-of select="ns0:WAREHOUSE_CODE"/>
                        </tns:WarehouseCode>
                        <tns:UnitOfMeasureCode>
                           <xsl:value-of select="ns0:UNIT_OF_MEASURE_CODE"/>
                        </tns:UnitOfMeasureCode>
                        <tns:UnitOfMeasureName>
                           <xsl:value-of select="ns0:UNIT_OF_MEASURE_NAME"/>
                        </tns:UnitOfMeasureName>
                        <tns:InvoicingRuleName>
                           <xsl:value-of select="ns0:INVOICING_RULE_NAME"/>
                        </tns:InvoicingRuleName>
                        <tns:RevenueSchedulingRuleName>
                           <xsl:value-of select="ns0:REVE_SCHEDULING_RULE_NAME"/>
                        </tns:RevenueSchedulingRuleName>
                        <tns:NumberOfRevenuePeriods>
                           <xsl:value-of select="ns0:NUMBER_OF_REVENUE_PERIODS"/>
                        </tns:NumberOfRevenuePeriods>
                        <tns:RevenueSchedulingRuleStartDate>
                           <xsl:value-of select="ns0:REV_SCHDLNG_RULE_START_DATE"/>
                        </tns:RevenueSchedulingRuleStartDate>
                        <tns:RevenueSchedulingRuleEndDate>
                           <xsl:value-of select="ns0:REV_SCHDLNG_RULE_END_DATE"/>
                        </tns:RevenueSchedulingRuleEndDate>
                        <tns:ReasonCodeMeaning>
                           <xsl:value-of select="ns0:REASON_CODE_MEANING"/>
                        </tns:ReasonCodeMeaning>
                        <tns:LastPeriodToCredit>
                           <xsl:value-of select="ns0:LAST_PERIOD_TO_CREDIT"/>
                        </tns:LastPeriodToCredit>
                        <tns:TransactionBusinessCategoryCode>
                           <xsl:value-of select="ns0:TRANS_BISS_CATEGORY_CODE"/>
                        </tns:TransactionBusinessCategoryCode>
                        <tns:ProductFiscalClassicationCode>
                           <xsl:value-of select="ns0:PROD_FISC_CLASSIFICTN_CODE"/>
                        </tns:ProductFiscalClassicationCode>
                        <tns:ProductCategoryCode>
                           <xsl:value-of select="ns0:PRODUCT_CATEGORY_CODE"/>
                        </tns:ProductCategoryCode>
                        <tns:ProductType>
                           <xsl:value-of select="ns0:PRODUCT_TYPE"/>
                        </tns:ProductType>
                        <tns:LineIntendedUseCode>
                           <xsl:value-of select="ns0:LINE_INTENDED_USE_CODE"/>
                        </tns:LineIntendedUseCode>
                        <tns:AssessableValue>
                           <xsl:value-of select="ns0:ASSESSABLE_VALUE"/>
                        </tns:AssessableValue>
                        <tns:DocumentSubType>
                           <xsl:value-of select="ns0:DOCUMENT_SUB_TYPE"/>
                        </tns:DocumentSubType>
                        <tns:DefaultTaxationCountry>
                           <xsl:value-of select="ns0:DOCUMENT_SUB_TYPE"/>
                        </tns:DefaultTaxationCountry>
                        <tns:UserDefinedFiscalClassification>
                           <xsl:value-of select="ns0:USER_DEFND_FISC_CLASSIFICTN"/>
                        </tns:UserDefinedFiscalClassification>
                        <tns:TaxInvoiceNumber>
                           <xsl:value-of select="ns0:TAX_INVOICE_NUMBER"/>
                        </tns:TaxInvoiceNumber>
                        <tns:TaxInvoiceDate>
                           <xsl:value-of select="ns0:TAX_INVOICE_DATE"/>
                        </tns:TaxInvoiceDate>
                        <tns:TaxRegimeCode>
                           <xsl:value-of select="ns0:TAX_REGIME_CODE"/>
                        </tns:TaxRegimeCode>
                        <tns:TAX>
                           <xsl:value-of select="ns0:TAX"/>
                        </tns:TAX>
                        <tns:TaxStatusCode>
                           <xsl:value-of select="ns0:TAX_STATUS_CODE"/>
                        </tns:TaxStatusCode>
                        <tns:TaxRateCode>
                           <xsl:value-of select="ns0:TAX_RATE_CODE"/>
                        </tns:TaxRateCode>
                        <tns:TaxJuridictionCode>
                           <xsl:value-of select="ns0:TAX_JURISDICTION_CODE"/>
                        </tns:TaxJuridictionCode>
                        <tns:FirstPartyRegistrationNumber>
                           <xsl:value-of select="ns0:FIRST_PARTY_REGISTRATN_NMBR"/>
                        </tns:FirstPartyRegistrationNumber>
                        <tns:ThirdPartyRegistrationNumber>
                           <xsl:value-of select="ns0:THIRD_PARTY_REGISTRATN_NMBR"/>
                        </tns:ThirdPartyRegistrationNumber>
                        <tns:FinalDischargeLocation>
                           <xsl:value-of select="ns0:FINAL_DISCHARGE_LOCATION"/>
                        </tns:FinalDischargeLocation>
                        <tns:TaxableAmount>
                           <xsl:value-of select="ns0:TAXABLE_AMOUNT"/>
                        </tns:TaxableAmount>
                        <tns:TaxableFlag>
                           <xsl:value-of select="ns0:TAXABLE_FLAG"/>
                        </tns:TaxableFlag>
                        <tns:TaxExemptionFlag>
                           <xsl:value-of select="ns0:TAX_EXEMPTION_FLAG"/>
                        </tns:TaxExemptionFlag>
                        <tns:TaxExemptionReasonCode>
                           <xsl:value-of select="ns0:TAX_EXEMPTION_REASON_CODE"/>
                        </tns:TaxExemptionReasonCode>
                        <tns:TaxExemptionReasonCodeMeaning>
                           <xsl:value-of select="ns0:TAX_EXEMPTN_RSON_CODE_MNG"/>
                        </tns:TaxExemptionReasonCodeMeaning>
                        <tns:TaxExemptionCertificateNumber>
                           <xsl:value-of select="ns0:TAX_EXEMPTN_CERTIFICT_NMBR"/>
                        </tns:TaxExemptionCertificateNumber>
                        <tns:LineAmountIncludes_TaxFlag>
                           <xsl:value-of select="ns0:LINE_AMOUNT_INCLDS_TAX_FLAG"/>
                        </tns:LineAmountIncludes_TaxFlag>
                        <tns:TaxPrecedent>
                           <xsl:value-of select="ns0:TAX_PRECEDENCE"/>
                        </tns:TaxPrecedent>
                        <tns:CreditMethodToBeUserForLinesWithRevenueSchedulingRules>
                           <xsl:value-of select="ns0:CR_MT_2B_US_4_LS_WT_RV_SC_RS"/>
                        </tns:CreditMethodToBeUserForLinesWithRevenueSchedulingRules>
                        <tns:CreditMethodToBeUserForTransactionsWithSpritPaymentTerms>
                           <xsl:value-of select="ns0:CR_MT_2B_US_4_TR_WT_SP_PY_TR"/>
                        </tns:CreditMethodToBeUserForTransactionsWithSpritPaymentTerms>
                        <tns:ReasonCode>
                           <xsl:value-of select="ns0:REASON_CODE"/>
                        </tns:ReasonCode>
                        <tns:TaxRate>
                           <xsl:value-of select="ns0:TAX_RATE"/>
                        </tns:TaxRate>
                        <tns:FobPoint>
                           <xsl:value-of select="ns0:FOB_POINT"/>
                        </tns:FobPoint>
                        <tns:Carrier>
                           <xsl:value-of select="ns0:CARRIER"/>
                        </tns:Carrier>
                        <tns:ShippingReference>
                           <xsl:value-of select="ns0:SHIPPING_REFERENCE"/>
                        </tns:ShippingReference>
                        <tns:SalesOrderLineNumber>
                           <xsl:value-of select="ns0:SALES_ORDER_LINE_NUMBER"/>
                        </tns:SalesOrderLineNumber>
                        <tns:SalesOrderSource>
                           <xsl:value-of select="ns0:SALES_ORDER_SOURCE"/>
                        </tns:SalesOrderSource>
                        <tns:SalesOrderRevisionNumber>
                           <xsl:value-of select="ns0:SALES_ORDER_REVISION_NUMBER"/>
                        </tns:SalesOrderRevisionNumber>
                        <tns:PurchaseOrderNumber>
                           <xsl:value-of select="ns0:PURCHASE_ORDER_NUMBER"/>
                        </tns:PurchaseOrderNumber>
                        <tns:PurchaseOrder_RevisionNumber>
                           <xsl:value-of select="ns0:PURCHASE_ORDER_REVSN_NMBR"/>
                        </tns:PurchaseOrder_RevisionNumber>
                        <tns:PurchaseOrderDate>
                           <xsl:value-of select="ns0:PURCHASE_ORDER_DATE"/>
                        </tns:PurchaseOrderDate>
                        <tns:AgreementName>
                           <xsl:value-of select="ns0:AGREEMENT_NAME"/>
                        </tns:AgreementName>
                        <tns:MemoLineName>
                           <xsl:value-of select="ns0:MEMO_LINE_NAME"/>
                        </tns:MemoLineName>
                        <tns:DocumentNumber>
                           <xsl:value-of select="ns0:DOCUMENT_NUMBER"/>
                        </tns:DocumentNumber>
                        <tns:OriginalSystemBatchName>
                           <xsl:value-of select="ns0:ORIGINAL_SYSTEM_BATCH_NAME"/>
                        </tns:OriginalSystemBatchName>
                        <tns:LinkToTransactionsFlexfieldContext>
                           <xsl:value-of select="ns0:LINK_TO_TRANS_FLXFLD_CNTXT"/>
                        </tns:LinkToTransactionsFlexfieldContext>
                        <tns:LinkToTransactionsFlexfieldSegment1>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_1"/>
                        </tns:LinkToTransactionsFlexfieldSegment1>
                        <tns:LinkToTransactionsFlexfieldSegment2>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_2"/>
                        </tns:LinkToTransactionsFlexfieldSegment2>
                        <tns:LinkToTransactionsFlexfieldSegment3>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_3"/>
                        </tns:LinkToTransactionsFlexfieldSegment3>
                        <tns:LinkToTransactionsFlexfieldSegment4>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_4"/>
                        </tns:LinkToTransactionsFlexfieldSegment4>
                        <tns:LinkToTransactionsFlexfieldSegment5>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_5"/>
                        </tns:LinkToTransactionsFlexfieldSegment5>
                        <tns:LinkToTransactionsFlexfieldSegment6>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_6"/>
                        </tns:LinkToTransactionsFlexfieldSegment6>
                        <tns:LinkToTransactionsFlexfieldSegment7>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_7"/>
                        </tns:LinkToTransactionsFlexfieldSegment7>
                        <tns:LinkToTransactionsFlexfieldSegment8>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_8"/>
                        </tns:LinkToTransactionsFlexfieldSegment8>
                        <tns:LinkToTransactionsFlexfieldSegment9>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_9"/>
                        </tns:LinkToTransactionsFlexfieldSegment9>
                        <tns:LinkToTransactionsFlexfieldSegment10>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_10"/>
                        </tns:LinkToTransactionsFlexfieldSegment10>
                        <tns:LinkToTransactionsFlexfieldSegment11>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_11"/>
                        </tns:LinkToTransactionsFlexfieldSegment11>
                        <tns:LinkToTransactionsFlexfieldSegment12>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_12"/>
                        </tns:LinkToTransactionsFlexfieldSegment12>
                        <tns:LinkToTransactionsFlexfieldSegment13>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_13"/>
                        </tns:LinkToTransactionsFlexfieldSegment13>
                        <tns:LinkToTransactionsFlexfieldSegment14>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_14"/>
                        </tns:LinkToTransactionsFlexfieldSegment14>
                        <tns:LinkToTransactionsFlexfieldSegment15>
                           <xsl:value-of select="ns0:LNK_TO_TRANS_FLXFLD_SGMNT_15"/>
                        </tns:LinkToTransactionsFlexfieldSegment15>
                        <tns:ReferenceTransationsFlexfieldContext>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_CNTXT"/>
                        </tns:ReferenceTransationsFlexfieldContext>
                        <tns:ReferenceTransationsFlexfieldSegment1>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_1"/>
                        </tns:ReferenceTransationsFlexfieldSegment1>
                        <tns:ReferenceTransationsFlexfieldSegment2>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_2"/>
                        </tns:ReferenceTransationsFlexfieldSegment2>
                        <tns:ReferenceTransationsFlexfieldSegment3>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_3"/>
                        </tns:ReferenceTransationsFlexfieldSegment3>
                        <tns:ReferenceTransationsFlexfieldSegment4>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_4"/>
                        </tns:ReferenceTransationsFlexfieldSegment4>
                        <tns:ReferenceTransationsFlexfieldSegment5>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_5"/>
                        </tns:ReferenceTransationsFlexfieldSegment5>
                        <tns:ReferenceTransationsFlexfieldSegment6>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_6"/>
                        </tns:ReferenceTransationsFlexfieldSegment6>
                        <tns:ReferenceTransationsFlexfieldSegment7>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_7"/>
                        </tns:ReferenceTransationsFlexfieldSegment7>
                        <tns:ReferenceTransationsFlexfieldSegment8>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_8"/>
                        </tns:ReferenceTransationsFlexfieldSegment8>
                        <tns:ReferenceTransationsFlexfieldSegment9>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_9"/>
                        </tns:ReferenceTransationsFlexfieldSegment9>
                        <tns:ReferenceTransationsFlexfieldSegment10>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_10"/>
                        </tns:ReferenceTransationsFlexfieldSegment10>
                        <tns:ReferenceTransationsFlexfieldSegment11>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_11"/>
                        </tns:ReferenceTransationsFlexfieldSegment11>
                        <tns:ReferenceTransationsFlexfieldSegment12>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_12"/>
                        </tns:ReferenceTransationsFlexfieldSegment12>
                        <tns:ReferenceTransationsFlexfieldSegment13>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_13"/>
                        </tns:ReferenceTransationsFlexfieldSegment13>
                        <tns:ReferenceTransationsFlexfieldSegment14>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_14"/>
                        </tns:ReferenceTransationsFlexfieldSegment14>
                        <tns:ReferenceTransationsFlexfieldSegment15>
                           <xsl:value-of select="ns0:REF_TRANS_FLXFLD_SGMNT_15"/>
                        </tns:ReferenceTransationsFlexfieldSegment15>
                        <tns:LinkToParentLineContext>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_CONTEXT"/>
                        </tns:LinkToParentLineContext>
                        <tns:LinkToParentLineSegment1>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_1"/>
                        </tns:LinkToParentLineSegment1>
                        <tns:LinkToParentLineSegment2>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_2"/>
                        </tns:LinkToParentLineSegment2>
                        <tns:LinkToParentLineSegment3>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_3"/>
                        </tns:LinkToParentLineSegment3>
                        <tns:LinkToParentLineSegment4>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_4"/>
                        </tns:LinkToParentLineSegment4>
                        <tns:LinkToParentLineSegment5>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_5"/>
                        </tns:LinkToParentLineSegment5>
                        <tns:LinkToParentLineSegment6>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_6"/>
                        </tns:LinkToParentLineSegment6>
                        <tns:LinkToParentLineSegment7>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_7"/>
                        </tns:LinkToParentLineSegment7>
                        <tns:LinkToParentLineSegment8>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_8"/>
                        </tns:LinkToParentLineSegment8>
                        <tns:LinkToParentLineSegment9>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_9"/>
                        </tns:LinkToParentLineSegment9>
                        <tns:LinkToParentLineSegment10>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_10"/>
                        </tns:LinkToParentLineSegment10>
                        <tns:LinkToParentLineSegment11>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_11"/>
                        </tns:LinkToParentLineSegment11>
                        <tns:LinkToParentLineSegment12>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_12"/>
                        </tns:LinkToParentLineSegment12>
                        <tns:LinkToParentLineSegment13>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_13"/>
                        </tns:LinkToParentLineSegment13>
                        <tns:LinkToParentLineSegment14>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_14"/>
                        </tns:LinkToParentLineSegment14>
                        <tns:LinkToParentLineSegment15>
                           <xsl:value-of select="ns0:LNK_TO_PARENT_LINE_SGMNT_15"/>
                        </tns:LinkToParentLineSegment15>
                        <tns:ReceiptMethodName>
                           <xsl:value-of select="ns0:RECEIPT_METHOD_NAME"/>
                        </tns:ReceiptMethodName>
                        <tns:PrintingOption>
                           <xsl:value-of select="ns0:PRINTING_OPTION"/>
                        </tns:PrintingOption>
                        <tns:RelatedBatchSourceName>
                           <xsl:value-of select="ns0:RELATED_BATCH_SOURCE_NAME"/>
                        </tns:RelatedBatchSourceName>
                        <tns:RelatedTransactionNumber>
                           <xsl:value-of select="ns0:RELATED_TRANSACTION_NUMBER"/>
                        </tns:RelatedTransactionNumber>
                        <tns:InventoryItemNumber>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_NUMBER"/>
                        </tns:InventoryItemNumber>
                        <tns:InventoryItemSegment2>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_2"/>
                        </tns:InventoryItemSegment2>
                        <tns:InventoryItemSegment3>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_3"/>
                        </tns:InventoryItemSegment3>
                        <tns:InventoryItemSegment4>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_4"/>
                        </tns:InventoryItemSegment4>
                        <tns:InventoryItemSegment5>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_5"/>
                        </tns:InventoryItemSegment5>
                        <tns:InventoryItemSegment6>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_6"/>
                        </tns:InventoryItemSegment6>
                        <tns:InventoryItemSegment7>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_7"/>
                        </tns:InventoryItemSegment7>
                        <tns:InventoryItemSegment8>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_8"/>
                        </tns:InventoryItemSegment8>
                        <tns:InventoryItemSegment9>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_9"/>
                        </tns:InventoryItemSegment9>
                        <tns:InventoryItemSegment10>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_10"/>
                        </tns:InventoryItemSegment10>
                        <tns:InventoryItemSegment11>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_11"/>
                        </tns:InventoryItemSegment11>
                        <tns:InventoryItemSegment12>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_12"/>
                        </tns:InventoryItemSegment12>
                        <tns:InventoryItemSegment13>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_13"/>
                        </tns:InventoryItemSegment13>
                        <tns:InventoryItemSegment14>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_14"/>
                        </tns:InventoryItemSegment14>
                        <tns:InventoryItemSegment15>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_15"/>
                        </tns:InventoryItemSegment15>
                        <tns:InventoryItemSegment16>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_16"/>
                        </tns:InventoryItemSegment16>
                        <tns:InventoryItemSegment17>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_17"/>
                        </tns:InventoryItemSegment17>
                        <tns:InventoryItemSegment18>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_18"/>
                        </tns:InventoryItemSegment18>
                        <tns:InventoryItemSegment19>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_19"/>
                        </tns:InventoryItemSegment19>
                        <tns:InventoryItemSegment20>
                           <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_20"/>
                        </tns:InventoryItemSegment20>
                        <tns:BillToCustomerBankAccountName>
                           <xsl:value-of select="ns0:BILL_TO_CUST_BANK_ACC_NAME"/>
                        </tns:BillToCustomerBankAccountName>
                        <tns:ResetTransactionDateFlag>
                           <xsl:value-of select="ns0:RESET_TRANSACTION_DATE_FLAG"/>
                        </tns:ResetTransactionDateFlag>
                        <tns:PaymentServerOrderNumber>
                           <xsl:value-of select="ns0:PAYMENT_SERVER_ORDER_NUMBER"/>
                        </tns:PaymentServerOrderNumber>
                        <tns:LastTransactionOnDebitAuthorization>
                           <xsl:value-of select="ns0:LAST_TRANS_ON_DEBIT_AUTZTN"/>
                        </tns:LastTransactionOnDebitAuthorization>
                        <tns:ApprovalCode>
                           <xsl:value-of select="ns0:APPROVAL_CODE"/>
                        </tns:ApprovalCode>
                        <tns:AddressVerificationCode>
                           <xsl:value-of select="ns0:ADDRESS_VERIFICATION_CODE"/>
                        </tns:AddressVerificationCode>
                        <tns:TransactionLineTranslatedDescription>
                           <xsl:value-of select="ns0:TRANS_LINE_TRANSLATED_DESC"/>
                        </tns:TransactionLineTranslatedDescription>
                        <tns:ConsolidatedBillingNumber>
                           <xsl:value-of select="ns0:CONSOLIDATED_BILLING_NUMBER"/>
                        </tns:ConsolidatedBillingNumber>
                        <tns:PromisedCommitmentAmount>
                           <xsl:value-of select="ns0:PROMISED_COMMITMENT_AMOUNT"/>
                        </tns:PromisedCommitmentAmount>
                        <tns:PaymentSetIdentifier>
                           <xsl:value-of select="ns0:PAYMENT_SET_IDENTIFIER"/>
                        </tns:PaymentSetIdentifier>
                        <tns:OriginalAccountingDate>
                           <xsl:value-of select="ns0:ORIGINAL_ACCOUNTING_DATE"/>
                        </tns:OriginalAccountingDate>
                        <tns:InvoicedLineAccountingLivel>
                           <xsl:value-of select="ns0:INVOICED_LINE_ACC_LEVEL"/>
                        </tns:InvoicedLineAccountingLivel>
                        <tns:OverrideAutoAccountingFlag>
                           <xsl:value-of select="ns0:OVERRIDE_AUTOACCOUNTING_FLAG"/>
                        </tns:OverrideAutoAccountingFlag>
                        <tns:HistoricalFlag>
                           <xsl:value-of select="ns0:HISTORICAL_FLAG"/>
                        </tns:HistoricalFlag>
                        <tns:DeferralExclusionFlag>
                           <xsl:value-of select="ns0:DEFERRAL_EXCLUSION_FLAG"/>
                        </tns:DeferralExclusionFlag>
                        <tns:PaymentAttributes>
                           <xsl:value-of select="ns0:PAYMENT_ATTRIBUTES"/>
                        </tns:PaymentAttributes>
                        <tns:InvoiceBillingDate>
                           <xsl:value-of select="ns0:INVOICE_BILLING_DATE"/>
                        </tns:InvoiceBillingDate>
                        <tns:InvoiceLinesFlexfieldContext>
                           <xsl:value-of select="ns0:INVOICE_LINES_FLXFLD_CNTXT"/>
                        </tns:InvoiceLinesFlexfieldContext>
                        <tns:InvoiceLinesFlexfieldSegment1>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_1"/>
                        </tns:InvoiceLinesFlexfieldSegment1>
                        <tns:InvoiceLinesFlexfieldSegment2>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_2"/>
                        </tns:InvoiceLinesFlexfieldSegment2>
                        <tns:InvoiceLinesFlexfieldSegment3>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_3"/>
                        </tns:InvoiceLinesFlexfieldSegment3>
                        <tns:InvoiceLinesFlexfieldSegment4>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_4"/>
                        </tns:InvoiceLinesFlexfieldSegment4>
                        <tns:InvoiceLinesFlexfieldSegment5>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_5"/>
                        </tns:InvoiceLinesFlexfieldSegment5>
                        <tns:InvoiceLinesFlexfieldSegment6>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_6"/>
                        </tns:InvoiceLinesFlexfieldSegment6>
                        <tns:InvoiceLinesFlexfieldSegment7>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_7"/>
                        </tns:InvoiceLinesFlexfieldSegment7>
                        <tns:InvoiceLinesFlexfieldSegment8>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_8"/>
                        </tns:InvoiceLinesFlexfieldSegment8>
                        <tns:InvoiceLinesFlexfieldSegment9>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_9"/>
                        </tns:InvoiceLinesFlexfieldSegment9>
                        <tns:InvoiceLinesFlexfieldSegment10>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_10"/>
                        </tns:InvoiceLinesFlexfieldSegment10>
                        <tns:InvoiceLinesFlexfieldSegment11>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_11"/>
                        </tns:InvoiceLinesFlexfieldSegment11>
                        <tns:InvoiceLinesFlexfieldSegment12>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_12"/>
                        </tns:InvoiceLinesFlexfieldSegment12>
                        <tns:InvoiceLinesFlexfieldSegment13>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_13"/>
                        </tns:InvoiceLinesFlexfieldSegment13>
                        <tns:InvoiceLinesFlexfieldSegment14>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_14"/>
                        </tns:InvoiceLinesFlexfieldSegment14>
                        <tns:InvoiceLinesFlexfieldSegment15>
                           <xsl:value-of select="ns0:INVOICE_LNS_FLXFLD_SGMNT_15"/>
                        </tns:InvoiceLinesFlexfieldSegment15>
                        <tns:InvoiceTransactionsFlexfieldContext>
                           <xsl:value-of select="ns0:INVOICE_TRANS_FLXFLD_CNTXT"/>
                        </tns:InvoiceTransactionsFlexfieldContext>
                        <tns:InvoiceTransactionsFlexfieldSegment1>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_1"/>
                        </tns:InvoiceTransactionsFlexfieldSegment1>
                        <tns:InvoiceTransactionsFlexfieldSegment2>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_2"/>
                        </tns:InvoiceTransactionsFlexfieldSegment2>
                        <tns:InvoiceTransactionsFlexfieldSegment3>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_3"/>
                        </tns:InvoiceTransactionsFlexfieldSegment3>
                        <tns:InvoiceTransactionsFlexfieldSegment4>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_4"/>
                        </tns:InvoiceTransactionsFlexfieldSegment4>
                        <tns:InvoiceTransactionsFlexfieldSegment5>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_5"/>
                        </tns:InvoiceTransactionsFlexfieldSegment5>
                        <tns:InvoiceTransactionsFlexfieldSegment6>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_6"/>
                        </tns:InvoiceTransactionsFlexfieldSegment6>
                        <tns:InvoiceTransactionsFlexfieldSegment7>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_7"/>
                        </tns:InvoiceTransactionsFlexfieldSegment7>
                        <tns:InvoiceTransactionsFlexfieldSegment8>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_8"/>
                        </tns:InvoiceTransactionsFlexfieldSegment8>
                        <tns:InvoiceTransactionsFlexfieldSegment9>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_9"/>
                        </tns:InvoiceTransactionsFlexfieldSegment9>
                        <tns:InvoiceTransactionsFlexfieldSegment10>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_10"/>
                        </tns:InvoiceTransactionsFlexfieldSegment10>
                        <tns:InvoiceTransactionsFlexfieldSegment11>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_11"/>
                        </tns:InvoiceTransactionsFlexfieldSegment11>
                        <tns:InvoiceTransactionsFlexfieldSegment12>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_12"/>
                        </tns:InvoiceTransactionsFlexfieldSegment12>
                        <tns:InvoiceTransactionsFlexfieldSegment13>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_13"/>
                        </tns:InvoiceTransactionsFlexfieldSegment13>
                        <tns:InvoiceTransactionsFlexfieldSegment14>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_14"/>
                        </tns:InvoiceTransactionsFlexfieldSegment14>
                        <tns:InvoiceTransactionsFlexfieldSegment15>
                           <xsl:value-of select="ns0:INV_TRANS_FLXFLD_SGMNT_15"/>
                        </tns:InvoiceTransactionsFlexfieldSegment15>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldContext>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_CNTXT"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldContext>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment1>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_1"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment1>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment2>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_2"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment2>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment3>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_3"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment3>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment4>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_4"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment4>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment5>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_5"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment5>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment6>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_6"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment6>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment7>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_7"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment7>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment8>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_8"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment8>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment9>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_9"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment9>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment10>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_10"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment10>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment11>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_11"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment11>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment12>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_12"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment12>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment13>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_13"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment13>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment14>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_14"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment14>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment15>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_15"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment15>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment16>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_16"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment16>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment17>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_17"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment17>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment18>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_18"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment18>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment19>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_19"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment19>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment20>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_20"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment20>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment21>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_21"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment21>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment22>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_22"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment22>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment23>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_23"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment23>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment24>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_24"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment24>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment25>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_25"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment25>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment26>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_26"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment26>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment27>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_27"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment27>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment28>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_28"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment28>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment29>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_29"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment29>
                        <tns:ReceivablesTransactionRegionInformationFlexfieldSegment30>
                           <xsl:value-of select="ns0:RCVB_TRN_RGN_INF_FLXF_SGM_30"/>
                        </tns:ReceivablesTransactionRegionInformationFlexfieldSegment30>
                        <tns:LineGlobalDescriptiveFlexfieldAttributeCategory>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_ATTR_CAT"/>
                        </tns:LineGlobalDescriptiveFlexfieldAttributeCategory>
                        <tns:LineGlobalDescriptiveFlexfieldSegment1>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment1>
                        <tns:LineGlobalDescriptiveFlexfieldSegment2>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_2"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment2>
                        <tns:LineGlobalDescriptiveFlexfieldSegment3>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_3"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment3>
                        <tns:LineGlobalDescriptiveFlexfieldSegment4>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_4"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment4>
                        <tns:LineGlobalDescriptiveFlexfieldSegment5>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_5"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment5>
                        <tns:LineGlobalDescriptiveFlexfieldSegment6>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_6"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment6>
                        <tns:LineGlobalDescriptiveFlexfieldSegment7>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_7"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment7>
                        <tns:LineGlobalDescriptiveFlexfieldSegment8>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_8"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment8>
                        <tns:LineGlobalDescriptiveFlexfieldSegment9>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_9"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment9>
                        <tns:LineGlobalDescriptiveFlexfieldSegment10>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_10"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment10>
                        <tns:LineGlobalDescriptiveFlexfieldSegment11>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_11"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment11>
                        <tns:LineGlobalDescriptiveFlexfieldSegment12>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_12"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment12>
                        <tns:LineGlobalDescriptiveFlexfieldSegment13>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_13"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment13>
                        <tns:LineGlobalDescriptiveFlexfieldSegment14>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_14"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment14>
                        <tns:LineGlobalDescriptiveFlexfieldSegment15>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_15"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment15>
                        <tns:LineGlobalDescriptiveFlexfieldSegment16>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_16"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment16>
                        <tns:LineGlobalDescriptiveFlexfieldSegment17>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_17"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment17>
                        <tns:LineGlobalDescriptiveFlexfieldSegment18>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_18"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment18>
                        <tns:LineGlobalDescriptiveFlexfieldSegment19>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_19"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment19>
                        <tns:LineGlobalDescriptiveFlexfieldSegment20>
                           <xsl:value-of select="ns0:LN_GLB_DSC_FLXFLD_SGMNT_1_20"/>
                        </tns:LineGlobalDescriptiveFlexfieldSegment20>
                        <tns:Comments>
                           <xsl:value-of select="ns0:COMMENTS"/>
                        </tns:Comments>
                        <tns:NotesFromSource>
                           <xsl:value-of select="ns0:NOTES_FROM_SOURCE"/>
                        </tns:NotesFromSource>
                        <tns:EnforceChronologicalDocSequencing>
                           <xsl:value-of select="ns0:ENFORCE_CHRONLGCL_DOC_SEQNG"/>
                        </tns:EnforceChronologicalDocSequencing>
                        <tns:OrganizationId>
                           <xsl:value-of select="ns0:ORGANIZATION_ID"/>
                        </tns:OrganizationId>
                     </tns:Invoice>
                  </xsl:for-each>
               </tns:Invoices>
            </xsl:if>
            <tns:Error>
            
               <xsl:value-of select="/ns0:OutputParameters/ns0:P_ERROR"/>
            </tns:Error>
            <tns:ErrorDesc>
               <xsl:value-of select="/ns0:OutputParameters/ns0:P_ERROR_DESC"/>
            </tns:ErrorDesc>
         </tns:Return>
      </tns:GetReceiptOrInvoicesRs>
   </xsl:template>
</xsl:stylesheet>