<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbConciliation" xmlns:tns="http://soa.estrellaroja.com.mx/ConciliationTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/dbConciliation_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="ConciliationCashRs" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbConciliation"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ConciliationTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="ConciliationCashRs" namespace="http://soa.estrellaroja.com.mx/ConciliationTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SAT JUN 19 01:14:52 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ConciliationCashRs>
               <xsl:choose>
            <xsl:when test="string-length (/ns0:ConciliationCashRs/ns0:P_ERROR_DESC ) = 0">
               <cmn:Success/>
            </xsl:when>
         </xsl:choose>
         <xsl:choose>
            <xsl:when test="string-length (/ns0:ConciliationCashRs/ns0:P_ERROR_DESC ) > 0">
               <cmn:Errors>
                  <cmn:Error>
                     <cmn:ErrorCode>
                        <xsl:value-of select="/ns0:ConciliationCashRs/ns0:P_ERROR"/>
                     </cmn:ErrorCode>
                     <cmn:ShortDescription>
                        <xsl:value-of select="/ns0:ConciliationCashRs/ns0:P_ERROR_DESC"/>
                     </cmn:ShortDescription>
                     <cmn:Description/>
                     <cmn:BusinessProcess>Error in  PROCEDURE CONCILIATION_CASH</cmn:BusinessProcess>
                     <cmn:FailedService>XXER_CONCILIATION_PKG.CONCILIATION_CASH</cmn:FailedService>
                     <cmn:TimeStamp>
                        <xsl:value-of select="xp20:current-dateTime ( )"/>
                     </cmn:TimeStamp>
                  </cmn:Error>
               </cmn:Errors>
            </xsl:when>
         </xsl:choose>
         <xsl:for-each select="/ns0:ConciliationCashRs/ns0:P_CONCILIATION_RESULT/ns0:P_CONCILIATION_RESULT_ITEM">
            <tns:XXER_AR_GET_CASH_CONC>
               <tns:REFERENCE_PAYMENT>
                  <xsl:value-of select="ns0:REFERENCE_PAYMENT"/>
               </tns:REFERENCE_PAYMENT>
               <tns:RECEIPT_METHOD>
                  <xsl:value-of select="ns0:RECEIPT_METHOD"/>
               </tns:RECEIPT_METHOD>
               <tns:STATUS>
                  <xsl:value-of select="ns0:STATUS"/>
               </tns:STATUS>
            </tns:XXER_AR_GET_CASH_CONC>
         </xsl:for-each>
         

      </tns:ConciliationCashRs>
   </xsl:template>
</xsl:stylesheet>