<wsdl:definitions targetNamespace="http://soa.estrellaroja.com.mx/BanxicoTec" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://soa.estrellaroja.com.mx/BanxicoTec" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	TYPE DEFINITION - List of services participating in this process.
        You can define or import any XML Schema type and use them as part of the message types.
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <wsdl:types>
    <xsd:schema targetNamespace="http://soa.estrellaroja.com.mx/BanxicoTec/types" elementFormDefault="qualified">
      <xsd:import namespace="http://soa.estrellaroja.com.mx/BanxicoTec" schemaLocation="../Schemas/BanxicoTec.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	MESSAGE TYPE DEFINITION - Definition of the message types used as 
	part of the port type defintions
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <wsdl:message name="GetExchangeRateRq">
    <wsdl:part name="GetExchangeRateRq" element="tns:GetExchangeRateRq"/>
  </wsdl:message>
  <wsdl:message name="GetExchangeRateRs">
    <wsdl:part name="GetExchangeRateRs" element="tns:GetExchangeRateRs"/>
  </wsdl:message>
 
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	PORT TYPE DEFINITION - A port type groups a set of operations into
	a logical service unit.
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <wsdl:portType name="BanxicoTecPortType">
    <wsdl:operation name="GetExchangeRate">
      <wsdl:input message="tns:GetExchangeRateRq"/>
      <wsdl:output message="tns:GetExchangeRateRs"/>
    </wsdl:operation>
  </wsdl:portType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	BINDING OPERATIONS DEFINITION
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <wsdl:binding name="BanxicoTecBinding" type="tns:BanxicoTecPortType">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetExchangeRate">
      <soap12:operation soapAction="http://soa.estrellaroja.com.mx/BanxicoTec/GetExchangeRate"/>
      <wsdl:input>
        <soap12:body/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>