<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbXXER_BANK_AMEX" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/ConciliationTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ConciliationTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="SendConciliationBankAMEXRq" namespace="http://soa.estrellaroja.com.mx/ConciliationTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/dbXXER_BANK_AMEX_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="XxerBancosAmexHeaderTblCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbXXER_BANK_AMEX"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [FRI AUG 27 17:55:17 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
<xsl:template match="/">
      <tns:XxerBancosAmexHeaderTblCollection>
         <tns:XxerBancosAmexHeaderTbl>
            <tns:fechaCreacionArchivo>
               <xsl:value-of select="/ns0:SendConciliationBankAMEXRq/ns0:HEADER/ns0:FECHA_CREACION_ARCHIVO"/>
            </tns:fechaCreacionArchivo>
            <tns:horaCreacionArchivo>
               <xsl:value-of select="/ns0:SendConciliationBankAMEXRq/ns0:HEADER/ns0:HORA_CREACION_ARCHIVO"/>
            </tns:horaCreacionArchivo>
            <tns:numSecuencial>
               <xsl:value-of select="/ns0:SendConciliationBankAMEXRq/ns0:HEADER/ns0:NUM_SECUENCIAL"/>
            </tns:numSecuencial>
            <tns:identidiacionArchivo>
               <xsl:value-of select="/ns0:SendConciliationBankAMEXRq/ns0:HEADER/ns0:IDENTIDIACION_ARCHIVO"/>
            </tns:identidiacionArchivo>
            <tns:nombreArchivo>
               <xsl:value-of select="/ns0:SendConciliationBankAMEXRq/ns0:HEADER/ns0:NOMBRE_ARCHIVO"/>
            </tns:nombreArchivo>
            <tns:numVersionArchivo>
               <xsl:value-of select="/ns0:SendConciliationBankAMEXRq/ns0:HEADER/ns0:NUM_VERSION_ARCHIVO"/>
            </tns:numVersionArchivo>
            <tns:sumaTotalRegistros>
               <xsl:value-of select="/ns0:SendConciliationBankAMEXRq/ns0:TRAILER/ns0:SUMA_TOTAL_REGISTROS"/>
            </tns:sumaTotalRegistros>
            <tns:xxerBancosAmexSummaryTblCollection>
               <xsl:for-each select="/ns0:SendConciliationBankAMEXRq/ns0:SUMMARY">
                  <tns:XxerBancosAmexSummaryTbl>
                     <tns:identificacionEstablecimiento>
                        <xsl:value-of select="ns0:IDENTIFICACION_ESTABLECIMIENTO"/>
                     </tns:identificacionEstablecimiento>
                     <tns:codigoTipoCuenta>
                        <xsl:value-of select="ns0:CODIGO_TIPO_CUENTA"/>
                     </tns:codigoTipoCuenta>
                         <xsl:variable name="numPagoAMEX" select="ns0:NUM_PAGO"/>
                     <tns:numPagoAmex>
                        <xsl:value-of select="ns0:NUM_PAGO"/>
                     </tns:numPagoAmex>
                     <tns:fechaPago>
                        <xsl:value-of select="ns0:FECHA_PAGO"/>
                     </tns:fechaPago>
                     <tns:monedaPago>
                        <xsl:value-of select="ns0:MONEDA_PAGO"/>
                     </tns:monedaPago>
                     <tns:numUnicoReferenciaPago>
                        <xsl:value-of select="ns0:NUM_UNICO_REFERENCIA_PAGO"/>
                     </tns:numUnicoReferenciaPago>
                     <tns:montoNetoPago>
                        <xsl:value-of select="ns0:MONTO_NETO_PAGO"/>
                     </tns:montoNetoPago>
                     <tns:montoBrutoPago>
                        <xsl:value-of select="ns0:MONTO_BRUTO_PAGO"/>
                     </tns:montoBrutoPago>
                     <tns:montoDescuento>
                        <xsl:value-of select="ns0:MONTO_DESCUENTO"/>
                     </tns:montoDescuento>
                     <tns:montoServicio>
                        <xsl:value-of select="ns0:MONTO_SERVICIO"/>
                     </tns:montoServicio>
                     <tns:montoAjuste>
                        <xsl:value-of select="ns0:MONTO_AJUSTE"/>
                     </tns:montoAjuste>
                     <tns:montoImpuestos>
                        <xsl:value-of select="ns0:MONTO_IMPUESTOS"/>
                     </tns:montoImpuestos>
                     <tns:montoSaldoDebitoInicial>
                        <xsl:value-of select="ns0:MONTO_SALDO_DEBITO_INICIAL"/>
                     </tns:montoSaldoDebitoInicial>
                     <tns:numDepositoDirecto>
                        <xsl:value-of select="ns0:NUM_DEPOSITO_DIRECTO"/>
                     </tns:numDepositoDirecto>
                     <tns:numCuentaBancaria>
                        <xsl:value-of select="ns0:NUM_CUENTA_BANCARIA"/>
                     </tns:numCuentaBancaria>
                     <tns:numCuentaBancariaInternacional>
                        <xsl:value-of select="ns0:NUM_CUENTA_BANCARIA_INTERNACIONAL"/>
                     </tns:numCuentaBancariaInternacional>
                     <tns:codigoBanco>
                        <xsl:value-of select="ns0:CODIGO_BANCO"/>
                     </tns:codigoBanco>
                        
                                          <tns:xxerBancosAmexChargebackTblCollection>
                        <xsl:for-each select="/ns0:SendConciliationBankAMEXRq/ns0:CHARGEBACK[ns0:NUM_PAGO_AMERICAN_EXPRESS=$numPagoAMEX]">
                           <tns:XxerBancosAmexChargebackTbl>
                              <tns:numEstablecimiento>
                                 <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO"/>
                              </tns:numEstablecimiento>
                              <tns:codigoTipoCuenta>
                                 <xsl:value-of select="ns0:CODIGO_TIPO_CUENTA_"/>
                              </tns:codigoTipoCuenta>
                              <tns:monedaPago>
                                 <xsl:value-of select="ns0:MONEDA_PAGO"/>
                              </tns:monedaPago>
                              <tns:numEstablecimientoPresentacion>
                                 <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO_PRESENTACION"/>
                              </tns:numEstablecimientoPresentacion>
                              <tns:fechaPresentacion>
                                 <xsl:value-of select="ns0:FECHA_PRESENTACION"/>
                              </tns:fechaPresentacion>
                              <tns:ubicacionEstablecimiento>
                                 <xsl:value-of select="ns0:UBICACION_ESTABLECIMIENTO"/>
                              </tns:ubicacionEstablecimiento>
                              <tns:numFacturaOReferencia>
                                 <xsl:value-of select="ns0:NUM_FACTURA_O_REFERENCIA"/>
                              </tns:numFacturaOReferencia>
                              <tns:identificacionVendedor>
                                 <xsl:value-of select="ns0:IDENTIFICACION_VENDEDOR"/>
                              </tns:identificacionVendedor>
                              <tns:numTarjeta>
                                 <xsl:value-of select="ns0:NUM_TARJETA"/>
                              </tns:numTarjeta>
                              <tns:numReferenciaIndustria>
                                 <xsl:value-of select="ns0:NUM_REFERENCIA_INDUSTRIA"/>
                              </tns:numReferenciaIndustria>
                              <tns:fechaProcesamientoAmex>
                                 <xsl:value-of select="ns0:FECHA_PROCESAMIENTO_AMERICAN_EXPRESS"/>
                              </tns:fechaProcesamientoAmex>
                              <tns:numFactura>
                                 <xsl:value-of select="ns0:NUM_FACTURA"/>
                              </tns:numFactura>
                              <tns:monedaPresentacion>
                                 <xsl:value-of select="ns0:MONEDA_PRESENTACION"/>
                              </tns:monedaPresentacion>
                              <tns:numContracargo>
                                 <xsl:value-of select="ns0:NUM_CONTRACARGO"/>
                              </tns:numContracargo>
                              <tns:codigoMotivoContracargo>
                                 <xsl:value-of select="ns0:CODIGO_MOTIVO_CONTRACARGO"/>
                              </tns:codigoMotivoContracargo>
                              <tns:descripcionMotivoContracargo>
                                 <xsl:value-of select="ns0:DESCRIPCION_MOTIVO_CONTRACARGO"/>
                              </tns:descripcionMotivoContracargo>
                              <tns:montoBruto>
                                 <xsl:value-of select="ns0:MONTO_BRUTO"/>
                              </tns:montoBruto>
                              <tns:montoDescuento>
                                 <xsl:value-of select="ns0:MONTO_DESCUENTO"/>
                              </tns:montoDescuento>
                              <tns:montoCargoServicio>
                                 <xsl:value-of select="ns0:MONTO_CARGO_SERVICIO"/>
                              </tns:montoCargoServicio>
                              <tns:montoImpuesto>
                                 <xsl:value-of select="ns0:MONTO_IMPUESTO"/>
                              </tns:montoImpuesto>
                              <tns:montoNeto>
                                 <xsl:value-of select="ns0:MONTO_NETO"/>
                              </tns:montoNeto>
                              <tns:tasaDescuento>
                                 <xsl:value-of select="ns0:TASA_DESCUENTO"/>
                              </tns:tasaDescuento>
                              <tns:tasaCargoServicio>
                                 <xsl:value-of select="ns0:TASA_CARGO_SERVICIO"/>
                              </tns:tasaCargoServicio>
                              <tns:codigoLote>
                                 <xsl:value-of select="ns0:CODIGO_LOTE"/>
                              </tns:codigoLote>
                              <tns:codigoFactura>
                                 <xsl:value-of select="ns0:CODIGO_FACTURA"/>
                              </tns:codigoFactura>
                           </tns:XxerBancosAmexChargebackTbl>
                        </xsl:for-each>
                     </tns:xxerBancosAmexChargebackTblCollection>
                      <tns:xxerBancosAmexAdjustmentTblCollection>
                        <xsl:for-each select="/ns0:SendConciliationBankAMEXRq/ns0:ADJUSTMENT[ns0:NUM_PAGO_AMEX=$numPagoAMEX]">
                           <tns:XxerBancosAmexAdjustmentTbl>
                              <tns:numEstablecimiento>
                                 <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO"/>
                              </tns:numEstablecimiento>
                              <tns:codigoTipoCuenta>
                                 <xsl:value-of select="ns0:CODIGO_TIPO_CUENTA"/>
                              </tns:codigoTipoCuenta>
                              <tns:monedaPago>
                                 <xsl:value-of select="ns0:MONEDA_PAGO"/>
                              </tns:monedaPago>
                              <tns:numEstablecimientoPresentacion>
                                 <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO_PRESENTACION"/>
                              </tns:numEstablecimientoPresentacion>
                              <tns:fechaEnvio>
                                 <xsl:value-of select="ns0:FECHA_ENVIO"/>
                              </tns:fechaEnvio>
                              <tns:ubicacionEstablecimiento>
                                 <xsl:value-of select="ns0:UBICACION_ESTABLECIMIENTO"/>
                              </tns:ubicacionEstablecimiento>
                              <tns:numFacturaReferencia>
                                 <xsl:value-of select="ns0:NUM_FACTURA_REFERENCIA"/>
                              </tns:numFacturaReferencia>
                              <tns:identificacionVendedor>
                                 <xsl:value-of select="ns0:IDENTIFICACION_VENDEDOR"/>
                              </tns:identificacionVendedor>
                              <tns:numTarjeta>
                                 <xsl:value-of select="ns0:NUM_TARJETA"/>
                              </tns:numTarjeta>
                              <tns:numReferenciaIndustria>
                                 <xsl:value-of select="ns0:NUM_REFERENCIA_INDUSTRIA"/>
                              </tns:numReferenciaIndustria>
                              <tns:fechaProcesamientoAmex>
                                 <xsl:value-of select="ns0:FECHA_PROCESAMIENTO_AMEX"/>
                              </tns:fechaProcesamientoAmex>
                              <tns:numFactura>
                                 <xsl:value-of select="ns0:NUM_FACTURA"/>
                              </tns:numFactura>
                              <tns:monedaPresentacion>
                                 <xsl:value-of select="ns0:MONEDA_PRESENTACION"/>
                              </tns:monedaPresentacion>
                              <tns:numAjuste>
                                 <xsl:value-of select="ns0:NUM_AJUSTE"/>
                              </tns:numAjuste>
                              <tns:codigoMotivoAjuste>
                                 <xsl:value-of select="ns0:CODIGO_MOTIVO_AJUSTE"/>
                              </tns:codigoMotivoAjuste>
                              <tns:descripcionMotivoAjuste>
                                 <xsl:value-of select="ns0:DESCRIPCION_MOTIVO_AJUSTE"/>
                              </tns:descripcionMotivoAjuste>
                              <tns:montoBruto>
                                 <xsl:value-of select="ns0:MONTO_BRUTO"/>
                              </tns:montoBruto>
                              <tns:montoDescuento>
                                 <xsl:value-of select="ns0:MONTO_DESCUENTO"/>
                              </tns:montoDescuento>
                              <tns:montoCargoServicio>
                                 <xsl:value-of select="ns0:MONTO_CARGO_SERVICIO"/>
                              </tns:montoCargoServicio>
                              <tns:montoImpuesto>
                                 <xsl:value-of select="ns0:MONTO_IMPUESTO"/>
                              </tns:montoImpuesto>
                              <tns:montoNeto>
                                 <xsl:value-of select="ns0:MONTO_NETO"/>
                              </tns:montoNeto>
                              <tns:tasaDescuento>
                                 <xsl:value-of select="ns0:TASA_DESCUENTO"/>
                              </tns:tasaDescuento>
                              <tns:tasaCargoServicio>
                                 <xsl:value-of select="ns0:TASA_CARGO_SERVICIO"/>
                              </tns:tasaCargoServicio>
                              <tns:codigoLote>
                                 <xsl:value-of select="ns0:CODIGO_LOTE"/>
                              </tns:codigoLote>
                              <tns:codigoFactura>
                                 <xsl:value-of select="ns0:CODIGO_FACTURA"/>
                              </tns:codigoFactura>
                           </tns:XxerBancosAmexAdjustmentTbl>
                        </xsl:for-each>
                     </tns:xxerBancosAmexAdjustmentTblCollection>
                     <tns:xxerBancosAmexSubmissionTblCollection>
                        <xsl:for-each select="/ns0:SendConciliationBankAMEXRq/ns0:SUBMISSION[ns0:NUM_PAGO_AMEX=$numPagoAMEX]">
                           <tns:XxerBancosAmexSubmissionTbl>
                              <tns:numEstablecimiento>
                                 <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO"/>
                              </tns:numEstablecimiento>
                              <tns:codigoTipoCuenta>
                                 <xsl:value-of select="ns0:CODIGO_TIPO_CUENTA"/>
                              </tns:codigoTipoCuenta>
                              <tns:monedaPago>
                                 <xsl:value-of select="ns0:MONEDA_PAGO"/>
                              </tns:monedaPago>
                              <tns:numEstablecimientoPresention>
                                 <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO_PRESENTION"/>
                              </tns:numEstablecimientoPresention>
                              <tns:fechaEnvioComercial>
                                 <xsl:value-of select="ns0:FECHA_ENVIO_COMERCIAL"/>
                              </tns:fechaEnvioComercial>
                              <tns:fechaProcesamientoAmex>
                                 <xsl:value-of select="ns0:FECHA_PROCESAMIENTO_AMEX"/>
                              </tns:fechaProcesamientoAmex>
                               <xsl:variable name="fechaPAMEX" select="ns0:FECHA_PROCESAMIENTO_AMEX"/>
                              <tns:numFactura>
                                 <xsl:value-of select="ns0:NUM_FACTURA"/>
                              </tns:numFactura>
                              <tns:moneda>
                                 <xsl:value-of select="ns0:MONEDA"/>
                              </tns:moneda>
                              <tns:relleno>
                                 <xsl:value-of select="ns0:RELLENO"/>
                              </tns:relleno>
                              <tns:tasaCambio>
                                 <xsl:value-of select="ns0:TASA_CAMBIO"/>
                              </tns:tasaCambio>
                              <tns:montoBrutoMonedaPresentacion>
                                 <xsl:value-of select="ns0:MONTO_BRUTO_MONEDA_PRESENTACION"/>
                              </tns:montoBrutoMonedaPresentacion>
                              <tns:montoBrutoMonedaPago>
                                 <xsl:value-of select="ns0:MONTO_BRUTO_MONEDA_PAGO"/>
                              </tns:montoBrutoMonedaPago>
                              <tns:montoDescuentoRsentcion>
                                 <xsl:value-of select="ns0:MONTO_DESCUENTO_RSENTCION"/>
                              </tns:montoDescuentoRsentcion>
                              <tns:montoCargoServicio>
                                 <xsl:value-of select="ns0:MONTO_CARGO_SERVICIO"/>
                              </tns:montoCargoServicio>
                              <tns:montoImpuesto>
                                 <xsl:value-of select="ns0:MONTO_IMPUESTO"/>
                              </tns:montoImpuesto>
                              <tns:montoNeto>
                                 <xsl:value-of select="ns0:MONTO_NETO"/>
                              </tns:montoNeto>
                              <tns:tasaDescuento>
                                 <xsl:value-of select="ns0:TASA_DESCUENTO"/>
                              </tns:tasaDescuento>
                              <tns:tasaImpuesto>
                                 <xsl:value-of select="ns0:TASA_IMPUESTO"/>
                              </tns:tasaImpuesto>
                              <tns:sumaTransacciones>
                                 <xsl:value-of select="ns0:SUMA_TRANSACCIONES"/>
                              </tns:sumaTransacciones>
                              <tns:identificacionSeguimiento>
                                 <xsl:value-of select="ns0:IDENTIFICACION_SEGUIMIENTO"/>
                              </tns:identificacionSeguimiento>
                              <tns:numCuota>
                                 <xsl:value-of select="ns0:NUM_CUOTA"/>
                              </tns:numCuota>
                              <tns:numAceleracion>
                                 <xsl:value-of select="ns0:NUM_ACELERACION"/>
                              </tns:numAceleracion>
                              <tns:fechaLiquidacionOriginal>
                                 <xsl:value-of select="ns0:FECHA_LIQUIDACION_ORIGINAL"/>
                              </tns:fechaLiquidacionOriginal>
                              <tns:fechaAceleracion>
                                 <xsl:value-of select="ns0:FECHA_ACELERACION"/>
                              </tns:fechaAceleracion>
                              <tns:cantidadDiasAdelantados>
                                 <xsl:value-of select="ns0:CANTIDAD_DIAS_ADELANTADOS"/>
                              </tns:cantidadDiasAdelantados>
                              <tns:montoCargoAceleracion>
                                 <xsl:value-of select="ns0:MONTO_CARGO_ACELERACION"/>
                              </tns:montoCargoAceleracion>
                              <tns:montoNetoCargoAceleracion>
                                 <xsl:value-of select="ns0:MONTO_NETO_CARGO_ACELERACION"/>
                              </tns:montoNetoCargoAceleracion>
                              <tns:montoBrutoDebito>
                                 <xsl:value-of select="ns0:MONTO_BRUTO_DEBITO"/>
                              </tns:montoBrutoDebito>
                              <tns:montoBrutoCredito>
                                 <xsl:value-of select="ns0:MONTO_BRUTO_CREDITO"/>
                              </tns:montoBrutoCredito>
                              <tns:xxerBancosAmexTransactnTblCollection>
                                 <xsl:for-each select="/ns0:SendConciliationBankAMEXRq/ns0:TRANSACTN[ns0:NUM_PAGO_AMEX=$numPagoAMEX  and ns0:FECHA_PROCESAMIENTO_AMEX=$fechaPAMEX]">
                                    <tns:XxerBancosAmexTransactnTbl>
                                       <tns:numEstablecimiento>
                                          <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO"/>
                                       </tns:numEstablecimiento>
                                       <tns:codigoTipoCuenta>
                                          <xsl:value-of select="ns0:CODIGO_TIPO_CUENTA"/>
                                       </tns:codigoTipoCuenta>
                                       <tns:monedaPago>
                                          <xsl:value-of select="ns0:MONEDA_PAGO"/>
                                       </tns:monedaPago>
                                       <tns:numEstablecimiento2>
                                          <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO2"/>
                                       </tns:numEstablecimiento2>
                                       <tns:fechaPresentacion>
                                          <xsl:value-of select="ns0:FECHA_PRESENTACION"/>
                                       </tns:fechaPresentacion>
                                       <tns:fechaProcesamientoAmex>
                                          <xsl:value-of select="ns0:FECHA_PROCESAMIENTO_AMEX"/>
                                       </tns:fechaProcesamientoAmex>
                                       <tns:numFactura>
                                          <xsl:value-of select="ns0:NUM_FACTURA"/>
                                       </tns:numFactura>
                                       <tns:monedaPresentacion>
                                          <xsl:value-of select="ns0:MONEDA_PRESENTACION"/>
                                       </tns:monedaPresentacion>
                                       <tns:identificacionUbicacionEstablecimiento>
                                          <xsl:value-of select="ns0:IDENTIFICACION_UBICACION_ESTABLECIMIENTO"/>
                                       </tns:identificacionUbicacionEstablecimiento>
                 <xsl:variable name="numFacturaReferencia" select="ns0:NUM_FACTURA_REFERENCIA"/>
   
                                       <tns:numFacturaReferencia>
                                          <xsl:value-of select="ns0:NUM_FACTURA_REFERENCIA"/>
                                       </tns:numFacturaReferencia>
                                       <tns:numVendedor>
                                          <xsl:value-of select="ns0:NUM_VENDEDOR"/>
                                       </tns:numVendedor>
                                       <tns:numTarjeta>
                                          <xsl:value-of select="ns0:NUM_TARJETA"/>
                                       </tns:numTarjeta>
                                       <tns:numReferenciaEspecificoIndustria>
                                          <xsl:value-of select="ns0:NUM_REFERENCIA_ESPECIFICO_INDUSTRIA"/>
                                       </tns:numReferenciaEspecificoIndustria>
                                       <tns:montoBrutoPresentacion>
                                          <xsl:value-of select="ns0:MONTO_BRUTO_PRESENTACION"/>
                                       </tns:montoBrutoPresentacion>
                                       <tns:montoTransaccion>
                                          <xsl:value-of select="ns0:MONTO_TRANSACCION"/>
                                       </tns:montoTransaccion>
                                       <tns:fechaTransaccion>
                                          <xsl:value-of select="ns0:FECHA_TRANSACCION"/>
                                       </tns:fechaTransaccion>
                                       <tns:horaTransaccion>
                                          <xsl:value-of select="ns0:HORA_TRANSACCION"/>
                                       </tns:horaTransaccion>
                                       <tns:numTransaccion>
                                          <xsl:value-of select="ns0:NUM_TRANSACCION"/>
                                       </tns:numTransaccion>
                                       <tns:codigoAprobacion>
                                          <xsl:value-of select="ns0:CODIGO_APROBACION"/>
                                       </tns:codigoAprobacion>
                                       <tns:numTerminal>
                                          <xsl:value-of select="ns0:NUM_TERMINAL"/>
                                       </tns:numTerminal>
                                       <tns:codigoCategoriaEstablecimiento>
                                          <xsl:value-of select="ns0:CODIGO_CATEGORIA_ESTABLECIMIENTO"/>
                                       </tns:codigoCategoriaEstablecimiento>
                                       <tns:numReferenciaSocio>
                                          <xsl:value-of select="ns0:NUM_REFERENCIA_SOCIO"/>
                                       </tns:numReferenciaSocio>
                                       <tns:numReferenciaAdquirente>
                                          <xsl:value-of select="ns0:NUM_REFERENCIA_ADQUIRENTE"/>
                                       </tns:numReferenciaAdquirente>
                                       <tns:codigoErrorIncumplimientoCalidadDatos>
                                          <xsl:value-of select="ns0:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS"/>
                                       </tns:codigoErrorIncumplimientoCalidadDatos>
                                       <tns:codigoErrorIncumplimientoCalidadDatos1>
                                          <xsl:value-of select="ns0:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS1"/>
                                       </tns:codigoErrorIncumplimientoCalidadDatos1>
                                       <tns:codigoErrorIncumplimientoCalidadDatos2>
                                          <xsl:value-of select="ns0:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS2"/>
                                       </tns:codigoErrorIncumplimientoCalidadDatos2>
                                       <tns:codigoErrorIncumplimientoCalidadDatos3>
                                          <xsl:value-of select="ns0:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS3"/>
                                       </tns:codigoErrorIncumplimientoCalidadDatos3>
                                       <tns:codigoErrorIncumplimientoCalidadDatos4>
                                          <xsl:value-of select="ns0:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS4"/>
                                       </tns:codigoErrorIncumplimientoCalidadDatos4>
                                       <tns:indicadorLecturaBanda>
                                          <xsl:value-of select="ns0:INDICADOR_LECTURA_BANDA"/>
                                       </tns:indicadorLecturaBanda>
                                       <tns:indicadorTransaccionRechazada>
                                          <xsl:value-of select="ns0:INDICADOR_TRANSACCION_RECHAZADA"/>
                                       </tns:indicadorTransaccionRechazada>
                                       <tns:montoPrimeraCuota>
                                          <xsl:value-of select="ns0:MONTO_PRIMERA_CUOTA"/>
                                       </tns:montoPrimeraCuota>
                                       <tns:montoCuotaSiguiente>
                                          <xsl:value-of select="ns0:MONTO_CUOTA_SIGUIENTE"/>
                                       </tns:montoCuotaSiguiente>
                                       <tns:cantidadCuotas>
                                          <xsl:value-of select="ns0:CANTIDAD_CUOTAS"/>
                                       </tns:cantidadCuotas>
                                       <tns:numCuota>
                                          <xsl:value-of select="ns0:NUM_CUOTA"/>
                                       </tns:numCuota>
                                       <tns:relleno>
                                          <xsl:value-of select="ns0:RELLENO"/>
                                       </tns:relleno>
                                       <tns:montoServicio>
                                          <xsl:value-of select="ns0:MONTO_SERVICIO"/>
                                       </tns:montoServicio>
                                       <tns:montoAceleracion>
                                          <xsl:value-of select="ns0:MONTO_ACELERACION"/>
                                       </tns:montoAceleracion>
                                       <tns:xxerBancosAmexTxnpricingTblCollection>
                                          <xsl:for-each select="/ns0:SendConciliationBankAMEXRq/ns0:TXNPRICING[ns0:NUM_PAGO_AMEX=$numPagoAMEX and ns0:NUM_FACTURA_REFERENCIA=$numFacturaReferencia]">
                                             <tns:XxerBancosAmexTxnpricingTbl>
                                                <tns:numeroEstablcimiento>
                                                   <xsl:value-of select="ns0:NUMERO_ESTABLCIMIENTO"/>
                                                </tns:numeroEstablcimiento>
                                                <tns:codigoCuenta>
                                                   <xsl:value-of select="ns0:CODIGO_CUENTA"/>
                                                </tns:codigoCuenta>
                                                <tns:monedaPago>
                                                   <xsl:value-of select="ns0:MONEDA_PAGO"/>
                                                </tns:monedaPago>
                                                <tns:numEstablecimentoPresentacion>
                                                   <xsl:value-of select="ns0:NUM_ESTABLECIMENTO_PRESENTACION"/>
                                                </tns:numEstablecimentoPresentacion>
                                                <tns:ubicacionEstablecimiento>
                                                   <xsl:value-of select="ns0:UBICACION_ESTABLECIMIENTO"/>
                                                </tns:ubicacionEstablecimiento>
                                                <tns:relleno>
                                                   <xsl:value-of select="ns0:RELLENO"/>
                                                </tns:relleno>
                                                <tns:numeroVendedor>
                                                   <xsl:value-of select="ns0:NUMERO_VENDEDOR"/>
                                                </tns:numeroVendedor>
                                                <tns:numTarjeta>
                                                   <xsl:value-of select="ns0:NUM_TARJETA"/>
                                                </tns:numTarjeta>
                                                <tns:montoTransaccion>
                                                   <xsl:value-of select="ns0:MONTO_TRANSACCION"/>
                                                </tns:montoTransaccion>
                                                <tns:fechaTransaccion>
                                                   <xsl:value-of select="ns0:FECHA_TRANSACCION"/>
                                                </tns:fechaTransaccion>
                                                <tns:codigoCargo>
                                                   <xsl:value-of select="ns0:CODIGO_CARGO"/>
                                                </tns:codigoCargo>
                                                <tns:relleno2>
                                                   <xsl:value-of select="ns0:RELLENO2"/>
                                                </tns:relleno2>
                                                <tns:montoCargo>
                                                   <xsl:value-of select="ns0:MONTO_CARGO"/>
                                                </tns:montoCargo>
                                                <tns:tasaDescuento>
                                                   <xsl:value-of select="ns0:TASA_DESCUENTO"/>
                                                </tns:tasaDescuento>
                                                <tns:montoDescuento>
                                                   <xsl:value-of select="ns0:MONTO_DESCUENTO"/>
                                                </tns:montoDescuento>
                                             </tns:XxerBancosAmexTxnpricingTbl>
                                          </xsl:for-each>
                                       </tns:xxerBancosAmexTxnpricingTblCollection>
                                    </tns:XxerBancosAmexTransactnTbl>
                                 </xsl:for-each>
                              </tns:xxerBancosAmexTransactnTblCollection>
                           </tns:XxerBancosAmexSubmissionTbl>
                        </xsl:for-each>
                     </tns:xxerBancosAmexSubmissionTblCollection>
                  </tns:XxerBancosAmexSummaryTbl>
               </xsl:for-each>
            </tns:xxerBancosAmexSummaryTblCollection>
         </tns:XxerBancosAmexHeaderTbl>
      </tns:XxerBancosAmexHeaderTblCollection>
   </xsl:template>
</xsl:stylesheet>