<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergePerson/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/" xmlns:ns5="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/partySite/" xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/" xmlns:types="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/types/" xmlns:sdoXML="commonj.sdo/xml" xmlns:ns7="http://xmlns.oracle.com/adf/svc/types/" xmlns:sdoJava="commonj.sdo/java" xmlns:ns8="http://xmlns.oracle.com/apps/cdm/foundation/parties/relationshipService/" xmlns:ns9="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/orgContact/" xmlns:ns10="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/" xmlns:ns12="http://xmlns.oracle.com/apps/cdm/foundation/parties/partyService/" xmlns:ns13="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/relationship/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns4="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/person/" xmlns:ns6="http://xmlns.oracle.com/apps/cdm/foundation/parties/contactPointService/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns11="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/sourceSystemRef/" xmlns:ns1="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/contactPoint/" xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergePerson" xmlns:ns15="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergePerson" xmlns:ns14="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergePerson/types">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="CreatePersonRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../../WSDL/Externals/Cloud/Customers/erpRefMergePerson.wsdl"/>
            <oracle-xsl-mapper:rootElement name="mergePerson" namespace="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergePerson/types"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 07 10:28:26 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:mergePerson>
         <tns:personParty>
            <ns10:CreatedByModule>HZ_WS</ns10:CreatedByModule>
            <ns10:PersonProfile>
               <ns10:PersonFirstName>
                  <xsl:value-of select="/ns0:CreatePersonRq/ns0:Person/ns0:FirstName"/>
               </ns10:PersonFirstName>
               <ns10:PersonLastName>
                  <xsl:value-of select="/ns0:CreatePersonRq/ns0:Person/ns0:LastName"/>
               </ns10:PersonLastName>
               <ns10:JgzzFiscalCode>
                  <xsl:value-of select="/ns0:CreatePersonRq/ns0:Person/ns0:FiscalCode"/>
               </ns10:JgzzFiscalCode>
               <ns10:CreatedByModule>HZ_WS</ns10:CreatedByModule>
            </ns10:PersonProfile>
            <ns10:PartyUsageAssignment>
               <ns12:PartyUsageCode>PARTY_OF_INTEREST</ns12:PartyUsageCode>
               <ns12:CreatedByModule>HZ_WS</ns12:CreatedByModule>
            </ns10:PartyUsageAssignment>
         </tns:personParty>
      </tns:mergePerson>
   </xsl:template>
</xsl:stylesheet>