<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbInvoicesAP" xmlns:tns="http://soa.estrellaroja.com.mx/ValidacionAutomaticTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/dbInvoicesAP_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="XxerInvoicesApTblCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbInvoicesAP"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ValidacionAutomaticTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetReportValidationResponse" namespace="http://soa.estrellaroja.com.mx/ValidacionAutomaticTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED JUL 21 09:57:21 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetReportValidationResponse>
         <xsl:for-each select="/ns0:XxerInvoicesApTblCollection/ns0:XxerInvoicesApTbl">
            <tns:XxerInvoicesApTbl>
               <tns:invoiceId>
                  <xsl:value-of select="ns0:invoiceId"/>
               </tns:invoiceId>
               <tns:emisorRfc>
                  <xsl:value-of select="ns0:emisorRfc"/>
               </tns:emisorRfc>
               <tns:receptorRfc>
                  <xsl:value-of select="ns0:receptorRfc"/>
               </tns:receptorRfc>
               <tns:amount>
                  <xsl:value-of select="ns0:amount"/>
               </tns:amount>
               <tns:uuid>
                  <xsl:value-of select="ns0:uuid"/>
               </tns:uuid>
               <tns:status>
                  <xsl:value-of select="ns0:status"/>
               </tns:status>
               <tns:businessUnit>
                  <xsl:value-of select="ns0:businessUnit"/>
               </tns:businessUnit>
               <tns:invoiceNumber>
                  <xsl:value-of select="ns0:invoiceNumber"/>
               </tns:invoiceNumber>
               <tns:supplierNumber>
                  <xsl:value-of select="ns0:supplierNumber"/>
               </tns:supplierNumber>
               <tns:attribute1>
                  <xsl:value-of select="ns0:attribute1"/>
               </tns:attribute1>
               <tns:attribute2>
                  <xsl:value-of select="ns0:attribute2"/>
               </tns:attribute2>
               <tns:attribute3>
                  <xsl:value-of select="ns0:attribute3"/>
               </tns:attribute3>
               <tns:attribute4>
                  <xsl:value-of select="ns0:attribute4"/>
               </tns:attribute4>
               <tns:attribute5>
                  <xsl:value-of select="ns0:attribute5"/>
               </tns:attribute5>
               <tns:createdBy>
                  <xsl:value-of select="ns0:createdBy"/>
               </tns:createdBy>
               <tns:creationDate>
                  <xsl:value-of select="ns0:creationDate"/>
               </tns:creationDate>
               <tns:lastUpdatedBy>
                  <xsl:value-of select="ns0:lastUpdatedBy"/>
               </tns:lastUpdatedBy>
               <tns:lastUpdateDate>
                  <xsl:value-of select="ns0:lastUpdateDate"/>
               </tns:lastUpdateDate>
               <tns:objectVersionNumber>
                  <xsl:value-of select="ns0:objectVersionNumber"/>
               </tns:objectVersionNumber>
               <tns:numeroPago>
                  <xsl:value-of select="ns0:numeroPago"/>
               </tns:numeroPago>
               <tns:documentoPago>
                  <xsl:value-of select="ns0:documentoPago"/>
               </tns:documentoPago>
               <tns:estadoPago>
                  <xsl:value-of select="ns0:estadoPago"/>
               </tns:estadoPago>
               <tns:tipoPago>
                  <xsl:value-of select="ns0:tipoPago"/>
               </tns:tipoPago>
               <tns:conciliadas>
                  <xsl:value-of select="ns0:conciliadas"/>
               </tns:conciliadas>
               <tns:beneficio>
                  <xsl:value-of select="ns0:beneficio"/>
               </tns:beneficio>
               <tns:sitioBeneficio>
                  <xsl:value-of select="ns0:sitioBeneficio"/>
               </tns:sitioBeneficio>
               <tns:fechaPago>
                  <xsl:value-of select="ns0:fechaPago"/>
               </tns:fechaPago>
               <tns:monedaPago>
                  <xsl:value-of select="ns0:monedaPago"/>
               </tns:monedaPago>
               <tns:direccionPago>
                  <xsl:value-of select="ns0:direccionPago"/>
               </tns:direccionPago>
               <tns:noCuentaPago>
                  <xsl:value-of select="ns0:noCuentaPago"/>
               </tns:noCuentaPago>
               <tns:proveedorParte>
                  <xsl:value-of select="ns0:proveedorParte"/>
               </tns:proveedorParte>
               <tns:sitioProveedor>
                  <xsl:value-of select="ns0:sitioProveedor"/>
               </tns:sitioProveedor>
               <tns:unidadNegocio>
                  <xsl:value-of select="ns0:unidadNegocio"/>
               </tns:unidadNegocio>
               <tns:nomBancoPagador>
                  <xsl:value-of select="ns0:nomBancoPagador"/>
               </tns:nomBancoPagador>
               <tns:fecPagoBanco>
                  <xsl:value-of select="ns0:fecPagoBanco"/>
               </tns:fecPagoBanco>
               <tns:importePagadoBanco>
                  <xsl:value-of select="ns0:importePagadoBanco"/>
               </tns:importePagadoBanco>
               <tns:cuentaBancariaPago>
                  <xsl:value-of select="ns0:cuentaBancariaPago"/>
               </tns:cuentaBancariaPago>
               <tns:importPagoBanco>
                  <xsl:value-of select="ns0:importPagoBanco"/>
               </tns:importPagoBanco>
               <tns:nombreActual>
                  <xsl:value-of select="ns0:nombreActual"/>
               </tns:nombreActual>
               <tns:detalles>
                  <xsl:value-of select="ns0:detalles"/>
               </tns:detalles>
               <tns:tercerSegmCotable>
                  <xsl:value-of select="ns0:tercerSegmCotable"/>
               </tns:tercerSegmCotable>
               <tns:conceptoCuenCotble3>
                  <xsl:value-of select="ns0:conceptoCuenCotble3"/>
               </tns:conceptoCuenCotble3>
               <tns:quintoSegmContable>
                  <xsl:value-of select="ns0:quintoSegmContable"/>
               </tns:quintoSegmContable>
               <tns:conceptoCuenContable5>
                  <xsl:value-of select="ns0:conceptoCuenContable5"/>
               </tns:conceptoCuenContable5>
               <tns:tipoComprobante>
                  <xsl:value-of select="ns0:tipoComprobante"/>
               </tns:tipoComprobante>
               <tns:fechaTimbrado>
                  <xsl:value-of select="ns0:fechaTimbrado"/>
               </tns:fechaTimbrado>
               <tns:tipoRelacion>
                  <xsl:value-of select="ns0:tipoRelacion"/>
               </tns:tipoRelacion>
               <tns:uuidRelacion>
                  <xsl:value-of select="ns0:uuidRelacion"/>
               </tns:uuidRelacion>
               <tns:nombreEmisor>
                  <xsl:value-of select="ns0:nombreEmisor"/>
               </tns:nombreEmisor>
               <tns:usoCfdi>
                  <xsl:value-of select="ns0:usoCfdi"/>
               </tns:usoCfdi>
               <tns:subtotal>
                  <xsl:value-of select="ns0:subtotal"/>
               </tns:subtotal>
               <tns:descuento>
                  <xsl:value-of select="ns0:descuento"/>
               </tns:descuento>
               <tns:totalIeps>
                  <xsl:value-of select="ns0:totalIeps"/>
               </tns:totalIeps>
               <tns:iva16>
                  <xsl:value-of select="ns0:iva16"/>
               </tns:iva16>
               <tns:retenidoIva>
                  <xsl:value-of select="ns0:retenidoIva"/>
               </tns:retenidoIva>
               <tns:retenidoIsr>
                  <xsl:value-of select="ns0:retenidoIsr"/>
               </tns:retenidoIsr>
               <tns:ish>
                  <xsl:value-of select="ns0:ish"/>
               </tns:ish>
               <tns:total>
                  <xsl:value-of select="ns0:total"/>
               </tns:total>
               <tns:moneda>
                  <xsl:value-of select="ns0:moneda"/>
               </tns:moneda>
               <tns:tipoCambio>
                  <xsl:value-of select="ns0:tipoCambio"/>
               </tns:tipoCambio>
               <tns:formaPago>
                  <xsl:value-of select="ns0:formaPago"/>
               </tns:formaPago>
               <tns:metodoPago>
                  <xsl:value-of select="ns0:metodoPago"/>
               </tns:metodoPago>
               <tns:conceptos>
                  <xsl:value-of select="ns0:conceptos"/>
               </tns:conceptos>
               <tns:combustible>
                  <xsl:value-of select="ns0:combustible"/>
               </tns:combustible>
               <tns:iva8>
                  <xsl:value-of select="ns0:iva8"/>
               </tns:iva8>
               <tns:estatusValidacion>
                  <xsl:value-of select="ns0:estatusValidacion"/>
               </tns:estatusValidacion>
               <tns:estatusValidacionDesc>
                  <xsl:value-of select="ns0:estatusValidacionDesc"/>
               </tns:estatusValidacionDesc>
            </tns:XxerInvoicesApTbl>
         </xsl:for-each>
      </tns:GetReportValidationResponse>
   </xsl:template>
</xsl:stylesheet>