<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://soa.estrellaroja.com.mx/ValidacionAutomaticaConsulta" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://soa.estrellaroja.com.mx/ValidacionAutomaticTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/ValidacionAutomaticaConsulta.xsd"/>
            <oracle-xsl-mapper:rootElement name="PostValidationConsultResponse" namespace="http://soa.estrellaroja.com.mx/ValidacionAutomaticaConsulta"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ValidacionAutomaticTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="ValidationConsultResponse" namespace="http://soa.estrellaroja.com.mx/ValidacionAutomaticTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED JUL 21 17:13:22 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ValidationConsultResponse>
         <tns:Return>
            <cmn:Success/>
         </tns:Return>
         <tns:responseCode>
            <xsl:value-of select="/ns0:PostValidationConsultResponse/ns0:responseCode"/>
         </tns:responseCode>
         <tns:message>
            <xsl:value-of select="/ns0:PostValidationConsultResponse/ns0:message"/>
         </tns:message>
         <tns:data>
            <tns:codigoEstatus>
               <xsl:value-of select="/ns0:PostValidationConsultResponse/ns0:data/ns0:codigoEstatus"/>
            </tns:codigoEstatus>
            <tns:esCancelable>
                           <xsl:value-of select="/ns0:PostValidationConsultResponse/ns0:data/ns0:esCancelable"/>
            </tns:esCancelable>
            <tns:estado>
               <xsl:value-of select="/ns0:PostValidationConsultResponse/ns0:data/ns0:estado"/>
            </tns:estado>
            <tns:estatusCancelacion>
                           <xsl:value-of select="/ns0:PostValidationConsultResponse/ns0:data/ns0:estatusCancelacion"/>
            </tns:estatusCancelacion>
            <tns:expresionImpresa>
               <xsl:value-of select="/ns0:PostValidationConsultResponse/ns0:data/ns0:expresionImpresa"/>
            </tns:expresionImpresa>
         </tns:data>
      </tns:ValidationConsultResponse>
   </xsl:template>
</xsl:stylesheet>