<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbXXER_JOBS_REQUEST" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/AuditControlTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="CreateJobsStatusRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/External/Audit/dbXXER_JOBS_REQUEST_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="XxerJobsRequestCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbXXER_JOBS_REQUEST"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED DEC 13 09:53:10 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:XxerJobsRequestCollection>
         <tns:XxerJobsRequest>
            <tns:integrationName>
               <xsl:value-of select="/ns0:CreateJobsStatusRq/ns0:Process/ns0:IntegrationName"/>
            </tns:integrationName>
            <tns:instanceNumber>
               <xsl:value-of select="/ns0:CreateJobsStatusRq/ns0:Process/ns0:InstanceId"/>
            </tns:instanceNumber>
            <xsl:for-each select="/ns0:CreateJobsStatusRq/ns0:Jobs/ns0:Job">
               <xsl:choose>
                  <!--FileImport-->
                  <xsl:when test="ns0:Name = &quot;FileImport&quot;">
                     <xsl:if test="ns0:RequestId">
                        <tns:requestUcmId>
                           <xsl:value-of select="ns0:RequestId"/>
                        </tns:requestUcmId>
                     </xsl:if>
                     <xsl:if test="ns0:Status">
                        <tns:requestUcmStatus>
                           <xsl:value-of select="ns0:Status"/>
                        </tns:requestUcmStatus>
                     </xsl:if>
                  </xsl:when>
                  <!--LoadInterface-->
                  <xsl:when test="ns0:Name = &quot;LoadInterface&quot;">
                     <xsl:if test="ns0:RequestId">
                        <tns:requestIntId>
                           <xsl:value-of select="ns0:RequestId"/>
                        </tns:requestIntId>
                     </xsl:if>
                     <xsl:if test="ns0:Status">
                        <tns:requestIntStatus>
                           <xsl:value-of select="ns0:Status"/>
                        </tns:requestIntStatus>
                     </xsl:if>
                  </xsl:when>
                  <!--ImportToERPCloud-->
                  <xsl:when test="ns0:Name = &quot;ImportToERPCloud&quot;">
                     <xsl:if test="ns0:RequestId">
                        <tns:requestId>
                           <xsl:value-of select="ns0:RequestId"/>
                        </tns:requestId>
                     </xsl:if>
                     <xsl:if test="ns0:Status">
                        <tns:requestStatus>
                           <xsl:value-of select="ns0:Status"/>
                        </tns:requestStatus>
                     </xsl:if>
                  </xsl:when>
               </xsl:choose>
            </xsl:for-each>
            <tns:creationdate>
               <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:creationdate>
            <tns:createdby>AuditControlTec</tns:createdby>
         </tns:XxerJobsRequest>
      </tns:XxerJobsRequestCollection>
   </xsl:template>
</xsl:stylesheet>