<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbArElecInvoiceBs" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../Schemas/AuditControlTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="InsertArElecInvoiceRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../Schemas/External/dbaArElecInvoice_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="XxerArElecInvoiceCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbArElecInvoiceBs"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON DEC 11 16:09:30 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:XxerArElecInvoiceCollection>
         <tns:XxerArElecInvoice>
            <tns:customerTrxId>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:customerTrxId"/>
            </tns:customerTrxId>
            <tns:numeroFactura>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:numeroFactura"/>
            </tns:numeroFactura>
            <tns:tipocfd>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:tipocfd"/>
            </tns:tipocfd>
            <tns:uuid>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:uuid"/>
            </tns:uuid>
            <tns:payload>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:payload"/>
            </tns:payload>
            <tns:attribute1>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:attribute1"/>
            </tns:attribute1>
            <tns:attribute2>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:attribute2"/>
            </tns:attribute2>
            <tns:attribute3>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:attribute3"/>
            </tns:attribute3>
            <tns:attribute4>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:attribute4"/>
            </tns:attribute4>
            <tns:attribute5>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:attribute5"/>
            </tns:attribute5>
            <tns:creationDate>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:creationDate"/>
            </tns:creationDate>
            <tns:lastUpdateDate>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:lastUpdateDate"/>
            </tns:lastUpdateDate>
            <tns:createdBy>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:createdBy"/>
            </tns:createdBy>
            <tns:lastUpdatedBy>
               <xsl:value-of select="/ns0:InsertArElecInvoiceRq/ns0:ElecInvoice/ns0:lastUpdatedBy"/>
            </tns:lastUpdatedBy>
         </tns:XxerArElecInvoice>
      </tns:XxerArElecInvoiceCollection>
   </xsl:template>
</xsl:stylesheet>