<wsdl:definitions name="EAMUpdateWorkOrders" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_ESTRELLA_ROJA/DEV_EAMWorkOrdersTec/EAMUpdateWorkOrders" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_ESTRELLA_ROJA/DEV_EAMWorkOrdersTec/EAMUpdateWorkOrders" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EAMUpdateWorkOrders" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="EAMUpdateWorkOrders_plt">
    <plt:role name="EAMUpdateWorkOrders_role">
      <plt:portType name="tns:EAMUpdateWorkOrders_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EAMUpdateWorkOrders" schemaLocation="../../XSD/TransactionalWorkOrders/EAMUpdateWorkOrdersXSD.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="XxerZamWoBlksTblCollection_msg">
        <wsdl:part name="XxerZamWoBlksTblCollection" element="top:XxerZamWoBlksTblCollection"/>
    </wsdl:message>
    <wsdl:portType name="EAMUpdateWorkOrders_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:XxerZamWoBlksTblCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>