<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://soa.estrellaroja.com.mx/FinancialsTec" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/dbaReadCustomers" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/dbaReadCustomers.xsd"/>
            <oracle-xsl-mapper:rootElement name="dbaReadCustomersOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbaReadCustomers"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/FinancialsTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetCustomersRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON DEC 11 16:12:47 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetCustomersRs>
         <cmn:Success/>
         <tns:Return>
            <xsl:for-each select="/ns0:dbaReadCustomersOutputCollection/ns0:dbaReadCustomersOutput">
               <tns:Customer>
                  <xsl:if test="string-length (ns0:CustomerId ) > 0">
                     <tns:CustomerId>
                        <xsl:value-of select="ns0:CustomerId"/>
                     </tns:CustomerId>
                  </xsl:if>
                  <xsl:if test="string-length (ns0:Name ) > 0">
                     <tns:Name>
                        <xsl:if test="ns0:Name/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Name/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Name"/>
                     </tns:Name>
                  </xsl:if>
                  <xsl:if test="string-length (ns0:LastName ) > 0">
                     <tns:LastName>
                        <xsl:value-of select="ns0:LastName"/>
                     </tns:LastName>
                  </xsl:if>
                  <xsl:if test="string-length (ns0:PaymentTerms ) > 0">
                     <tns:PaymentTerms>
                        <xsl:value-of select="ns0:PaymentTerms"/>
                     </tns:PaymentTerms>
                  </xsl:if>
                  <xsl:if test="string-length (ns0:FiscalCode ) > 0">
                     <tns:FiscalCode>
                        <xsl:if test="ns0:FiscalCode/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:FiscalCode/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:FiscalCode"/>
                     </tns:FiscalCode>
                  </xsl:if>
                  <xsl:if test="string-length (ns0:DunsNumber ) > 0">
                     <tns:DunsNumber>
                        <xsl:if test="ns0:DunsNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:DunsNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:DunsNumber"/>
                     </tns:DunsNumber>
                  </xsl:if>
                  <xsl:if test="string-length (ns0:AccountName ) > 0">
                     <tns:AccountName>
                        <xsl:value-of select="ns0:AccountName"/>
                     </tns:AccountName>
                  </xsl:if>
                  <tns:CustomerType>
                     <xsl:if test="ns0:CustomerType/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CustomerType/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CustomerType"/>
                  </tns:CustomerType>
                  <tns:AccountId>
                     <xsl:value-of select="ns0:AccountId"/>
                  </tns:AccountId>
                  <tns:replicationInd>
                     <xsl:value-of select="ns0:ReplicationInd"/>
                  </tns:replicationInd>
                  <tns:replicationMsg>
                     <xsl:value-of select="ns0:ReplicationMsg"/>
                  </tns:replicationMsg>
               </tns:Customer>
            </xsl:for-each>
         </tns:Return>
      </tns:GetCustomersRs>
   </xsl:template>
</xsl:stylesheet>