<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbGetTransactionsReconcile" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://soa.estrellaroja.com.mx/FinancialsTec" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/dbGetTransactionsReconcile_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbGetTransactionsReconcile"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/FinancialsTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetTransactionsReconcileRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU MAY 20 13:51:48 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetTransactionsReconcileRs>
         <xsl:choose>
            <xsl:when test="string-length (/ns0:OutputParameters/ns0:P_ERROR_DESC )=0">
               <cmn:Success/>
            </xsl:when>
         </xsl:choose>
         <xsl:choose>
            <xsl:when test="string-length (/ns0:OutputParameters/ns0:P_ERROR_DESC )>0">
               <cmn:Errors>
                  <cmn:Error>
                     <cmn:ErrorCode>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_ERROR"/>
                     </cmn:ErrorCode>
                     <cmn:ShortDescription>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_ERROR_DESC"/>
                     </cmn:ShortDescription>
                     <cmn:Description>
                        <xsl:value-of select="concat (/ns0:OutputParameters/ns0:P_ERROR, ' - ', /ns0:OutputParameters/ns0:P_ERROR_DESC )"/>
                     </cmn:Description>
                     <cmn:BusinessProcess>Error in  PROCEDURE GET_TRANSACTIONS_RECONCILE</cmn:BusinessProcess>
                     <cmn:FailedService>XXER_UTILITIES_PKG.GET_TRANSACTIONS_RECONCILE</cmn:FailedService>
                     <cmn:TimeStamp>
                        <xsl:value-of select="xp20:current-dateTime ( )"/>
                     </cmn:TimeStamp>
                  </cmn:Error>
               </cmn:Errors>
            </xsl:when>
         </xsl:choose>

         <tns:Return>
            <xsl:for-each select="/ns0:OutputParameters/ns0:P_TRANSACTIONS_RECONCILE/ns0:P_TRANSACTIONS_RECONCILE_ITEM">
               <tns:Reconciliations>
                  <tns:REFERENCE_PAYMENT>
                     <xsl:value-of select="ns0:REFERENCE_PAYMENT"/>
                  </tns:REFERENCE_PAYMENT>
                  <tns:RECEIPT_METHOD>
                     <xsl:value-of select="ns0:RECEIPT_METHOD"/>
                  </tns:RECEIPT_METHOD>
                  <tns:RECEIPT_METHOD_ID>
                     <xsl:value-of select="ns0:RECEIPT_METHOD_ID"/>
                  </tns:RECEIPT_METHOD_ID>
                  <tns:ORGANIZATION_ID>
                     <xsl:value-of select="ns0:ORGANIZATION_ID"/>
                  </tns:ORGANIZATION_ID>
                  <tns:TOLERANCE>
                     <xsl:value-of select="ns0:TOLERANCE"/>
                  </tns:TOLERANCE>
                  <tns:FREQUENCY>
                     <xsl:value-of select="ns0:FREQUENCY"/>
                  </tns:FREQUENCY>
                  <tns:RFC>
                     <xsl:value-of select="ns0:RFC"/>
                  </tns:RFC>
                  <xsl:for-each select="ns0:TRANSACTIONS/ns0:TRANSACTIONS_ITEM">
                     <tns:TRANSACTIONS>
                        <tns:TRANSACTION_NUMBER>
                           <xsl:value-of select="ns0:INVOICE_NUMBER"/>
                        </tns:TRANSACTION_NUMBER>
                        <tns:ID_TRANSACTION>
                           <xsl:value-of select="ns0:INVOICE_ID"/>
                        </tns:ID_TRANSACTION>
                        <tns:TRANSACTION_DATE>
                           <xsl:value-of select="ns0:INVOICE_DATE"/>
                        </tns:TRANSACTION_DATE>
                        <tns:TRANSACTION_AMOUNT>
                           <xsl:value-of select="ns0:AMOUNT_LINE"/>
                        </tns:TRANSACTION_AMOUNT>
                     </tns:TRANSACTIONS>
                  </xsl:for-each>
               </tns:Reconciliations>
            </xsl:for-each>
         </tns:Return>
      </tns:GetTransactionsReconcileRs>
   </xsl:template>
</xsl:stylesheet>