<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbaUpdateConciliations" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://soa.estrellaroja.com.mx/FinancialsTec" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/FinancialsTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="UpdateConciliationsRq" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/dbaUpdateConciliations_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbaUpdateConciliations"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED JUN 02 10:07:33 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <tns:P_CONCILIATIONS>
            <xsl:for-each select="/ns0:UpdateConciliationsRq/ns0:Conciliation">
               <tns:P_CONCILIATIONS_ITEM>
                  <tns:REFERENCE_PAYMENT>
                     <xsl:value-of select="ns0:PaymentReference"/>
                  </tns:REFERENCE_PAYMENT>
                  <tns:PAYMENT_NUMBER>
                     <xsl:value-of select="ns0:PaymentNumber"/>
                  </tns:PAYMENT_NUMBER>
                  <tns:AMOUNT_TRANSACTIONS>
                     <xsl:value-of select="ns0:TotalTransactions"/>
                  </tns:AMOUNT_TRANSACTIONS>
                  <tns:AMOUNT_PAYMENT>
                     <xsl:value-of select="ns0:TotalPayment"/>
                  </tns:AMOUNT_PAYMENT>
                  <tns:TOLERANCE>
                     <xsl:value-of select="ns0:Tolerance"/>
                  </tns:TOLERANCE>
                  <tns:STATUS>
                     <xsl:value-of select="ns0:Status"/>
                  </tns:STATUS>
                  <tns:MSJ_VALIDATION>
                     <xsl:value-of select="ns0:ValidationMsj"/>
                  </tns:MSJ_VALIDATION>
                  <tns:REFERENCE_TRANSACTIONS_ID>
                     <xsl:value-of select="ns0:IdTransactionReference"/>
                  </tns:REFERENCE_TRANSACTIONS_ID>
                  <tns:REFERENCE_TRANSACTIONS>
                     <xsl:value-of select="ns0:TransactionsReference"/>
                  </tns:REFERENCE_TRANSACTIONS>
                  <tns:METODO_RECIBO>
                     <xsl:value-of select="ns0:ReceiptMethod"/>
                  </tns:METODO_RECIBO>
               </tns:P_CONCILIATIONS_ITEM>
            </xsl:for-each>
         </tns:P_CONCILIATIONS>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>