<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbComplementsAP" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../Schemas/External/dbComplementsAP_table.xsd"/>
        <oracle-xsl-mapper:rootElement name="XxerComplementsApTblCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbComplementsAP"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../Schemas/AuditControlTec.xsd"/>
        <oracle-xsl-mapper:rootElement name="GetComplementsAPRs" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [FRI AUG 13 16:20:16 CDT 2021].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:GetComplementsAPRs>
     <xsl:if test="count (/ns0:XxerComplementsApTblCollection/ns0:XxerComplementsApTbl ) > 0">
            <cmn:Success/>
         </xsl:if>
         <xsl:if test="count (/ns0:XxerComplementsApTblCollection/ns0:XxerComplementsApTbl ) = 0">
            <cmn:Errors>
               <cmn:Error>
                  <cmn:ErrorCode>SOA-0010</cmn:ErrorCode>
                  <cmn:ShortDescription>No Data Found</cmn:ShortDescription>
                  <cmn:Description>No data found with parameter values</cmn:Description>
                  <cmn:BusinessProcess>AuditControlTec</cmn:BusinessProcess>
                  <cmn:FailedService>GetComplementsAP</cmn:FailedService>
                  <cmn:TimeStamp>
                     <xsl:value-of select="xp20:current-dateTime ( )"/>
                  </cmn:TimeStamp>
               </cmn:Error>
            </cmn:Errors>
         </xsl:if>
         <xsl:if test="count (/ns0:XxerComplementsApTblCollection/ns0:XxerComplementsApTbl ) > 0">
      <tns:Return>
        <tns:Complements>
          <xsl:for-each select="/ns0:XxerComplementsApTblCollection/ns0:XxerComplementsApTbl">
            <tns:Complement>
              <tns:paymentId>
                <xsl:value-of select="ns0:paymentId"/>
              </tns:paymentId>
              <tns:paymentNumber>
                <xsl:value-of select="ns0:paymentNumber"/>
              </tns:paymentNumber>
              <tns:nombreEmisor>
                <xsl:value-of select="ns0:nombreEmisor"/>
              </tns:nombreEmisor>
              <tns:emisorRfc>
                <xsl:value-of select="ns0:emisorRfc"/>
              </tns:emisorRfc>
              <tns:nombrePreceptor>
                <xsl:value-of select="ns0:nombrePreceptor"/>
              </tns:nombrePreceptor>
              <tns:receptorRfc>
                <xsl:value-of select="ns0:receptorRfc"/>
              </tns:receptorRfc>
              <tns:paymentAmount>
                <xsl:value-of select="ns0:paymentAmount"/>
              </tns:paymentAmount>
              <tns:paymentCurrency>
                <xsl:value-of select="ns0:paymentCurrency"/>
              </tns:paymentCurrency>
              <tns:paymentDate>
                <xsl:value-of select="ns0:paymentDate"/>
              </tns:paymentDate>
              <tns:status>
                <xsl:value-of select="ns0:status"/>
              </tns:status>
              <tns:statusDesc>
                <xsl:value-of select="ns0:statusDesc"/>
              </tns:statusDesc>
              <tns:folioXml>
                <xsl:value-of select="ns0:folioXml"/>
              </tns:folioXml>
              <tns:serieXml>
                <xsl:value-of select="ns0:serieXml"/>
              </tns:serieXml>
              <tns:nombreEmisorXml>
                <xsl:value-of select="ns0:nombreEmisorXml"/>
              </tns:nombreEmisorXml>
              <tns:emisorRfcXml>
                <xsl:value-of select="ns0:emisorRfcXml"/>
              </tns:emisorRfcXml>
              <tns:nombreReceptorXml>
                <xsl:value-of select="ns0:nombreReceptorXml"/>
              </tns:nombreReceptorXml>
              <tns:receptorRfcXml>
                <xsl:value-of select="ns0:receptorRfcXml"/>
              </tns:receptorRfcXml>
              <tns:totalXml>
                <xsl:value-of select="ns0:totalXml"/>
              </tns:totalXml>
              <tns:subtotalXml>
                <xsl:value-of select="ns0:subtotalXml"/>
              </tns:subtotalXml>
              <tns:tipoCambioXml>
                <xsl:value-of select="ns0:tipoCambioXml"/>
              </tns:tipoCambioXml>
              <tns:monedaXml>
                <xsl:value-of select="ns0:monedaXml"/>
              </tns:monedaXml>
              <tns:usoCfdiXml>
                <xsl:value-of select="ns0:usoCfdiXml"/>
              </tns:usoCfdiXml>
              <tns:formaPagoXml>
                <xsl:value-of select="ns0:formaPagoXml"/>
              </tns:formaPagoXml>
              <tns:tipoComprobanteXml>
                <xsl:value-of select="ns0:tipoComprobanteXml"/>
              </tns:tipoComprobanteXml>
              <tns:descripcionXml>
                <xsl:value-of select="ns0:descripcionXml"/>
              </tns:descripcionXml>
              <tns:uuidXml>
                <xsl:value-of select="ns0:uuidXml"/>
              </tns:uuidXml>
              <tns:fechaXml>
                <xsl:value-of select="ns0:fechaXml"/>
              </tns:fechaXml>
              <tns:fechaTimbradoXml>
                <xsl:value-of select="ns0:fechaTimbradoXml"/>
              </tns:fechaTimbradoXml>
              <tns:attribute1>
                <xsl:value-of select="ns0:attribute1"/>
              </tns:attribute1>
              <tns:attribute2>
                <xsl:value-of select="ns0:attribute2"/>
              </tns:attribute2>
              <tns:attribute3>
                <xsl:value-of select="ns0:attribute3"/>
              </tns:attribute3>
              <tns:attribute4>
                <xsl:value-of select="ns0:attribute4"/>
              </tns:attribute4>
              <tns:attribute5>
                <xsl:value-of select="ns0:attribute5"/>
              </tns:attribute5>
              <tns:createdBy>
                <xsl:value-of select="ns0:createdBy"/>
              </tns:createdBy>
              <tns:creationDate>
                <xsl:value-of select="ns0:creationDate"/>
              </tns:creationDate>
              <tns:lastUpdatedBy>
                <xsl:value-of select="ns0:lastUpdatedBy"/>
              </tns:lastUpdatedBy>
              <tns:lastUpdateDate>
                <xsl:value-of select="ns0:lastUpdateDate"/>
              </tns:lastUpdateDate>
              <tns:objectVersionNumber>
                <xsl:value-of select="ns0:objectVersionNumber"/>
              </tns:objectVersionNumber>
              <tns:objetoImpXml>
                <xsl:value-of select="ns0:objetoImpXml"/>
              </tns:objetoImpXml>
              <tns:receptorRegimenXml>
                <xsl:value-of select="ns0:receptorRegimenXml"/>
              </tns:receptorRegimenXml>
              <tns:emisorRegimenXml>
                <xsl:value-of select="ns0:emisorRegimenXml"/>
              </tns:emisorRegimenXml>
              <tns:receptorRegimen>
                <xsl:value-of select="ns0:receptorRegimen"/>
              </tns:receptorRegimen>
              <tns:emisorRegimen>
                <xsl:value-of select="ns0:emisorRegimen"/>
              </tns:emisorRegimen>
              <tns:versionXml>
                <xsl:value-of select="ns0:versionXml"/>
              </tns:versionXml>
              <tns:ComplementsLinesAp>
                <xsl:for-each select="ns0:xxerComplementsLinesApTblCollection/ns0:XxerComplementsLinesApTbl">
                  <tns:XxerComplementsLinesApTbl>
                    <tns:drId>
                      <xsl:value-of select="ns0:drId"/>
                    </tns:drId>
                    <tns:invoiceId>
                      <xsl:value-of select="ns0:invoiceId"/>
                    </tns:invoiceId>
                    <tns:status>
                      <xsl:value-of select="ns0:status"/>
                    </tns:status>
                    <tns:statusDesc>
                      <xsl:value-of select="ns0:statusDesc"/>
                    </tns:statusDesc>
                    <tns:folioDrXml>
                      <xsl:value-of select="ns0:folioDrXml"/>
                    </tns:folioDrXml>
                    <tns:serieDrXml>
                      <xsl:value-of select="ns0:serieDrXml"/>
                    </tns:serieDrXml>
                    <tns:uuidDrXml>
                      <xsl:value-of select="ns0:uuidDrXml"/>
                    </tns:uuidDrXml>
                    <tns:impSaldoAntDrXml>
                      <xsl:value-of select="ns0:impSaldoAntDrXml"/>
                    </tns:impSaldoAntDrXml>
                    <tns:impPagoDrXml>
                      <xsl:value-of select="ns0:impPagoDrXml"/>
                    </tns:impPagoDrXml>
                    <tns:impSaldoInsolutoDrXml>
                      <xsl:value-of select="ns0:impSaldoInsolutoDrXml"/>
                    </tns:impSaldoInsolutoDrXml>
                    <tns:monedaDrXml>
                      <xsl:value-of select="ns0:monedaDrXml"/>
                    </tns:monedaDrXml>
                    <tns:metodoPagoDrXml>
                      <xsl:value-of select="ns0:metodoPagoDrXml"/>
                    </tns:metodoPagoDrXml>
                    <tns:tipoCambioDrXml>
                      <xsl:value-of select="ns0:tipoCambioDrXml"/>
                    </tns:tipoCambioDrXml>
                    <tns:formaPagoDrXml>
                      <xsl:value-of select="ns0:formaPagoDrXml"/>
                    </tns:formaPagoDrXml>
                    <tns:fechaDrXml>
                      <xsl:value-of select="ns0:fechaDrXml"/>
                    </tns:fechaDrXml>
                    <tns:attribute1>
                      <xsl:value-of select="ns0:attribute1"/>
                    </tns:attribute1>
                    <tns:attribute2>
                      <xsl:value-of select="ns0:attribute2"/>
                    </tns:attribute2>
                    <tns:attribute3>
                      <xsl:value-of select="ns0:attribute3"/>
                    </tns:attribute3>
                    <tns:attribute4>
                      <xsl:value-of select="ns0:attribute4"/>
                    </tns:attribute4>
                    <tns:attribute5>
                      <xsl:value-of select="ns0:attribute5"/>
                    </tns:attribute5>
                    <tns:createdBy>
                      <xsl:value-of select="ns0:createdBy"/>
                    </tns:createdBy>
                    <tns:creationDate>
                      <xsl:value-of select="ns0:creationDate"/>
                    </tns:creationDate>
                    <tns:lastUpdatedBy>
                      <xsl:value-of select="ns0:lastUpdatedBy"/>
                    </tns:lastUpdatedBy>
                    <tns:lastUpdateDate>
                      <xsl:value-of select="ns0:lastUpdateDate"/>
                    </tns:lastUpdateDate>
                    <tns:objectVersionNumber>
                      <xsl:value-of select="ns0:objectVersionNumber"/>
                    </tns:objectVersionNumber>
                    <tns:objetoImpDrXml>
                      <xsl:value-of select="ns0:objetoImpDrXml"/>
                    </tns:objetoImpDrXml>
                  </tns:XxerComplementsLinesApTbl>
                </xsl:for-each>
              </tns:ComplementsLinesAp>
            </tns:Complement>
          </xsl:for-each>
        </tns:Complements>
      </tns:Return>
      </xsl:if>
    </tns:GetComplementsAPRs>
  </xsl:template>
</xsl:stylesheet>