<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.oracle.com/oxp/service/v2" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDL/Externals/ReportService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="runDataModelResponse" namespace="http://xmlns.oracle.com/oxp/service/v2"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="RunDataModelRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED JUL 12 16:05:49 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:RunDataModelRs>
         <xsl:if test="/ns0:runDataModelResponse/ns0:runDataModelReturn">
            <cmn:Success/>
         </xsl:if>
         <tns:Return>
            <tns:metaDataList>
               <xsl:if test="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:metaDataList/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:metaDataList/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <tns:metaDataList>
                  <xsl:if test="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:metaDataList/ns0:metaDataList/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:metaDataList/ns0:metaDataList/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:for-each select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:metaDataList/ns0:metaDataList/ns0:item">
                     <tns:item>
                        <tns:metaDataName>
                           <xsl:if test="ns0:metaDataName/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="ns0:metaDataName/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="ns0:metaDataName"/>
                        </tns:metaDataName>
                        <tns:metaDataValue>
                           <xsl:if test="ns0:metaDataValue/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="ns0:metaDataValue/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="ns0:metaDataValue"/>
                        </tns:metaDataValue>
                     </tns:item>
                  </xsl:for-each>
               </tns:metaDataList>
            </tns:metaDataList>
            <tns:reportBytes>
               <xsl:if test="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportBytes/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportBytes/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportBytes"/>
            </tns:reportBytes>
            <tns:reportContentType>
               <xsl:if test="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportContentType/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportContentType/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportContentType"/>
            </tns:reportContentType>
            <tns:reportFileID>
               <xsl:if test="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportFileID/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportFileID/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportFileID"/>
            </tns:reportFileID>
            <tns:reportLocale>
               <xsl:if test="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportLocale/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportLocale/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:runDataModelResponse/ns0:runDataModelReturn/ns0:reportLocale"/>
            </tns:reportLocale>
         </tns:Return>
      </tns:RunDataModelRs>
   </xsl:template>
</xsl:stylesheet>