<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns1="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns3="http://xmlns.oracle.com/adf/svc/types/" xmlns:ns4="commonj.sdo/xml" xmlns:ns5="commonj.sdo/java" xmlns:ns6="commonj.sdo" xmlns:ns2="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="UpdateObjectRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/Modules/Cloud/ErpObjectDFFUpdate/ErpObjectDFFUpdate.xsd"/>
            <oracle-xsl-mapper:rootElement name="updateDffEntityDetails" namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE JUL 18 13:42:38 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:updateDffEntityDetails>
         <xsl:if test="/ns0:UpdateObjectRq/ns0:document">
            <tns:document>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:document/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <ns2:Content>
                  <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:Content/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:Content/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:Content"/>
               </ns2:Content>
               <ns2:FileName>
                  <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:FileName/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:FileName/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:FileName"/>
               </ns2:FileName>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:ContentType">
                  <ns2:ContentType>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:ContentType/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:ContentType/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:ContentType"/>
                  </ns2:ContentType>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentTitle">
                  <ns2:DocumentTitle>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentTitle/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentTitle/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentTitle"/>
                  </ns2:DocumentTitle>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentAuthor">
                  <ns2:DocumentAuthor>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentAuthor/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentAuthor/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentAuthor"/>
                  </ns2:DocumentAuthor>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentSecurityGroup">
                  <ns2:DocumentSecurityGroup>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentSecurityGroup/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentSecurityGroup/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentSecurityGroup"/>
                  </ns2:DocumentSecurityGroup>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentAccount">
                  <ns2:DocumentAccount>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentAccount/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentAccount/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentAccount"/>
                  </ns2:DocumentAccount>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentName">
                  <ns2:DocumentName>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentName"/>
                  </ns2:DocumentName>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentId">
                  <ns2:DocumentId>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:document/ns0:DocumentId"/>
                  </ns2:DocumentId>
               </xsl:if>
            </tns:document>
         </xsl:if>
         <xsl:if test="string-length (/ns0:UpdateObjectRq/ns0:operationMode ) > 0">
            <tns:operationMode>
               <xsl:value-of select="/ns0:UpdateObjectRq/ns0:operationMode"/>
            </tns:operationMode>
         </xsl:if>
         <xsl:if test="/ns0:UpdateObjectRq/ns0:object">
            <tns:object>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:object/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:EntityName">
                  <ns2:EntityName>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:EntityName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:EntityName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:EntityName"/>
                  </ns2:EntityName>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:ContextValue">
                  <ns2:ContextValue>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:ContextValue/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:ContextValue/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:ContextValue"/>
                  </ns2:ContextValue>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyA">
                  <ns2:UserKeyA>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyA/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyA/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyA"/>
                  </ns2:UserKeyA>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyB">
                  <ns2:UserKeyB>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyB/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyB/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyB"/>
                  </ns2:UserKeyB>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyC">
                  <ns2:UserKeyC>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyC/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyC/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyC"/>
                  </ns2:UserKeyC>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyD">
                  <ns2:UserKeyD>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyD/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyD/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyD"/>
                  </ns2:UserKeyD>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyE">
                  <ns2:UserKeyE>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyE/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyE/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:UserKeyE"/>
                  </ns2:UserKeyE>
               </xsl:if>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:DFFAttributes">
                  <ns2:DFFAttributes>
                     <xsl:if test="/ns0:UpdateObjectRq/ns0:object/ns0:DFFAttributes/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:DFFAttributes/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:object/ns0:DFFAttributes"/>
                  </ns2:DFFAttributes>
               </xsl:if>
            </tns:object>
         </xsl:if>
         <xsl:if test="/ns0:UpdateObjectRq/ns0:notificationCode">
            <tns:notificationCode>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:notificationCode/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:notificationCode/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:UpdateObjectRq/ns0:notificationCode"/>
            </tns:notificationCode>
         </xsl:if>
         <xsl:if test="/ns0:UpdateObjectRq/ns0:callbackURL">
            <tns:callbackURL>
               <xsl:if test="/ns0:UpdateObjectRq/ns0:callbackURL/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:UpdateObjectRq/ns0:callbackURL/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:UpdateObjectRq/ns0:callbackURL"/>
            </tns:callbackURL>
         </xsl:if>
      </tns:updateDffEntityDetails>
   </xsl:template>
</xsl:stylesheet>