<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns3="http://xmlns.oracle.com/apps/financials/generalLedger/accounts/codeCombinations/publicFlex/Account/" xmlns:ns4="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns2="http://xmlns.oracle.com/adf/svc/types/" xmlns:ns5="commonj.sdo/xml" xmlns:ns6="commonj.sdo/java" xmlns:ns7="commonj.sdo" xmlns:ns1="http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="JournalImportRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/Modules/Cloud/JournalImport/JournalImportService.xsd"/>
            <oracle-xsl-mapper:rootElement name="importJournals" namespace="http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE JUL 18 12:50:26 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:importJournals>
         <tns:interfaceRows>
            <xsl:if test="/ns0:JournalImportRq/ns0:BatchName">
               <ns1:BatchName>
                  <xsl:if test="/ns0:JournalImportRq/ns0:BatchName/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:JournalImportRq/ns0:BatchName/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:JournalImportRq/ns0:BatchName"/>
               </ns1:BatchName>
            </xsl:if>
            <xsl:if test="/ns0:JournalImportRq/ns0:BatchDescription">
               <ns1:BatchDescription>
                  <xsl:if test="/ns0:JournalImportRq/ns0:BatchDescription/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:JournalImportRq/ns0:BatchDescription/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:JournalImportRq/ns0:BatchDescription"/>
               </ns1:BatchDescription>
            </xsl:if>
            <xsl:if test="/ns0:JournalImportRq/ns0:LedgerId">
               <ns1:LedgerId>
                  <xsl:if test="/ns0:JournalImportRq/ns0:LedgerId/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:JournalImportRq/ns0:LedgerId/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:JournalImportRq/ns0:LedgerId"/>
               </ns1:LedgerId>
            </xsl:if>
            <xsl:if test="/ns0:JournalImportRq/ns0:AccountingPeriodName">
               <ns1:AccountingPeriodName>
                  <xsl:if test="/ns0:JournalImportRq/ns0:AccountingPeriodName/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:JournalImportRq/ns0:AccountingPeriodName/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:JournalImportRq/ns0:AccountingPeriodName"/>
               </ns1:AccountingPeriodName>
            </xsl:if>
            <xsl:if test="/ns0:JournalImportRq/ns0:AccountingDate">
               <ns1:AccountingDate>
                  <xsl:if test="/ns0:JournalImportRq/ns0:AccountingDate/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:JournalImportRq/ns0:AccountingDate/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:JournalImportRq/ns0:AccountingDate"/>
               </ns1:AccountingDate>
            </xsl:if>
            <xsl:if test="/ns0:JournalImportRq/ns0:UserSourceName">
               <ns1:UserSourceName>
                  <xsl:if test="/ns0:JournalImportRq/ns0:UserSourceName/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:JournalImportRq/ns0:UserSourceName/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:JournalImportRq/ns0:UserSourceName"/>
               </ns1:UserSourceName>
            </xsl:if>
            <xsl:if test="/ns0:JournalImportRq/ns0:UserCategoryName">
               <ns1:UserCategoryName>
                  <xsl:if test="/ns0:JournalImportRq/ns0:UserCategoryName/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:JournalImportRq/ns0:UserCategoryName/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:JournalImportRq/ns0:UserCategoryName"/>
               </ns1:UserCategoryName>
            </xsl:if>
            <xsl:if test="/ns0:JournalImportRq/ns0:ErrorToSuspenseFlag">
               <ns1:ErrorToSuspenseFlag>
                  <xsl:if test="/ns0:JournalImportRq/ns0:ErrorToSuspenseFlag/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:JournalImportRq/ns0:ErrorToSuspenseFlag/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:JournalImportRq/ns0:ErrorToSuspenseFlag"/>
               </ns1:ErrorToSuspenseFlag>
            </xsl:if>
            <xsl:if test="/ns0:JournalImportRq/ns0:SummaryFlag">
               <ns1:SummaryFlag>
                  <xsl:if test="/ns0:JournalImportRq/ns0:SummaryFlag/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:JournalImportRq/ns0:SummaryFlag/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:JournalImportRq/ns0:SummaryFlag"/>
               </ns1:SummaryFlag>
            </xsl:if>
            <xsl:if test="/ns0:JournalImportRq/ns0:ImportDescriptiveFlexField">
               <ns1:ImportDescriptiveFlexField>
                  <xsl:if test="/ns0:JournalImportRq/ns0:ImportDescriptiveFlexField/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:JournalImportRq/ns0:ImportDescriptiveFlexField/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:JournalImportRq/ns0:ImportDescriptiveFlexField"/>
               </ns1:ImportDescriptiveFlexField>
            </xsl:if>
            <xsl:for-each select="/ns0:JournalImportRq/ns0:GlInterface">
               <ns1:GlInterface>
                  <xsl:if test="ns0:Reference4">
                     <ns1:Reference4>
                        <xsl:if test="ns0:Reference4/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference4/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference4"/>
                     </ns1:Reference4>
                  </xsl:if>
                  <xsl:if test="ns0:Reference5">
                     <ns1:Reference5>
                        <xsl:if test="ns0:Reference5/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference5/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference5"/>
                     </ns1:Reference5>
                  </xsl:if>
                  <xsl:if test="ns0:LedgerId">
                     <ns1:LedgerId>
                        <xsl:value-of select="ns0:LedgerId"/>
                     </ns1:LedgerId>
                  </xsl:if>
                  <xsl:if test="ns0:PeriodName">
                     <ns1:PeriodName>
                        <xsl:if test="ns0:PeriodName/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:PeriodName/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:PeriodName"/>
                     </ns1:PeriodName>
                  </xsl:if>
                  <xsl:if test="ns0:AccountingDate">
                     <ns1:AccountingDate>
                        <xsl:value-of select="ns0:AccountingDate"/>
                     </ns1:AccountingDate>
                  </xsl:if>
                  <xsl:if test="ns0:UserJeSourceName">
                     <ns1:UserJeSourceName>
                        <xsl:value-of select="ns0:UserJeSourceName"/>
                     </ns1:UserJeSourceName>
                  </xsl:if>
                  <xsl:if test="ns0:UserJeCategoryName">
                     <ns1:UserJeCategoryName>
                        <xsl:value-of select="ns0:UserJeCategoryName"/>
                     </ns1:UserJeCategoryName>
                  </xsl:if>
                  <xsl:if test="ns0:GroupId">
                     <ns1:GroupId>
                        <xsl:value-of select="ns0:GroupId"/>
                     </ns1:GroupId>
                  </xsl:if>
                  <xsl:if test="ns0:ChartOfAccountsId">
                     <ns1:ChartOfAccountsId>
                        <xsl:if test="ns0:ChartOfAccountsId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:ChartOfAccountsId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:ChartOfAccountsId"/>
                     </ns1:ChartOfAccountsId>
                  </xsl:if>
                  <xsl:if test="ns0:BalanceType">
                     <ns1:BalanceType>
                        <xsl:value-of select="ns0:BalanceType"/>
                     </ns1:BalanceType>
                  </xsl:if>
                  <xsl:if test="ns0:CodeCombinationId">
                     <ns1:CodeCombinationId>
                        <xsl:if test="ns0:CodeCombinationId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:CodeCombinationId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:CodeCombinationId"/>
                     </ns1:CodeCombinationId>
                  </xsl:if>
                  <xsl:if test="ns0:Segment1">
                     <ns1:Segment1>
                        <xsl:if test="ns0:Segment1/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment1/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment1"/>
                     </ns1:Segment1>
                  </xsl:if>
                  <xsl:if test="ns0:Segment2">
                     <ns1:Segment2>
                        <xsl:if test="ns0:Segment2/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment2/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment2"/>
                     </ns1:Segment2>
                  </xsl:if>
                  <xsl:if test="ns0:Segment3">
                     <ns1:Segment3>
                        <xsl:if test="ns0:Segment3/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment3/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment3"/>
                     </ns1:Segment3>
                  </xsl:if>
                  <xsl:if test="ns0:Segment4">
                     <ns1:Segment4>
                        <xsl:if test="ns0:Segment4/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment4/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment4"/>
                     </ns1:Segment4>
                  </xsl:if>
                  <xsl:if test="ns0:Segment5">
                     <ns1:Segment5>
                        <xsl:if test="ns0:Segment5/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment5/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment5"/>
                     </ns1:Segment5>
                  </xsl:if>
                  <xsl:if test="ns0:Segment6">
                     <ns1:Segment6>
                        <xsl:if test="ns0:Segment6/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment6/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment6"/>
                     </ns1:Segment6>
                  </xsl:if>
                  <xsl:if test="ns0:Segment7">
                     <ns1:Segment7>
                        <xsl:if test="ns0:Segment7/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment7/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment7"/>
                     </ns1:Segment7>
                  </xsl:if>
                  <xsl:if test="ns0:Segment8">
                     <ns1:Segment8>
                        <xsl:if test="ns0:Segment8/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment8/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment8"/>
                     </ns1:Segment8>
                  </xsl:if>
                  <xsl:if test="ns0:Segment9">
                     <ns1:Segment9>
                        <xsl:if test="ns0:Segment9/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment9/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment9"/>
                     </ns1:Segment9>
                  </xsl:if>
                  <xsl:if test="ns0:Segment10">
                     <ns1:Segment10>
                        <xsl:if test="ns0:Segment10/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment10/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment10"/>
                     </ns1:Segment10>
                  </xsl:if>
                  <xsl:if test="ns0:Segment11">
                     <ns1:Segment11>
                        <xsl:if test="ns0:Segment11/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment11/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment11"/>
                     </ns1:Segment11>
                  </xsl:if>
                  <xsl:if test="ns0:Segment12">
                     <ns1:Segment12>
                        <xsl:if test="ns0:Segment12/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment12/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment12"/>
                     </ns1:Segment12>
                  </xsl:if>
                  <xsl:if test="ns0:Segment13">
                     <ns1:Segment13>
                        <xsl:if test="ns0:Segment13/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment13/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment13"/>
                     </ns1:Segment13>
                  </xsl:if>
                  <xsl:if test="ns0:Segment14">
                     <ns1:Segment14>
                        <xsl:if test="ns0:Segment14/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment14/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment14"/>
                     </ns1:Segment14>
                  </xsl:if>
                  <xsl:if test="ns0:Segment15">
                     <ns1:Segment15>
                        <xsl:if test="ns0:Segment15/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment15/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment15"/>
                     </ns1:Segment15>
                  </xsl:if>
                  <xsl:if test="ns0:Segment16">
                     <ns1:Segment16>
                        <xsl:if test="ns0:Segment16/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment16/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment16"/>
                     </ns1:Segment16>
                  </xsl:if>
                  <xsl:if test="ns0:Segment17">
                     <ns1:Segment17>
                        <xsl:if test="ns0:Segment17/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment17/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment17"/>
                     </ns1:Segment17>
                  </xsl:if>
                  <xsl:if test="ns0:Segment18">
                     <ns1:Segment18>
                        <xsl:if test="ns0:Segment18/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment18/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment18"/>
                     </ns1:Segment18>
                  </xsl:if>
                  <xsl:if test="ns0:Segment19">
                     <ns1:Segment19>
                        <xsl:if test="ns0:Segment19/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment19/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment19"/>
                     </ns1:Segment19>
                  </xsl:if>
                  <xsl:if test="ns0:Segment20">
                     <ns1:Segment20>
                        <xsl:if test="ns0:Segment20/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment20/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment20"/>
                     </ns1:Segment20>
                  </xsl:if>
                  <xsl:if test="ns0:Segment21">
                     <ns1:Segment21>
                        <xsl:if test="ns0:Segment21/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment21/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment21"/>
                     </ns1:Segment21>
                  </xsl:if>
                  <xsl:if test="ns0:Segment22">
                     <ns1:Segment22>
                        <xsl:if test="ns0:Segment22/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment22/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment22"/>
                     </ns1:Segment22>
                  </xsl:if>
                  <xsl:if test="ns0:Segment23">
                     <ns1:Segment23>
                        <xsl:if test="ns0:Segment23/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment23/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment23"/>
                     </ns1:Segment23>
                  </xsl:if>
                  <xsl:if test="ns0:Segment24">
                     <ns1:Segment24>
                        <xsl:if test="ns0:Segment24/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment24/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment24"/>
                     </ns1:Segment24>
                  </xsl:if>
                  <xsl:if test="ns0:Segment25">
                     <ns1:Segment25>
                        <xsl:if test="ns0:Segment25/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment25/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment25"/>
                     </ns1:Segment25>
                  </xsl:if>
                  <xsl:if test="ns0:Segment26">
                     <ns1:Segment26>
                        <xsl:if test="ns0:Segment26/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment26/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment26"/>
                     </ns1:Segment26>
                  </xsl:if>
                  <xsl:if test="ns0:Segment27">
                     <ns1:Segment27>
                        <xsl:if test="ns0:Segment27/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment27/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment27"/>
                     </ns1:Segment27>
                  </xsl:if>
                  <xsl:if test="ns0:Segment28">
                     <ns1:Segment28>
                        <xsl:if test="ns0:Segment28/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment28/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment28"/>
                     </ns1:Segment28>
                  </xsl:if>
                  <xsl:if test="ns0:Segment29">
                     <ns1:Segment29>
                        <xsl:if test="ns0:Segment29/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment29/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment29"/>
                     </ns1:Segment29>
                  </xsl:if>
                  <xsl:if test="ns0:Segment30">
                     <ns1:Segment30>
                        <xsl:if test="ns0:Segment30/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Segment30/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Segment30"/>
                     </ns1:Segment30>
                  </xsl:if>
                  <xsl:if test="ns0:CurrencyCode">
                     <ns1:CurrencyCode>
                        <xsl:value-of select="ns0:CurrencyCode"/>
                     </ns1:CurrencyCode>
                  </xsl:if>
                  <xsl:if test="ns0:EnteredCrAmount">
                     <ns1:EnteredCrAmount>
                        <xsl:if test="ns0:EnteredCrAmount/@currencyCode">
                           <xsl:attribute name="currencyCode">
                              <xsl:value-of select="ns0:EnteredCrAmount/@currencyCode"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:EnteredCrAmount/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:EnteredCrAmount/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:EnteredCrAmount"/>
                     </ns1:EnteredCrAmount>
                  </xsl:if>
                  <xsl:if test="ns0:EnteredDrAmount">
                     <ns1:EnteredDrAmount>
                        <xsl:if test="ns0:EnteredDrAmount/@currencyCode">
                           <xsl:attribute name="currencyCode">
                              <xsl:value-of select="ns0:EnteredDrAmount/@currencyCode"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:EnteredDrAmount/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:EnteredDrAmount/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:EnteredDrAmount"/>
                     </ns1:EnteredDrAmount>
                  </xsl:if>
                  <xsl:if test="ns0:AccountedCr">
                     <ns1:AccountedCr>
                        <xsl:if test="ns0:AccountedCr/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:AccountedCr/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:AccountedCr"/>
                     </ns1:AccountedCr>
                  </xsl:if>
                  <xsl:if test="ns0:AccountedDr">
                     <ns1:AccountedDr>
                        <xsl:if test="ns0:AccountedDr/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:AccountedDr/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:AccountedDr"/>
                     </ns1:AccountedDr>
                  </xsl:if>
                  <xsl:if test="ns0:StatisticalValue">
                     <ns1:StatisticalValue>
                        <xsl:if test="ns0:StatisticalValue/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:StatisticalValue/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:StatisticalValue"/>
                     </ns1:StatisticalValue>
                  </xsl:if>
                  <xsl:if test="ns0:UserCurrencyConversionType">
                     <ns1:UserCurrencyConversionType>
                        <xsl:if test="ns0:UserCurrencyConversionType/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:UserCurrencyConversionType/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:UserCurrencyConversionType"/>
                     </ns1:UserCurrencyConversionType>
                  </xsl:if>
                  <xsl:if test="ns0:CurrencyConversionDate">
                     <ns1:CurrencyConversionDate>
                        <xsl:if test="ns0:CurrencyConversionDate/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:CurrencyConversionDate/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:CurrencyConversionDate"/>
                     </ns1:CurrencyConversionDate>
                  </xsl:if>
                  <xsl:if test="ns0:CurrencyConversionRate">
                     <ns1:CurrencyConversionRate>
                        <xsl:if test="ns0:CurrencyConversionRate/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:CurrencyConversionRate/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:CurrencyConversionRate"/>
                     </ns1:CurrencyConversionRate>
                  </xsl:if>
                  <xsl:if test="ns0:CurrencyConversionType">
                     <ns1:CurrencyConversionType>
                        <xsl:if test="ns0:CurrencyConversionType/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:CurrencyConversionType/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:CurrencyConversionType"/>
                     </ns1:CurrencyConversionType>
                  </xsl:if>
                  <xsl:if test="ns0:Reference1">
                     <ns1:Reference1>
                        <xsl:if test="ns0:Reference1/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference1/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference1"/>
                     </ns1:Reference1>
                  </xsl:if>
                  <xsl:if test="ns0:Reference2">
                     <ns1:Reference2>
                        <xsl:if test="ns0:Reference2/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference2/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference2"/>
                     </ns1:Reference2>
                  </xsl:if>
                  <xsl:if test="ns0:Reference3">
                     <ns1:Reference3>
                        <xsl:if test="ns0:Reference3/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference3/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference3"/>
                     </ns1:Reference3>
                  </xsl:if>
                  <xsl:if test="ns0:Reference6">
                     <ns1:Reference6>
                        <xsl:if test="ns0:Reference6/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference6/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference6"/>
                     </ns1:Reference6>
                  </xsl:if>
                  <xsl:if test="ns0:Reference7">
                     <ns1:Reference7>
                        <xsl:if test="ns0:Reference7/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference7/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference7"/>
                     </ns1:Reference7>
                  </xsl:if>
                  <xsl:if test="ns0:Reference8">
                     <ns1:Reference8>
                        <xsl:if test="ns0:Reference8/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference8/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference8"/>
                     </ns1:Reference8>
                  </xsl:if>
                  <xsl:if test="ns0:Reference9">
                     <ns1:Reference9>
                        <xsl:if test="ns0:Reference9/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference9/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference9"/>
                     </ns1:Reference9>
                  </xsl:if>
                  <xsl:if test="ns0:Reference10">
                     <ns1:Reference10>
                        <xsl:if test="ns0:Reference10/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference10/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference10"/>
                     </ns1:Reference10>
                  </xsl:if>
                  <xsl:if test="ns0:Reference11">
                     <ns1:Reference11>
                        <xsl:if test="ns0:Reference11/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference11/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference11"/>
                     </ns1:Reference11>
                  </xsl:if>
                  <xsl:if test="ns0:Reference12">
                     <ns1:Reference12>
                        <xsl:if test="ns0:Reference12/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference12/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference12"/>
                     </ns1:Reference12>
                  </xsl:if>
                  <xsl:if test="ns0:Reference13">
                     <ns1:Reference13>
                        <xsl:if test="ns0:Reference13/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference13/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference13"/>
                     </ns1:Reference13>
                  </xsl:if>
                  <xsl:if test="ns0:Reference14">
                     <ns1:Reference14>
                        <xsl:if test="ns0:Reference14/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference14/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference14"/>
                     </ns1:Reference14>
                  </xsl:if>
                  <xsl:if test="ns0:Reference15">
                     <ns1:Reference15>
                        <xsl:if test="ns0:Reference15/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference15/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference15"/>
                     </ns1:Reference15>
                  </xsl:if>
                  <xsl:if test="ns0:Reference16">
                     <ns1:Reference16>
                        <xsl:if test="ns0:Reference16/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference16/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference16"/>
                     </ns1:Reference16>
                  </xsl:if>
                  <xsl:if test="ns0:Reference17">
                     <ns1:Reference17>
                        <xsl:if test="ns0:Reference17/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference17/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference17"/>
                     </ns1:Reference17>
                  </xsl:if>
                  <xsl:if test="ns0:Reference18">
                     <ns1:Reference18>
                        <xsl:if test="ns0:Reference18/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference18/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference18"/>
                     </ns1:Reference18>
                  </xsl:if>
                  <xsl:if test="ns0:Reference19">
                     <ns1:Reference19>
                        <xsl:if test="ns0:Reference19/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference19/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference19"/>
                     </ns1:Reference19>
                  </xsl:if>
                  <xsl:if test="ns0:Reference20">
                     <ns1:Reference20>
                        <xsl:if test="ns0:Reference20/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference20/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference20"/>
                     </ns1:Reference20>
                  </xsl:if>
                  <xsl:if test="ns0:Reference21">
                     <ns1:Reference21>
                        <xsl:if test="ns0:Reference21/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference21/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference21"/>
                     </ns1:Reference21>
                  </xsl:if>
                  <xsl:if test="ns0:Reference22">
                     <ns1:Reference22>
                        <xsl:if test="ns0:Reference22/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference22/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference22"/>
                     </ns1:Reference22>
                  </xsl:if>
                  <xsl:if test="ns0:Reference23">
                     <ns1:Reference23>
                        <xsl:if test="ns0:Reference23/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference23/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference23"/>
                     </ns1:Reference23>
                  </xsl:if>
                  <xsl:if test="ns0:Reference24">
                     <ns1:Reference24>
                        <xsl:if test="ns0:Reference24/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference24/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference24"/>
                     </ns1:Reference24>
                  </xsl:if>
                  <xsl:if test="ns0:Reference25">
                     <ns1:Reference25>
                        <xsl:if test="ns0:Reference25/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference25/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference25"/>
                     </ns1:Reference25>
                  </xsl:if>
                  <xsl:if test="ns0:Reference26">
                     <ns1:Reference26>
                        <xsl:if test="ns0:Reference26/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference26/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference26"/>
                     </ns1:Reference26>
                  </xsl:if>
                  <xsl:if test="ns0:Reference27">
                     <ns1:Reference27>
                        <xsl:if test="ns0:Reference27/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference27/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference27"/>
                     </ns1:Reference27>
                  </xsl:if>
                  <xsl:if test="ns0:Reference28">
                     <ns1:Reference28>
                        <xsl:if test="ns0:Reference28/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference28/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference28"/>
                     </ns1:Reference28>
                  </xsl:if>
                  <xsl:if test="ns0:Reference29">
                     <ns1:Reference29>
                        <xsl:if test="ns0:Reference29/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference29/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference29"/>
                     </ns1:Reference29>
                  </xsl:if>
                  <xsl:if test="ns0:Reference30">
                     <ns1:Reference30>
                        <xsl:if test="ns0:Reference30/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Reference30/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Reference30"/>
                     </ns1:Reference30>
                  </xsl:if>
                  <xsl:if test="ns0:ReferenceDate">
                     <ns1:ReferenceDate>
                        <xsl:if test="ns0:ReferenceDate/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:ReferenceDate/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:ReferenceDate"/>
                     </ns1:ReferenceDate>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute1">
                     <ns1:Attribute1>
                        <xsl:if test="ns0:Attribute1/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute1/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute1"/>
                     </ns1:Attribute1>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute2">
                     <ns1:Attribute2>
                        <xsl:if test="ns0:Attribute2/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute2/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute2"/>
                     </ns1:Attribute2>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute3">
                     <ns1:Attribute3>
                        <xsl:if test="ns0:Attribute3/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute3/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute3"/>
                     </ns1:Attribute3>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute4">
                     <ns1:Attribute4>
                        <xsl:if test="ns0:Attribute4/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute4/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute4"/>
                     </ns1:Attribute4>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute5">
                     <ns1:Attribute5>
                        <xsl:if test="ns0:Attribute5/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute5/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute5"/>
                     </ns1:Attribute5>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute6">
                     <ns1:Attribute6>
                        <xsl:if test="ns0:Attribute6/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute6/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute6"/>
                     </ns1:Attribute6>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute7">
                     <ns1:Attribute7>
                        <xsl:if test="ns0:Attribute7/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute7/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute7"/>
                     </ns1:Attribute7>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute8">
                     <ns1:Attribute8>
                        <xsl:if test="ns0:Attribute8/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute8/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute8"/>
                     </ns1:Attribute8>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute9">
                     <ns1:Attribute9>
                        <xsl:if test="ns0:Attribute9/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute9/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute9"/>
                     </ns1:Attribute9>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute10">
                     <ns1:Attribute10>
                        <xsl:if test="ns0:Attribute10/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute10/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute10"/>
                     </ns1:Attribute10>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute11">
                     <ns1:Attribute11>
                        <xsl:if test="ns0:Attribute11/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute11/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute11"/>
                     </ns1:Attribute11>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute12">
                     <ns1:Attribute12>
                        <xsl:if test="ns0:Attribute12/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute12/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute12"/>
                     </ns1:Attribute12>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute13">
                     <ns1:Attribute13>
                        <xsl:if test="ns0:Attribute13/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute13/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute13"/>
                     </ns1:Attribute13>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute14">
                     <ns1:Attribute14>
                        <xsl:if test="ns0:Attribute14/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute14/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute14"/>
                     </ns1:Attribute14>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute15">
                     <ns1:Attribute15>
                        <xsl:if test="ns0:Attribute15/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute15/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute15"/>
                     </ns1:Attribute15>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute16">
                     <ns1:Attribute16>
                        <xsl:if test="ns0:Attribute16/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute16/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute16"/>
                     </ns1:Attribute16>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute17">
                     <ns1:Attribute17>
                        <xsl:if test="ns0:Attribute17/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute17/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute17"/>
                     </ns1:Attribute17>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute18">
                     <ns1:Attribute18>
                        <xsl:if test="ns0:Attribute18/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute18/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute18"/>
                     </ns1:Attribute18>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute19">
                     <ns1:Attribute19>
                        <xsl:if test="ns0:Attribute19/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute19/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute19"/>
                     </ns1:Attribute19>
                  </xsl:if>
                  <xsl:if test="ns0:Attribute20">
                     <ns1:Attribute20>
                        <xsl:if test="ns0:Attribute20/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Attribute20/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Attribute20"/>
                     </ns1:Attribute20>
                  </xsl:if>
                  <xsl:if test="ns0:AttributeCategory">
                     <ns1:AttributeCategory>
                        <xsl:if test="ns0:AttributeCategory/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:AttributeCategory/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:AttributeCategory"/>
                     </ns1:AttributeCategory>
                  </xsl:if>
                  <xsl:if test="ns0:AttributeCategory2">
                     <ns1:AttributeCategory2>
                        <xsl:if test="ns0:AttributeCategory2/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:AttributeCategory2/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:AttributeCategory2"/>
                     </ns1:AttributeCategory2>
                  </xsl:if>
                  <xsl:if test="ns0:AttributeCategory3">
                     <ns1:AttributeCategory3>
                        <xsl:if test="ns0:AttributeCategory3/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:AttributeCategory3/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:AttributeCategory3"/>
                     </ns1:AttributeCategory3>
                  </xsl:if>
                  <xsl:if test="ns0:AverageJournalFlag">
                     <ns1:AverageJournalFlag>
                        <xsl:if test="ns0:AverageJournalFlag/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:AverageJournalFlag/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:AverageJournalFlag"/>
                     </ns1:AverageJournalFlag>
                  </xsl:if>
                  <xsl:if test="ns0:BalancingSegmentValue">
                     <ns1:BalancingSegmentValue>
                        <xsl:if test="ns0:BalancingSegmentValue/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:BalancingSegmentValue/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:BalancingSegmentValue"/>
                     </ns1:BalancingSegmentValue>
                  </xsl:if>
                  <xsl:if test="ns0:DescrFlexErrorMessage">
                     <ns1:DescrFlexErrorMessage>
                        <xsl:if test="ns0:DescrFlexErrorMessage/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:DescrFlexErrorMessage/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:DescrFlexErrorMessage"/>
                     </ns1:DescrFlexErrorMessage>
                  </xsl:if>
                  <xsl:if test="ns0:GlSlLinkId">
                     <ns1:GlSlLinkId>
                        <xsl:if test="ns0:GlSlLinkId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:GlSlLinkId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:GlSlLinkId"/>
                     </ns1:GlSlLinkId>
                  </xsl:if>
                  <xsl:if test="ns0:GlSlLinkTable">
                     <ns1:GlSlLinkTable>
                        <xsl:if test="ns0:GlSlLinkTable/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:GlSlLinkTable/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:GlSlLinkTable"/>
                     </ns1:GlSlLinkTable>
                  </xsl:if>
                  <xsl:if test="ns0:InvoiceAmount">
                     <ns1:InvoiceAmount>
                        <xsl:if test="ns0:InvoiceAmount/@currencyCode">
                           <xsl:attribute name="currencyCode">
                              <xsl:value-of select="ns0:InvoiceAmount/@currencyCode"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:InvoiceAmount/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:InvoiceAmount/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:InvoiceAmount"/>
                     </ns1:InvoiceAmount>
                  </xsl:if>
                  <xsl:if test="ns0:InvoiceDate">
                     <ns1:InvoiceDate>
                        <xsl:if test="ns0:InvoiceDate/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:InvoiceDate/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:InvoiceDate"/>
                     </ns1:InvoiceDate>
                  </xsl:if>
                  <xsl:if test="ns0:InvoiceIdentifier">
                     <ns1:InvoiceIdentifier>
                        <xsl:if test="ns0:InvoiceIdentifier/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:InvoiceIdentifier/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:InvoiceIdentifier"/>
                     </ns1:InvoiceIdentifier>
                  </xsl:if>
                  <xsl:if test="ns0:JeCategoryName">
                     <ns1:JeCategoryName>
                        <xsl:if test="ns0:JeCategoryName/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:JeCategoryName/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:JeCategoryName"/>
                     </ns1:JeCategoryName>
                  </xsl:if>
                  <xsl:if test="ns0:JeSourceName">
                     <ns1:JeSourceName>
                        <xsl:if test="ns0:JeSourceName/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:JeSourceName/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:JeSourceName"/>
                     </ns1:JeSourceName>
                  </xsl:if>
                  <xsl:if test="ns0:JgzzReconReference">
                     <ns1:JgzzReconReference>
                        <xsl:if test="ns0:JgzzReconReference/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:JgzzReconReference/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:JgzzReconReference"/>
                     </ns1:JgzzReconReference>
                  </xsl:if>
                  <xsl:if test="ns0:ManagementSegmentValue">
                     <ns1:ManagementSegmentValue>
                        <xsl:if test="ns0:ManagementSegmentValue/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:ManagementSegmentValue/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:ManagementSegmentValue"/>
                     </ns1:ManagementSegmentValue>
                  </xsl:if>
                  <xsl:if test="ns0:ObjectVersionNumber">
                     <ns1:ObjectVersionNumber>
                        <xsl:value-of select="ns0:ObjectVersionNumber"/>
                     </ns1:ObjectVersionNumber>
                  </xsl:if>
                  <xsl:if test="ns0:OriginatingBalSegValue">
                     <ns1:OriginatingBalSegValue>
                        <xsl:if test="ns0:OriginatingBalSegValue/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:OriginatingBalSegValue/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:OriginatingBalSegValue"/>
                     </ns1:OriginatingBalSegValue>
                  </xsl:if>
                  <xsl:if test="ns0:SetOfBooksId">
                     <ns1:SetOfBooksId>
                        <xsl:if test="ns0:SetOfBooksId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:SetOfBooksId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SetOfBooksId"/>
                     </ns1:SetOfBooksId>
                  </xsl:if>
                  <xsl:if test="ns0:Status">
                     <ns1:Status>
                        <xsl:value-of select="ns0:Status"/>
                     </ns1:Status>
                  </xsl:if>
                  <xsl:if test="ns0:TaxCode">
                     <ns1:TaxCode>
                        <xsl:if test="ns0:TaxCode/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:TaxCode/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:TaxCode"/>
                     </ns1:TaxCode>
                  </xsl:if>
                  <xsl:if test="ns0:TransactionDate">
                     <ns1:TransactionDate>
                        <xsl:if test="ns0:TransactionDate/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:TransactionDate/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:TransactionDate"/>
                     </ns1:TransactionDate>
                  </xsl:if>
                  <xsl:if test="ns0:USSGLTransactionCode">
                     <ns1:USSGLTransactionCode>
                        <xsl:if test="ns0:USSGLTransactionCode/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:USSGLTransactionCode/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:USSGLTransactionCode"/>
                     </ns1:USSGLTransactionCode>
                  </xsl:if>
                  <xsl:if test="ns0:GlInterfaceId">
                     <ns1:GlInterfaceId>
                        <xsl:if test="ns0:GlInterfaceId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:GlInterfaceId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:GlInterfaceId"/>
                     </ns1:GlInterfaceId>
                  </xsl:if>
                  <xsl:if test="ns0:AccountKFF">
                     <ns1:AccountKFF>
                        <xsl:if test="ns0:AccountKFF/ns0:JgzzReconFlag">
                           <ns3:JgzzReconFlag>
                              <xsl:if test="ns0:AccountKFF/ns0:JgzzReconFlag/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:AccountKFF/ns0:JgzzReconFlag/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:AccountKFF/ns0:JgzzReconFlag"/>
                           </ns3:JgzzReconFlag>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:Reference3">
                           <ns3:Reference3>
                              <xsl:if test="ns0:AccountKFF/ns0:Reference3/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:AccountKFF/ns0:Reference3/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:AccountKFF/ns0:Reference3"/>
                           </ns3:Reference3>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:FinancialCategory">
                           <ns3:FinancialCategory>
                              <xsl:if test="ns0:AccountKFF/ns0:FinancialCategory/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:AccountKFF/ns0:FinancialCategory/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:AccountKFF/ns0:FinancialCategory"/>
                           </ns3:FinancialCategory>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:SummaryFlag">
                           <ns3:SummaryFlag>
                              <xsl:value-of select="ns0:AccountKFF/ns0:SummaryFlag"/>
                           </ns3:SummaryFlag>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:DetailPostingAllowedFlag">
                           <ns3:DetailPostingAllowedFlag>
                              <xsl:value-of select="ns0:AccountKFF/ns0:DetailPostingAllowedFlag"/>
                           </ns3:DetailPostingAllowedFlag>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:AccountType">
                           <ns3:AccountType>
                              <xsl:value-of select="ns0:AccountKFF/ns0:AccountType"/>
                           </ns3:AccountType>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:DetailBudgetingAllowedFlag">
                           <ns3:DetailBudgetingAllowedFlag>
                              <xsl:value-of select="ns0:AccountKFF/ns0:DetailBudgetingAllowedFlag"/>
                           </ns3:DetailBudgetingAllowedFlag>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:_FLEX_StructureInstanceCode">
                           <ns3:_FLEX_StructureInstanceCode>
                              <xsl:value-of select="ns0:AccountKFF/ns0:_FLEX_StructureInstanceCode"/>
                           </ns3:_FLEX_StructureInstanceCode>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:_FLEX_StructureInstanceId">
                           <ns3:_FLEX_StructureInstanceId>
                              <xsl:value-of select="ns0:AccountKFF/ns0:_FLEX_StructureInstanceId"/>
                           </ns3:_FLEX_StructureInstanceId>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:StartDateActive">
                           <ns3:StartDateActive>
                              <xsl:if test="ns0:AccountKFF/ns0:StartDateActive/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:AccountKFF/ns0:StartDateActive/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:AccountKFF/ns0:StartDateActive"/>
                           </ns3:StartDateActive>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:EndDateActive">
                           <ns3:EndDateActive>
                              <xsl:if test="ns0:AccountKFF/ns0:EndDateActive/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:AccountKFF/ns0:EndDateActive/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:AccountKFF/ns0:EndDateActive"/>
                           </ns3:EndDateActive>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:EnabledFlag">
                           <ns3:EnabledFlag>
                              <xsl:value-of select="ns0:AccountKFF/ns0:EnabledFlag"/>
                           </ns3:EnabledFlag>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:_CODE_COMBINATION_ID">
                           <ns3:_CODE_COMBINATION_ID>
                              <xsl:value-of select="ns0:AccountKFF/ns0:_CODE_COMBINATION_ID"/>
                           </ns3:_CODE_COMBINATION_ID>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:_CHART_OF_ACCOUNTS_ID">
                           <ns3:_CHART_OF_ACCOUNTS_ID>
                              <xsl:value-of select="ns0:AccountKFF/ns0:_CHART_OF_ACCOUNTS_ID"/>
                           </ns3:_CHART_OF_ACCOUNTS_ID>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:FND_ACFF_ConcatenatedStorage">
                           <ns3:FND_ACFF_ConcatenatedStorage>
                              <xsl:if test="ns0:AccountKFF/ns0:FND_ACFF_ConcatenatedStorage/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:AccountKFF/ns0:FND_ACFF_ConcatenatedStorage/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:AccountKFF/ns0:FND_ACFF_ConcatenatedStorage"/>
                           </ns3:FND_ACFF_ConcatenatedStorage>
                        </xsl:if>
                        <xsl:if test="ns0:AccountKFF/ns0:FND_ACFF_Delimiter">
                           <ns3:FND_ACFF_Delimiter>
                              <xsl:if test="ns0:AccountKFF/ns0:FND_ACFF_Delimiter/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:AccountKFF/ns0:FND_ACFF_Delimiter/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:AccountKFF/ns0:FND_ACFF_Delimiter"/>
                           </ns3:FND_ACFF_Delimiter>
                        </xsl:if>
                     </ns1:AccountKFF>
                  </xsl:if>
               </ns1:GlInterface>
            </xsl:for-each>
         </tns:interfaceRows>
      </tns:importJournals>
   </xsl:template>
</xsl:stylesheet>