<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbValInvoicesAPBs" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/External/dbValInvoicesAPBs_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="XxerInvoicesApConfTblCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbValInvoicesAPBs"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/AuditControlTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetConfValInvoicesAPRs" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON OCT 10 12:52:12 CDT 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetConfValInvoicesAPRs>
         <cmn:Success/>
         <tns:Return>
            <xsl:for-each select="/ns0:XxerInvoicesApConfTblCollection/ns0:XxerInvoicesApConfTbl">
               <tns:XxerInvoicesApConfTbl>
                  <tns:id>
                     <xsl:value-of select="ns0:id"/>
                  </tns:id>
                  <tns:code>
                     <xsl:value-of select="ns0:code"/>
                  </tns:code>
                  <tns:proccess xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:proccess"/>
                  </tns:proccess>
                  <tns:action xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:action"/>
                  </tns:action>
                  <tns:orderProccess xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:orderProccess"/>
                  </tns:orderProccess>
                  <tns:validationName xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:validationName"/>
                  </tns:validationName>
                  <tns:documentType xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:documentType"/>
                  </tns:documentType>
                  <tns:cfdiVersion>
                     <xsl:value-of select="ns0:cfdiVersion"/>
                  </tns:cfdiVersion>
                  <tns:notificationMessage xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:notificationMessage"/>
                  </tns:notificationMessage>
                  <tns:proccessDesc xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:proccessDesc"/>
                  </tns:proccessDesc>
                  <tns:parameter1 xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:parameter1"/>
                  </tns:parameter1>
                  <tns:parameter2 xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:parameter2"/>
                  </tns:parameter2>
                  <tns:parameter3 xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:parameter3"/>
                  </tns:parameter3>
                  <tns:parameter4 xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:parameter4"/>
                  </tns:parameter4>
                  <tns:parameter5 xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:parameter5"/>
                  </tns:parameter5>
                  <tns:creationDate xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:creationDate"/>
                  </tns:creationDate>
                  <tns:createdBy xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:createdBy"/>
                  </tns:createdBy>
                  <tns:lastUpdateDate xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:lastUpdateDate"/>
                  </tns:lastUpdateDate>
                  <tns:lastUpdatedBy xsi:nil="{ns0:proccess/@xsi:nil}">
                     <xsl:value-of select="ns0:lastUpdatedBy"/>
                  </tns:lastUpdatedBy>
               </tns:XxerInvoicesApConfTbl>
            </xsl:for-each>
         </tns:Return>
      </tns:GetConfValInvoicesAPRs>
   </xsl:template>
</xsl:stylesheet>