<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.oracle.com/apps/scm/commonWorkExecution/workOrderMaterialTransactions/materialTransactionsService/types/" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns1="http://xmlns.oracle.com/apps/scm/commonWorkExecution/workOrderMaterialTransactions/materialTransactionsService/" xmlns:ns3="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns2="http://xmlns.oracle.com/adf/svc/types/" xmlns:ns4="commonj.sdo/xml" xmlns:ns5="commonj.sdo/java" xmlns:ns6="commonj.sdo" xmlns:ns7="http://xmlns.oracle.com/apps/flex/scm/commonWorkExecution/workOrders/" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:sfi="http://soa.estrellaroja.com.mx/StructureFindItems" xmlns:str="http://soa.estrellaroja.com.mx/Items/Structure">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/Modules/Cloud/WorkOrderMaterialTransaction/WorkOrderMaterialTransactionService.xsd"/>
            <oracle-xsl-mapper:rootElement name="createWorkOrderMaterialTransactionsResponse" namespace="http://xmlns.oracle.com/apps/scm/commonWorkExecution/workOrderMaterialTransactions/materialTransactionsService/types/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="CreateOrderTransactionsRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED JUL 12 17:11:13 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CreateOrderTransactionsRs>
         <tns:Return>
            <xsl:if test="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:InterfaceBatchStatus">
               <tns:InterfaceBatchStatus>
                  <xsl:value-of select="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:InterfaceBatchStatus"/>
               </tns:InterfaceBatchStatus>
            </xsl:if>
            <xsl:if test="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:SourceSystemType">
               <tns:SourceSystemType>
                  <xsl:if test="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:SourceSystemType/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:SourceSystemType/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:SourceSystemType"/>
               </tns:SourceSystemType>
            </xsl:if>
            <xsl:if test="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:SourceSystemCode">
               <tns:SourceSystemCode>
                  <xsl:if test="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:SourceSystemCode/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:SourceSystemCode/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:SourceSystemCode"/>
               </tns:SourceSystemCode>
            </xsl:if>
            <xsl:for-each select="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:MaterialTransactionHeader">
               <tns:MaterialTransactionHeader>
                  <xsl:if test="ns1:InterfaceStatusCode">
                     <tns:InterfaceStatusCode>
                        <xsl:value-of select="ns1:InterfaceStatusCode"/>
                     </tns:InterfaceStatusCode>
                  </xsl:if>
                  <xsl:if test="ns1:InvTransactionId">
                     <tns:InvTransactionId>
                        <xsl:if test="ns1:InvTransactionId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:InvTransactionId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:InvTransactionId"/>
                     </tns:InvTransactionId>
                  </xsl:if>
                  <xsl:if test="ns1:HeaderNumber">
                     <tns:HeaderNumber>
                        <xsl:if test="ns1:HeaderNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:HeaderNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:HeaderNumber"/>
                     </tns:HeaderNumber>
                  </xsl:if>
                  <xsl:if test="ns1:Organization">
                     <tns:Organization>
                        <xsl:if test="ns1:Organization/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:Organization/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:Organization"/>
                     </tns:Organization>
                  </xsl:if>
                  <xsl:if test="ns1:WorkOrderNumber">
                     <tns:WorkOrderNumber>
                        <xsl:if test="ns1:WorkOrderNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:WorkOrderNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:WorkOrderNumber"/>
                     </tns:WorkOrderNumber>
                  </xsl:if>
                  <xsl:if test="ns1:WorkOrderSerial">
                     <tns:WorkOrderSerial>
                        <xsl:if test="ns1:WorkOrderSerial/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:WorkOrderSerial/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:WorkOrderSerial"/>
                     </tns:WorkOrderSerial>
                  </xsl:if>
                  <xsl:if test="ns1:OperationSequence">
                     <tns:OperationSequence>
                        <xsl:if test="ns1:OperationSequence/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:OperationSequence/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:OperationSequence"/>
                     </tns:OperationSequence>
                  </xsl:if>
                  <xsl:if test="ns1:TransactionDate">
                     <tns:TransactionDate>
                        <xsl:value-of select="ns1:TransactionDate"/>
                     </tns:TransactionDate>
                  </xsl:if>
                  <xsl:if test="ns1:TransactionType">
                     <tns:TransactionType>
                        <xsl:value-of select="ns1:TransactionType"/>
                     </tns:TransactionType>
                  </xsl:if>
                  <xsl:if test="ns1:InventoryItemNumber">
                     <tns:InventoryItemNumber>
                        <xsl:if test="ns1:InventoryItemNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:InventoryItemNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:InventoryItemNumber"/>
                     </tns:InventoryItemNumber>
                  </xsl:if>
                  <xsl:if test="ns1:ItemRevision">
                     <tns:ItemRevision>
                        <xsl:if test="ns1:ItemRevision/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:ItemRevision/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:ItemRevision"/>
                     </tns:ItemRevision>
                  </xsl:if>
                  <xsl:if test="ns1:TransactionQuantity">
                     <tns:TransactionQuantity>
                        <xsl:if test="ns1:TransactionQuantity/@unitCode">
                           <xsl:attribute name="unitCode">
                              <xsl:value-of select="ns1:TransactionQuantity/@unitCode"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:TransactionQuantity"/>
                     </tns:TransactionQuantity>
                  </xsl:if>
                  <xsl:if test="ns1:TransactionUnitOfMeasure">
                     <tns:TransactionUnitOfMeasure>
                        <xsl:if test="ns1:TransactionUnitOfMeasure/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:TransactionUnitOfMeasure/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:TransactionUnitOfMeasure"/>
                     </tns:TransactionUnitOfMeasure>
                  </xsl:if>
                  <xsl:if test="ns1:Subinventory">
                     <tns:Subinventory>
                        <xsl:if test="ns1:Subinventory/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:Subinventory/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:Subinventory"/>
                     </tns:Subinventory>
                  </xsl:if>
                  <xsl:if test="ns1:Locator">
                     <tns:Locator>
                        <xsl:if test="ns1:Locator/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:Locator/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:Locator"/>
                     </tns:Locator>
                  </xsl:if>
                  <xsl:if test="ns1:WorkDefinition">
                     <tns:WorkDefinition>
                        <xsl:if test="ns1:WorkDefinition/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:WorkDefinition/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:WorkDefinition"/>
                     </tns:WorkDefinition>
                  </xsl:if>
                  <xsl:if test="ns1:WorkDefinitionVersion">
                     <tns:WorkDefinitionVersion>
                        <xsl:if test="ns1:WorkDefinitionVersion/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:WorkDefinitionVersion/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:WorkDefinitionVersion"/>
                     </tns:WorkDefinitionVersion>
                  </xsl:if>
                  <xsl:if test="ns1:WorkOrderType">
                     <tns:WorkOrderType>
                        <xsl:if test="ns1:WorkOrderType/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:WorkOrderType/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:WorkOrderType"/>
                     </tns:WorkOrderType>
                  </xsl:if>
                  <xsl:if test="ns1:WorkOrderSubType">
                     <tns:WorkOrderSubType>
                        <xsl:if test="ns1:WorkOrderSubType/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:WorkOrderSubType/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:WorkOrderSubType"/>
                     </tns:WorkOrderSubType>
                  </xsl:if>
                  <xsl:if test="ns1:SourceHeaderReference">
                     <tns:SourceHeaderReference>
                        <xsl:if test="ns1:SourceHeaderReference/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:SourceHeaderReference/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:SourceHeaderReference"/>
                     </tns:SourceHeaderReference>
                  </xsl:if>
                  <xsl:if test="ns1:SourceHeaderReferenceIdentifier">
                     <tns:SourceHeaderReferenceIdentifier>
                        <xsl:if test="ns1:SourceHeaderReferenceIdentifier/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:SourceHeaderReferenceIdentifier/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:SourceHeaderReferenceIdentifier"/>
                     </tns:SourceHeaderReferenceIdentifier>
                  </xsl:if>
                  <xsl:if test="ns1:SourceLineReference">
                     <tns:SourceLineReference>
                        <xsl:if test="ns1:SourceLineReference/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:SourceLineReference/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:SourceLineReference"/>
                     </tns:SourceLineReference>
                  </xsl:if>
                  <xsl:if test="ns1:SourceLineReferenceIdentifier">
                     <tns:SourceLineReferenceIdentifier>
                        <xsl:if test="ns1:SourceLineReferenceIdentifier/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:SourceLineReferenceIdentifier/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:SourceLineReferenceIdentifier"/>
                     </tns:SourceLineReferenceIdentifier>
                  </xsl:if>
                  <xsl:if test="ns1:ReasonCode">
                     <tns:ReasonCode>
                        <xsl:if test="ns1:ReasonCode/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:ReasonCode/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:ReasonCode"/>
                     </tns:ReasonCode>
                  </xsl:if>
                  <xsl:if test="ns1:PONumber">
                     <tns:PONumber>
                        <xsl:if test="ns1:PONumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:PONumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:PONumber"/>
                     </tns:PONumber>
                  </xsl:if>
                  <xsl:if test="ns1:POLineNumber">
                     <tns:POLineNumber>
                        <xsl:if test="ns1:POLineNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:POLineNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:POLineNumber"/>
                     </tns:POLineNumber>
                  </xsl:if>
                  <xsl:if test="ns1:SoldToLegalEntityName">
                     <tns:SoldToLegalEntityName>
                        <xsl:if test="ns1:SoldToLegalEntityName/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:SoldToLegalEntityName/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:SoldToLegalEntityName"/>
                     </tns:SoldToLegalEntityName>
                  </xsl:if>
                  <xsl:if test="ns1:WorkMethod">
                     <tns:WorkMethod>
                        <xsl:if test="ns1:WorkMethod/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:WorkMethod/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:WorkMethod"/>
                     </tns:WorkMethod>
                  </xsl:if>
                  <xsl:for-each select="ns1:MessageDetail">
                     <tns:MessageDetail>
                        <xsl:if test="ns1:ErrorText">
                           <tns:ErrorText>
                              <xsl:if test="ns1:ErrorText/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns1:ErrorText/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns1:ErrorText"/>
                           </tns:ErrorText>
                        </xsl:if>
                        <xsl:if test="ns1:ErrorMessageText">
                           <tns:ErrorMessageText>
                              <xsl:if test="ns1:ErrorMessageText/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns1:ErrorMessageText/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns1:ErrorMessageText"/>
                           </tns:ErrorMessageText>
                        </xsl:if>
                     </tns:MessageDetail>
                  </xsl:for-each>
                  <xsl:for-each select="ns1:TransactionLotHeader">
                     <tns:TransactionLotHeader>
                        <xsl:if test="ns1:LotNumber">
                           <tns:LotNumber>
                              <xsl:value-of select="ns1:LotNumber"/>
                           </tns:LotNumber>
                        </xsl:if>
                        <xsl:if test="ns1:TransactionQuantity">
                           <tns:TransactionQuantity>
                              <xsl:if test="ns1:TransactionQuantity/@unitCode">
                                 <xsl:attribute name="unitCode">
                                    <xsl:value-of select="ns1:TransactionQuantity/@unitCode"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns1:TransactionQuantity"/>
                           </tns:TransactionQuantity>
                        </xsl:if>
                        <xsl:if test="ns1:ParentSerialNumber">
                           <tns:ParentSerialNumber>
                              <xsl:if test="ns1:ParentSerialNumber/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns1:ParentSerialNumber/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns1:ParentSerialNumber"/>
                           </tns:ParentSerialNumber>
                        </xsl:if>
                     </tns:TransactionLotHeader>
                  </xsl:for-each>
                  <xsl:for-each select="ns1:TransactionSerialHeader">
                     <tns:TransactionSerialHeader>
                        <xsl:if test="ns1:LotNumber">
                           <tns:LotNumber>
                              <xsl:if test="ns1:LotNumber/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns1:LotNumber/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns1:LotNumber"/>
                           </tns:LotNumber>
                        </xsl:if>
                        <xsl:if test="ns1:FromSerialNumber">
                           <tns:FromSerialNumber>
                              <xsl:value-of select="ns1:FromSerialNumber"/>
                           </tns:FromSerialNumber>
                        </xsl:if>
                        <xsl:if test="ns1:ToSerialNumber">
                           <tns:ToSerialNumber>
                              <xsl:if test="ns1:ToSerialNumber/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns1:ToSerialNumber/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns1:ToSerialNumber"/>
                           </tns:ToSerialNumber>
                        </xsl:if>
                        <xsl:if test="ns1:ParentSerialNumber">
                           <tns:ParentSerialNumber>
                              <xsl:if test="ns1:ParentSerialNumber/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns1:ParentSerialNumber/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns1:ParentSerialNumber"/>
                           </tns:ParentSerialNumber>
                        </xsl:if>
                     </tns:TransactionSerialHeader>
                  </xsl:for-each>
               </tns:MaterialTransactionHeader>
            </xsl:for-each>
            <xsl:for-each select="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:TransactionInterfaceMessage">
               <tns:TransactionInterfaceMessage>
                  <xsl:if test="ns1:HeaderNumber">
                     <tns:HeaderNumber>
                        <xsl:if test="ns1:HeaderNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:HeaderNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:HeaderNumber"/>
                     </tns:HeaderNumber>
                  </xsl:if>
                  <xsl:if test="ns1:ExceptionMessage">
                     <tns:ExceptionMessage>
                        <xsl:if test="ns1:ExceptionMessage/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:ExceptionMessage/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:ExceptionMessage"/>
                     </tns:ExceptionMessage>
                  </xsl:if>
                  <xsl:if test="ns1:InterfaceBatchId">
                     <tns:InterfaceBatchId>
                        <xsl:if test="ns1:InterfaceBatchId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:InterfaceBatchId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:InterfaceBatchId"/>
                     </tns:InterfaceBatchId>
                  </xsl:if>
               </tns:TransactionInterfaceMessage>
            </xsl:for-each>
            <xsl:for-each select="/ns0:createWorkOrderMaterialTransactionsResponse/ns0:result/ns1:ProcessStatusTranslation">
               <tns:ProcessStatusTranslation>
                  <xsl:if test="ns1:InterfaceBatchDescription">
                     <tns:InterfaceBatchDescription>
                        <xsl:if test="ns1:InterfaceBatchDescription/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns1:InterfaceBatchDescription/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns1:InterfaceBatchDescription"/>
                     </tns:InterfaceBatchDescription>
                  </xsl:if>
                  <xsl:if test="ns1:InterfaceBatchId">
                     <tns:InterfaceBatchId>
                        <xsl:value-of select="ns1:InterfaceBatchId"/>
                     </tns:InterfaceBatchId>
                  </xsl:if>
                  <xsl:if test="ns1:InterfaceBatchName">
                     <tns:InterfaceBatchName>
                        <xsl:value-of select="ns1:InterfaceBatchName"/>
                     </tns:InterfaceBatchName>
                  </xsl:if>
                  <xsl:if test="ns1:Language">
                     <tns:Language>
                        <xsl:value-of select="ns1:Language"/>
                     </tns:Language>
                  </xsl:if>
                  <xsl:if test="ns1:SourceLang">
                     <tns:SourceLang>
                        <xsl:value-of select="ns1:SourceLang"/>
                     </tns:SourceLang>
                  </xsl:if>
               </tns:ProcessStatusTranslation>
            </xsl:for-each>
         </tns:Return>
      </tns:CreateOrderTransactionsRs>
   </xsl:template>
</xsl:stylesheet>