<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:str="http://soa.estrellaroja.com.mx/Items/Structure" xmlns:sfi="http://soa.estrellaroja.com.mx/StructureFindItems" xmlns:ns4="http://xmlns.oracle.com/apps/flex/financials/receivables/receipts/shared/standardReceiptService/commonService/ApplyOnAccountDff/" xmlns:ns6="http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/model/flex/StandardReceiptGdf/" xmlns:ns7="http://xmlns.oracle.com/apps/flex/financials/receivables/receipts/shared/standardReceiptService/commonService/ActivityApplicationGdf/" xmlns:ns1="http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/" xmlns:ns8="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns2="http://xmlns.oracle.com/adf/svc/types/" xmlns:ns9="commonj.sdo/xml" xmlns:ns10="commonj.sdo/java" xmlns:ns3="http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/model/flex/StandardReceiptDff/" xmlns:ns5="http://xmlns.oracle.com/apps/flex/financials/receivables/receipts/shared/standardReceiptService/commonService/ApplyOnAccountGdf/" xmlns:ns11="commonj.sdo" xmlns:ns12="http://xmlns.oracle.com/apps/flex/financials/receivables/receipts/shared/standardReceiptService/commonService/ActivityApplicationDff/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="CreateReceiptRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/Modules/Cloud/Receipt/XMLSchema_-1686185786.xsd"/>
            <oracle-xsl-mapper:rootElement name="createStandardReceipt" namespace="http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON AUG 21 11:56:58 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:createStandardReceipt>
         <tns:standardReceipt>
            <ns1:Amount>
               <xsl:value-of select="/ns0:CreateReceiptRq/ns0:Amount"/>
            </ns1:Amount>
            <xsl:if test="/ns0:CreateReceiptRq/ns0:CashReceiptId">
               <ns1:CashReceiptId>
                  <xsl:value-of select="/ns0:CreateReceiptRq/ns0:CashReceiptId"/>
               </ns1:CashReceiptId>
            </xsl:if>
            <ns1:CustomerSiteUseId>
               <xsl:value-of select="/ns0:CreateReceiptRq/ns0:CustomerSiteUseId"/>
            </ns1:CustomerSiteUseId>
            <ns1:DepositDate>
               <xsl:value-of select="/ns0:CreateReceiptRq/ns0:DepositDate"/>
            </ns1:DepositDate>
            <ns1:CurrencyCode>
               <xsl:value-of select="/ns0:CreateReceiptRq/ns0:CurrencyCode"/>
            </ns1:CurrencyCode>
            <ns1:OrgId>
               <xsl:value-of select="/ns0:CreateReceiptRq/ns0:OrganizationId"/>
            </ns1:OrgId>
            <ns1:CustomerId>
               <xsl:value-of select="/ns0:CreateReceiptRq/ns0:CustomerId"/>
            </ns1:CustomerId>
            <ns1:ReceiptDate>
               <xsl:value-of select="/ns0:CreateReceiptRq/ns0:ReceiptDate"/>
            </ns1:ReceiptDate>
            <ns1:ReceiptMethodId>
               <xsl:value-of select="/ns0:CreateReceiptRq/ns0:ReceiptMethodId"/>
            </ns1:ReceiptMethodId>
            <xsl:if test="/ns0:CreateReceiptRq/ns0:ReceiptNumber">
               <ns1:ReceiptNumber>
                  <xsl:value-of select="/ns0:CreateReceiptRq/ns0:ReceiptNumber"/>
               </ns1:ReceiptNumber>
            </xsl:if>
            <ns1:StandardReceiptFLEXVA>
               <ns3:REFERENCIA>
                  <xsl:value-of select="/ns0:CreateReceiptRq/ns0:ReceiptFlex/ns0:Reference"/>
               </ns3:REFERENCIA>
               <ns3:REFERENCIAAMPLIADA>
                  <xsl:value-of select="/ns0:CreateReceiptRq/ns0:ReceiptFlex/ns0:ReferenceExtend"/>
               </ns3:REFERENCIAAMPLIADA>
               <ns3:CONCEPTO>
                  <xsl:value-of select="/ns0:CreateReceiptRq/ns0:ReceiptFlex/ns0:Concept"/>
               </ns3:CONCEPTO>
               <ns3:FECHAHORA>
                  <xsl:value-of select="/ns0:CreateReceiptRq/ns0:ReceiptFlex/ns0:DateTime"/>
               </ns3:FECHAHORA>
               <ns3:FORMADEPAGO>
                  <xsl:value-of select="/ns0:CreateReceiptRq/ns0:ReceiptFlex/ns0:FormPay"/>
               </ns3:FORMADEPAGO>
               <ns3:superInterface>
                  <xsl:value-of select="/ns0:CreateReceiptRq/ns0:ReceiptFlex/ns0:superInterface"/>
               </ns3:superInterface>
            </ns1:StandardReceiptFLEXVA>
            <xsl:if test="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA">
               <ns1:StandardReceiptGdfVA>
                  <xsl:if test="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:CashReceiptId">
                     <ns6:CashReceiptId>
                        <xsl:value-of select="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:CashReceiptId"/>
                     </ns6:CashReceiptId>
                  </xsl:if>
                  <xsl:if test="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:FLEX_PARAM_GLOBAL_COUNTRY_CODE">
                     <ns6:FLEX_PARAM_GLOBAL_COUNTRY_CODE>
                        <xsl:if test="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:FLEX_PARAM_GLOBAL_COUNTRY_CODE/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:FLEX_PARAM_GLOBAL_COUNTRY_CODE/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:FLEX_PARAM_GLOBAL_COUNTRY_CODE"/>
                     </ns6:FLEX_PARAM_GLOBAL_COUNTRY_CODE>
                  </xsl:if>
                  <xsl:if test="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:__FLEX_Context">
                     <ns6:__FLEX_Context>
                        <xsl:if test="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:__FLEX_Context/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:__FLEX_Context/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:__FLEX_Context"/>
                     </ns6:__FLEX_Context>
                  </xsl:if>
                  <xsl:if test="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:__FLEX_Context_DisplayValue">
                     <ns6:__FLEX_Context_DisplayValue>
                        <xsl:if test="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:__FLEX_Context_DisplayValue/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:__FLEX_Context_DisplayValue/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:__FLEX_Context_DisplayValue"/>
                     </ns6:__FLEX_Context_DisplayValue>
                  </xsl:if>
                  <xsl:if test="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:_FLEX_NumOfSegments">
                     <ns6:_FLEX_NumOfSegments>
                        <xsl:if test="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:_FLEX_NumOfSegments/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:_FLEX_NumOfSegments/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="/ns0:CreateReceiptRq/ns0:StandardReceiptGdfVA/ns0:_FLEX_NumOfSegments"/>
                     </ns6:_FLEX_NumOfSegments>
                  </xsl:if>
               </ns1:StandardReceiptGdfVA>
            </xsl:if>
         </tns:standardReceipt>
      </tns:createStandardReceipt>
   </xsl:template>
</xsl:stylesheet>