<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:tns="http://xmlns.oracle.com/apps/scm/commonWorkExecution/workOrderMaterialTransactions/materialTransactionsService/types/" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns1="http://xmlns.oracle.com/apps/scm/commonWorkExecution/workOrderMaterialTransactions/materialTransactionsService/" xmlns:ns3="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns2="http://xmlns.oracle.com/adf/svc/types/" xmlns:ns4="commonj.sdo/xml" xmlns:ns5="commonj.sdo/java" xmlns:ns6="commonj.sdo" xmlns:ns7="http://xmlns.oracle.com/apps/flex/scm/commonWorkExecution/workOrders/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="CreateOrderTransactionsRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/Modules/Cloud/WorkOrderMaterialTransaction/WorkOrderMaterialTransactionService.xsd"/>
            <oracle-xsl-mapper:rootElement name="createWorkOrderMaterialTransactions" namespace="http://xmlns.oracle.com/apps/scm/commonWorkExecution/workOrderMaterialTransactions/materialTransactionsService/types/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON JUL 10 16:26:35 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:createWorkOrderMaterialTransactions>
         <tns:batchInput>
            <ns1:BatchCode>
               <xsl:value-of select="/ns0:CreateOrderTransactionsRq/ns0:BatchCode"/>
            </ns1:BatchCode>
            <ns1:SourceSystemCode>
               <xsl:value-of select="/ns0:CreateOrderTransactionsRq/ns0:SourceSystemCode"/>
            </ns1:SourceSystemCode>
            <xsl:for-each select="/ns0:CreateOrderTransactionsRq/ns0:MaterialTransactionInput">
               <ns1:MaterialTransactionInput>
                  <xsl:if test="ns0:HeaderNumber">
                     <ns1:HeaderNumber>
                        <xsl:if test="ns0:HeaderNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:HeaderNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:HeaderNumber"/>
                     </ns1:HeaderNumber>
                  </xsl:if>
                  <xsl:if test="ns0:Organization">
                     <ns1:Organization>
                        <xsl:if test="ns0:Organization/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Organization/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Organization"/>
                     </ns1:Organization>
                  </xsl:if>
                  <xsl:if test="ns0:WorkOrderNumber">
                     <ns1:WorkOrderNumber>
                        <xsl:if test="ns0:WorkOrderNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:WorkOrderNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:WorkOrderNumber"/>
                     </ns1:WorkOrderNumber>
                  </xsl:if>
                  <xsl:if test="ns0:WorkOrderSerial">
                     <ns1:WorkOrderSerial>
                        <xsl:if test="ns0:WorkOrderSerial/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:WorkOrderSerial/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:WorkOrderSerial"/>
                     </ns1:WorkOrderSerial>
                  </xsl:if>
                  <xsl:if test="ns0:OperationSequence">
                     <ns1:OperationSequence>
                        <xsl:if test="ns0:OperationSequence/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:OperationSequence/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:OperationSequence"/>
                     </ns1:OperationSequence>
                  </xsl:if>
                  <xsl:if test="ns0:TransactionDate">
                     <ns1:TransactionDate>
                        <xsl:if test="ns0:TransactionDate/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:TransactionDate/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:TransactionDate"/>
                     </ns1:TransactionDate>
                  </xsl:if>
                  <xsl:if test="ns0:TransactionType">
                     <ns1:TransactionType>
                        <xsl:if test="ns0:TransactionType/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:TransactionType/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:TransactionType"/>
                     </ns1:TransactionType>
                  </xsl:if>
                  <xsl:if test="ns0:TransactionNote">
                     <ns1:TransactionNote>
                        <xsl:if test="ns0:TransactionNote/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:TransactionNote/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:TransactionNote"/>
                     </ns1:TransactionNote>
                  </xsl:if>
                  <xsl:if test="ns0:InventoryItemNumber">
                     <ns1:InventoryItemNumber>
                        <xsl:if test="ns0:InventoryItemNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:InventoryItemNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:InventoryItemNumber"/>
                     </ns1:InventoryItemNumber>
                  </xsl:if>
                  <xsl:if test="ns0:ItemRevision">
                     <ns1:ItemRevision>
                        <xsl:if test="ns0:ItemRevision/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:ItemRevision/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:ItemRevision"/>
                     </ns1:ItemRevision>
                  </xsl:if>
                  <xsl:if test="ns0:TransactionQuantity">
                     <ns1:TransactionQuantity>
                        <xsl:if test="ns0:TransactionQuantity/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:TransactionQuantity/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:TransactionQuantity"/>
                     </ns1:TransactionQuantity>
                  </xsl:if>
                  <xsl:if test="ns0:TransactionUnitOfMeasure">
                     <ns1:TransactionUnitOfMeasure>
                        <xsl:if test="ns0:TransactionUnitOfMeasure/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:TransactionUnitOfMeasure/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:TransactionUnitOfMeasure"/>
                     </ns1:TransactionUnitOfMeasure>
                  </xsl:if>
                  <xsl:if test="ns0:Subinventory">
                     <ns1:Subinventory>
                        <xsl:if test="ns0:Subinventory/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Subinventory/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Subinventory"/>
                     </ns1:Subinventory>
                  </xsl:if>
                  <xsl:if test="ns0:Locator">
                     <ns1:Locator>
                        <xsl:if test="ns0:Locator/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:Locator/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Locator"/>
                     </ns1:Locator>
                  </xsl:if>
                  <xsl:if test="ns0:WorkDefinition">
                     <ns1:WorkDefinition>
                        <xsl:if test="ns0:WorkDefinition/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:WorkDefinition/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:WorkDefinition"/>
                     </ns1:WorkDefinition>
                  </xsl:if>
                  <xsl:if test="ns0:WorkOrderSubType">
                     <ns1:WorkOrderSubType>
                        <xsl:if test="ns0:WorkOrderSubType/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:WorkOrderSubType/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:WorkOrderSubType"/>
                     </ns1:WorkOrderSubType>
                  </xsl:if>
                  <xsl:if test="ns0:SourceHeaderReference">
                     <ns1:SourceHeaderReference>
                        <xsl:if test="ns0:SourceHeaderReference/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:SourceHeaderReference/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SourceHeaderReference"/>
                     </ns1:SourceHeaderReference>
                  </xsl:if>
                  <xsl:if test="ns0:SourceHeaderReferenceIdentifier">
                     <ns1:SourceHeaderReferenceIdentifier>
                        <xsl:if test="ns0:SourceHeaderReferenceIdentifier/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:SourceHeaderReferenceIdentifier/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SourceHeaderReferenceIdentifier"/>
                     </ns1:SourceHeaderReferenceIdentifier>
                  </xsl:if>
                  <xsl:if test="ns0:SourceLineReference">
                     <ns1:SourceLineReference>
                        <xsl:if test="ns0:SourceLineReference/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:SourceLineReference/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SourceLineReference"/>
                     </ns1:SourceLineReference>
                  </xsl:if>
                  <xsl:if test="ns0:SourceLineReferenceIdentifier">
                     <ns1:SourceLineReferenceIdentifier>
                        <xsl:if test="ns0:SourceLineReferenceIdentifier/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:SourceLineReferenceIdentifier/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SourceLineReferenceIdentifier"/>
                     </ns1:SourceLineReferenceIdentifier>
                  </xsl:if>
                  <xsl:if test="ns0:ReasonCode">
                     <ns1:ReasonCode>
                        <xsl:if test="ns0:ReasonCode/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:ReasonCode/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:ReasonCode"/>
                     </ns1:ReasonCode>
                  </xsl:if>
                  <xsl:if test="ns0:PONumber">
                     <ns1:PONumber>
                        <xsl:if test="ns0:PONumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:PONumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:PONumber"/>
                     </ns1:PONumber>
                  </xsl:if>
                  <xsl:if test="ns0:POLineNumber">
                     <ns1:POLineNumber>
                        <xsl:if test="ns0:POLineNumber/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:POLineNumber/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:POLineNumber"/>
                     </ns1:POLineNumber>
                  </xsl:if>
                  <xsl:if test="ns0:SoldToLegalEntityName">
                     <ns1:SoldToLegalEntityName>
                        <xsl:if test="ns0:SoldToLegalEntityName/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:SoldToLegalEntityName/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SoldToLegalEntityName"/>
                     </ns1:SoldToLegalEntityName>
                  </xsl:if>
                  <xsl:for-each select="ns0:TransactionLotInput">
                     <ns1:TransactionLotInput>
                        <xsl:if test="ns0:LotNumber">
                           <ns1:LotNumber>
                              <xsl:if test="ns0:LotNumber/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:LotNumber/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:LotNumber"/>
                           </ns1:LotNumber>
                        </xsl:if>
                        <xsl:if test="ns0:TransactionQuantity">
                           <ns1:TransactionQuantity>
                              <xsl:if test="ns0:TransactionQuantity/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:TransactionQuantity/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:TransactionQuantity"/>
                           </ns1:TransactionQuantity>
                        </xsl:if>
                     </ns1:TransactionLotInput>
                  </xsl:for-each>
                  <xsl:for-each select="ns0:TransactionSerialInput">
                     <ns1:TransactionSerialInput>
                        <xsl:if test="ns0:LotNumber">
                           <ns1:LotNumber>
                              <xsl:if test="ns0:LotNumber/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:LotNumber/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:LotNumber"/>
                           </ns1:LotNumber>
                        </xsl:if>
                        <xsl:if test="ns0:FromSerialNumber">
                           <ns1:FromSerialNumber>
                              <xsl:if test="ns0:FromSerialNumber/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:FromSerialNumber/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:FromSerialNumber"/>
                           </ns1:FromSerialNumber>
                        </xsl:if>
                        <xsl:if test="ns0:ToSerialNumber">
                           <ns1:ToSerialNumber>
                              <xsl:if test="ns0:ToSerialNumber/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:ToSerialNumber/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:ToSerialNumber"/>
                           </ns1:ToSerialNumber>
                        </xsl:if>
                     </ns1:TransactionSerialInput>
                  </xsl:for-each>
                  <xsl:if test="ns0:OrderlessTransactionDFF">
                     <ns1:OrderlessTransactionDFF>
                        <xsl:if test="ns0:OrderlessTransactionDFF/ns0:WorkOrderId">
                           <ns7:WorkOrderId>
                              <xsl:value-of select="ns0:OrderlessTransactionDFF/ns0:WorkOrderId"/>
                           </ns7:WorkOrderId>
                        </xsl:if>
                        <xsl:if test="ns0:OrderlessTransactionDFF/ns0:__FLEX_Context">
                           <ns7:__FLEX_Context>
                              <xsl:if test="ns0:OrderlessTransactionDFF/ns0:__FLEX_Context/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:OrderlessTransactionDFF/ns0:__FLEX_Context/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:OrderlessTransactionDFF/ns0:__FLEX_Context"/>
                           </ns7:__FLEX_Context>
                        </xsl:if>
                        <xsl:if test="ns0:OrderlessTransactionDFF/ns0:__FLEX_Context_DisplayValue">
                           <ns7:__FLEX_Context_DisplayValue>
                              <xsl:if test="ns0:OrderlessTransactionDFF/ns0:__FLEX_Context_DisplayValue/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:OrderlessTransactionDFF/ns0:__FLEX_Context_DisplayValue/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:OrderlessTransactionDFF/ns0:__FLEX_Context_DisplayValue"/>
                           </ns7:__FLEX_Context_DisplayValue>
                        </xsl:if>
                        <xsl:if test="ns0:OrderlessTransactionDFF/ns0:_FLEX_NumOfSegments">
                           <ns7:_FLEX_NumOfSegments>
                              <xsl:if test="ns0:OrderlessTransactionDFF/ns0:_FLEX_NumOfSegments/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns0:OrderlessTransactionDFF/ns0:_FLEX_NumOfSegments/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="ns0:OrderlessTransactionDFF/ns0:_FLEX_NumOfSegments"/>
                           </ns7:_FLEX_NumOfSegments>
                        </xsl:if>
                     </ns1:OrderlessTransactionDFF>
                  </xsl:if>
               </ns1:MaterialTransactionInput>
            </xsl:for-each>
         </tns:batchInput>
      </tns:createWorkOrderMaterialTransactions>
   </xsl:template>
</xsl:stylesheet>