<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:ns0="http://soa.estrellaroja.com.mx/CoherenceTec" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/CoherenceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="TERRITORY" namespace="http://soa.estrellaroja.com.mx/CoherenceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/CoherenceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetTerritoryCacheRs" namespace="http://soa.estrellaroja.com.mx/CoherenceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE DEC 26 11:07:20 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:GetTerritoryCacheRs>
         <xsl:if test="string-length (/ns0:TERRITORY/ns0:ROWID ) > 0">
            <cmn:Success/>
         </xsl:if>
         <xsl:if test="string-length (/ns0:TERRITORY/ns0:ROWID ) = 0">
            <cmn:Errors>
               <cmn:Error>
                  <cmn:ErrorCode>SOA-00010</cmn:ErrorCode>
                  <cmn:ShortDescription>No data found</cmn:ShortDescription>
                  <cmn:Description>No found data to match criteria</cmn:Description>
                  <cmn:BusinessProcess>CoherenceTec</cmn:BusinessProcess>
                  <cmn:FailedService>GetTerritoryCache</cmn:FailedService>
                  <cmn:TimeStamp>
                     <xsl:value-of select="xp20:current-dateTime ( )"/>
                  </cmn:TimeStamp>
               </cmn:Error>
            </cmn:Errors>
         </xsl:if>
         <xsl:if test="string-length (/ns0:TERRITORY/ns0:ROWID ) > 0">
            <ns0:Return>
               <ns0:Territory>
                  <ns0:ROWID>
                     <xsl:value-of select="/ns0:TERRITORY/ns0:ROWID"/>
                  </ns0:ROWID>
                  <ns0:TERRITORYCODE>
                     <xsl:value-of select="/ns0:TERRITORY/ns0:TERRITORYCODE"/>
                  </ns0:TERRITORYCODE>
                  <ns0:NLSTERRITORY>
                     <xsl:value-of select="/ns0:TERRITORY/ns0:NLSTERRITORY"/>
                  </ns0:NLSTERRITORY>
                  <ns0:ISOTERRITORYCODE>
                     <xsl:value-of select="/ns0:TERRITORY/ns0:ISOTERRITORYCODE"/>
                  </ns0:ISOTERRITORYCODE>
                  <ns0:TERRITORYSHORTNAME>
                     <xsl:value-of select="/ns0:TERRITORY/ns0:TERRITORYSHORTNAME"/>
                  </ns0:TERRITORYSHORTNAME>
                  <ns0:DESCRIPTION>
                     <xsl:value-of select="/ns0:TERRITORY/ns0:DESCRIPTION"/>
                  </ns0:DESCRIPTION>
                  <ns0:ALTERNATETERRITORYCODE>
                     <xsl:value-of select="/ns0:TERRITORY/ns0:ALTERNATETERRITORYCODE"/>
                  </ns0:ALTERNATETERRITORYCODE>
               </ns0:Territory>
            </ns0:Return>
         </xsl:if>
      </ns0:GetTerritoryCacheRs>
   </xsl:template>
</xsl:stylesheet>