<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:ns0="http://soa.estrellaroja.com.mx/CoherenceTec" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/CoherenceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="OrgCollection" namespace="http://soa.estrellaroja.com.mx/CoherenceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/CoherenceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetOrgListRs" namespace="http://soa.estrellaroja.com.mx/CoherenceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON DEC 25 19:35:54 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:GetOrgListRs>
         <xsl:if test="count (/ns0:OrgCollection/ns0:G_ORGS ) > 0">
            <cmn:Success/>
         </xsl:if>
         <ns0:Return>
            <ns0:OrgCollection>
               <xsl:for-each select="/ns0:OrgCollection/ns0:G_ORGS">
                  <ns0:ORGS>
                     <ns0:SET_ID>
                        <xsl:value-of select="ns0:SET_ID"/>
                     </ns0:SET_ID>
                     <ns0:SET_CODE>
                        <xsl:value-of select="ns0:SET_CODE"/>
                     </ns0:SET_CODE>
                     <ns0:SET_NAME>
                        <xsl:value-of select="ns0:SET_NAME"/>
                     </ns0:SET_NAME>
                     <ns0:DESCRIPTION>
                        <xsl:value-of select="ns0:DESCRIPTION"/>
                     </ns0:DESCRIPTION>
                  </ns0:ORGS>
               </xsl:for-each>
            </ns0:OrgCollection>
         </ns0:Return>
      </ns0:GetOrgListRs>
   </xsl:template>
</xsl:stylesheet>