<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergeCustomerAccount/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns5="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountContact/" xmlns:ns6="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountContactRole/" xmlns:ns1="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns7="http://xmlns.oracle.com/adf/svc/types/" xmlns:sdoJava="commonj.sdo/java" xmlns:ns8="http://xmlns.oracle.com/apps/cdm/foundation/parties/customerAccountService/" xmlns:ns10="http://xmlns.oracle.com/apps/cdm/foundation/parties/partyService/" xmlns:ns12="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountSiteUse/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountRel/" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergeCustomerAccount" xmlns:ns4="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccount/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns9="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/sourceSystemRef/" xmlns:ns11="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/custAccountSite/" xmlns:types="http://xmlns.oracle.com/apps/cdm/foundation/parties/customerAccountService/applicationModule/types/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../Schemas/ERPIntegrationServiceTec.xsd"/>
        <oracle-xsl-mapper:rootElement name="AssignSiteToAccountRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../../../WSDL/Externals/Cloud/Customers/erpRefMergeCustomerAccount.wsdl"/>
        <oracle-xsl-mapper:rootElement name="mergeCustomerAccount" namespace="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergeCustomerAccount/types"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 07 18:30:27 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:mergeCustomerAccount>
      <tns:customerAccount>
        <ns8:CustomerAccountId>
          <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:CustomerAccountId"/>
        </ns8:CustomerAccountId>
        <ns8:PartyId>
          <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:PartyId"/>
        </ns8:PartyId>
        <ns8:CustomerAccountSite>
          <xsl:if test="string-length (/ns0:AssignSiteToAccountRq/ns0:CustomerAccountSiteId ) > 0">
            <ns8:CustomerAccountSiteId>
              <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:CustomerAccountSiteId"/>
            </ns8:CustomerAccountSiteId>
          </xsl:if>
          <ns8:CustomerAccountId>
            <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:CustomerAccountId"/>
          </ns8:CustomerAccountId>
          <ns8:PartySiteId>
            <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:PartySiteId"/>
          </ns8:PartySiteId>
          <ns8:CreatedByModule>HZ_WS</ns8:CreatedByModule>
          <ns8:SetId>
            <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:SetId"/>
          </ns8:SetId>
          <xsl:if test="string-length (/ns0:AssignSiteToAccountRq/ns0:CustomerAccountSiteId ) = 0">
            <ns8:StartDate>2018-01-01T00:00:00</ns8:StartDate>
          </xsl:if>
          <xsl:choose>
            <xsl:when test="string-length (/ns0:AssignSiteToAccountRq/ns0:PartySiteUseId ) = 0">
              <xsl:choose>
                <xsl:when test="contains (/ns0:AssignSiteToAccountRq/ns0:AddressType, &quot;/&quot; )">
                  <ns8:CustomerAccountSiteUse>
                    <ns8:SiteUseCode>
                      <xsl:value-of select="substring-before (/ns0:AssignSiteToAccountRq/ns0:AddressType, &quot;/&quot; )"/>
                    </ns8:SiteUseCode>
                    <ns8:CreatedByModule>HZ_WS</ns8:CreatedByModule>
                    <xsl:if test="string-length (/ns0:AssignSiteToAccountRq/ns0:CustomerAccountSiteId ) = 0">
                      <ns8:StartDate>2018-01-01T00:00:00</ns8:StartDate>
                    </xsl:if>
                  </ns8:CustomerAccountSiteUse>
                  <ns8:CustomerAccountSiteUse>
                    <ns8:SiteUseCode>
                      <xsl:value-of select="substring-after (/ns0:AssignSiteToAccountRq/ns0:AddressType, &quot;/&quot; )"/>
                    </ns8:SiteUseCode>
                    <xsl:if test="string-length (/ns0:AssignSiteToAccountRq/ns0:SiteUseIdPrimaryBillTo ) > 0">
                      <ns8:BillToSiteUseId>
                        <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:SiteUseIdPrimaryBillTo"/>
                      </ns8:BillToSiteUseId>
                    </xsl:if>
                    <ns8:CreatedByModule>HZ_WS</ns8:CreatedByModule>
                    <xsl:if test="string-length (/ns0:AssignSiteToAccountRq/ns0:CustomerAccountSiteId ) = 0">
                      <ns8:StartDate>2018-01-01T00:00:00</ns8:StartDate>
                    </xsl:if>
                  </ns8:CustomerAccountSiteUse>
                </xsl:when>
                <xsl:otherwise>
                  <ns8:CustomerAccountSiteUse>
                    <ns8:SiteUseCode>
                      <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:AddressType"/>
                    </ns8:SiteUseCode>
                    <xsl:if test="string-length (/ns0:AssignSiteToAccountRq/ns0:SiteUseIdPrimaryBillTo ) > 0 and contains (/ns0:AssignSiteToAccountRq/ns0:AddressType, &quot;SHIP_TO&quot; )">
                      <ns8:BillToSiteUseId>
                        <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:SiteUseIdPrimaryBillTo"/>
                      </ns8:BillToSiteUseId>
                    </xsl:if>
                    <ns8:CreatedByModule>HZ_WS</ns8:CreatedByModule>
                    <xsl:if test="string-length (/ns0:AssignSiteToAccountRq/ns0:CustomerAccountSiteId ) = 0">
                      <ns8:StartDate>2018-01-01T00:00:00</ns8:StartDate>
                    </xsl:if>
                  </ns8:CustomerAccountSiteUse>
                </xsl:otherwise>
              </xsl:choose>
            </xsl:when>
            <xsl:otherwise>
              <ns8:CustomerAccountSiteUse>
                <ns8:SiteUseId>
                  <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:PartySiteUseId"/>
                </ns8:SiteUseId>
                <ns8:CustomerAccountSiteId>
                  <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:CustomerAccountSiteId"/>
                </ns8:CustomerAccountSiteId>
                <xsl:if test="string-length (/ns0:AssignSiteToAccountRq/ns0:SiteUseIdPrimaryBillTo ) > 0 and contains (/ns0:AssignSiteToAccountRq/ns0:AddressType, &quot;SHIP_TO&quot; )">
                  <ns8:BillToSiteUseId>
                    <xsl:value-of select="/ns0:AssignSiteToAccountRq/ns0:SiteUseIdPrimaryBillTo"/>
                  </ns8:BillToSiteUseId>
                </xsl:if>
                <ns8:CreatedByModule>HZ_WS</ns8:CreatedByModule>
              </ns8:CustomerAccountSiteUse>
            </xsl:otherwise>
          </xsl:choose>
        </ns8:CustomerAccountSite>
      </tns:customerAccount>
    </tns:mergeCustomerAccount>
  </xsl:template>
</xsl:stylesheet>