<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergeOrganization/types" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergeOrganization" xmlns:ns4="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/partySite/" xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/" xmlns:sdoXML="commonj.sdo/xml" xmlns:ns7="http://xmlns.oracle.com/adf/svc/types/" xmlns:sdoJava="commonj.sdo/java" xmlns:ns9="http://xmlns.oracle.com/apps/cdm/foundation/parties/relationshipService/" xmlns:ns10="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/orgContact/" xmlns:ns12="http://xmlns.oracle.com/apps/cdm/foundation/parties/partyService/" xmlns:ns2="http://xmlns.oracle.com/apps/cdm/foundation/parties/organizationService/applicationModule/" xmlns:ns13="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/relationship/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns5="http://xmlns.oracle.com/apps/cdm/foundation/parties/contactPointService/" xmlns:ns6="http://xmlns.oracle.com/apps/cdm/foundation/parties/organizationService/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:types="http://xmlns.oracle.com/apps/cdm/foundation/parties/organizationService/applicationModule/types/" xmlns:ns8="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/organization/" xmlns:ns11="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/sourceSystemRef/" xmlns:ns1="http://xmlns.oracle.com/apps/cdm/foundation/parties/flex/contactPoint/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Schemas/ERPIntegrationServiceTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="CreateOrganizationSiteRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../../WSDL/Externals/Cloud/Customers/erpRefMergeOrganization.wsdl"/>
            <oracle-xsl-mapper:rootElement name="mergeOrganization" namespace="http://xmlns.oracle.com/pcbpel/adapter/erp/ErpIntegrationServiceTec/ERPIntegrationServiceTec/erpRefMergeOrganization/types"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 07 16:39:41 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:mergeOrganization>
         <tns:organizationParty>
         <ns6:PartyId>
               <xsl:value-of select="/ns0:CreateOrganizationSiteRq/ns0:OrganizationSite/ns0:PartyId"/>
            </ns6:PartyId>
            <ns6:PartySite>
               <ns12:PartyId>
                  <xsl:value-of select="/ns0:CreateOrganizationSiteRq/ns0:OrganizationSite/ns0:PartyId"/>
               </ns12:PartyId>
               <ns12:LocationId>
                  <xsl:value-of select="/ns0:CreateOrganizationSiteRq/ns0:OrganizationSite/ns0:LocationId"/>
               </ns12:LocationId>
               <ns12:StartDateActive>2018-01-01T00:00:00</ns12:StartDateActive>
               <ns12:PartySiteName>
                  <xsl:value-of select="/ns0:CreateOrganizationSiteRq/ns0:OrganizationSite/ns0:PartySiteName"/>
               </ns12:PartySiteName>
               <ns12:CreatedByModule>HZ_WS</ns12:CreatedByModule>
               <xsl:choose>
                  <xsl:when test="contains (/ns0:CreateOrganizationSiteRq/ns0:OrganizationSite/ns0:AddressType, &quot;/&quot; )">
                     <ns12:PartySiteUse>
                        <ns12:BeginDate>2018-01-01T00:00:00</ns12:BeginDate>
                        <ns12:SiteUseType>
                           <xsl:value-of select="substring-before (/ns0:CreateOrganizationSiteRq/ns0:OrganizationSite/ns0:AddressType, &quot;/&quot; )"/>
                        </ns12:SiteUseType>
                        <ns12:CreatedByModule>HZ_WS</ns12:CreatedByModule>
                     </ns12:PartySiteUse>
                     <ns12:PartySiteUse>
                        <ns12:BeginDate>2018-01-01T00:00:00</ns12:BeginDate>
                        <ns12:SiteUseType>
                           <xsl:value-of select="substring-after (/ns0:CreateOrganizationSiteRq/ns0:OrganizationSite/ns0:AddressType, &quot;/&quot; )"/>
                        </ns12:SiteUseType>
                        <ns12:CreatedByModule>HZ_WS</ns12:CreatedByModule>
                     </ns12:PartySiteUse>
                  </xsl:when>
                  <xsl:otherwise>
                     <ns12:PartySiteUse>
                        <ns12:BeginDate>2018-01-01T00:00:00</ns12:BeginDate>
                        <ns12:SiteUseType>
                           <xsl:value-of select="/ns0:CreateOrganizationSiteRq/ns0:OrganizationSite/ns0:AddressType"/>
                        </ns12:SiteUseType>
                        <ns12:CreatedByModule>HZ_WS</ns12:CreatedByModule>
                     </ns12:PartySiteUse>
                  </xsl:otherwise>
               </xsl:choose>
            </ns6:PartySite>
         </tns:organizationParty>
      </tns:mergeOrganization>
   </xsl:template>
</xsl:stylesheet>